import type { BibleBook } from "./types";

/** Mattheüs t/m Openbaring - het Nieuwe Testament. */
export const NEW_TESTAMENT: BibleBook[] = [
  {
    slug: "mattheus",
    name: "Mattheüs",
    position: 40,
    testament: "nieuwe-testament",
    genre: "Evangelie",
    chapters: 28,
    author: "Anoniem; de traditie noemt de tollenaar Mattheüs.",
    written: "Waarschijnlijk 70-90 n.Chr.",
    theme: "Jezus als de beloofde Messias van Israël, in wie de Schriften vervuld worden.",
    blurb:
      "Mattheüs: geslachtsregister, Bergrede, vijf grote redevoeringen en het zendingsbevel. Hoofdlijn, kernverzen en studievragen.",
    summary: [
      "Mattheüs schrijft voor lezers die de Schriften kennen. Zijn evangelie begint met een geslachtsregister dat Jezus verankert in Abraham en David, en door het hele boek staat de formule 'opdat vervuld zou worden hetgeen gesproken is'. Hij haalt het Oude Testament vaker aan dan de andere evangelisten.",
      "Het boek is opvallend geordend rond vijf grote redevoeringen, elk afgesloten met dezelfde overgangszin: de Bergrede (5-7), de uitzendingsrede (10), de gelijkenissen van het Koninkrijk (13), de gemeenterede (18) en de rede over de laatste dingen (24-25). Veel uitleggers zien daarin een bewuste echo van de vijf boeken van Mozes.",
      "De Bergrede is het bekendste gedeelte en ook het scherpste: de zaligsprekingen, de zes 'maar Ik zeg u'-uitspraken, het Onze Vader, en de oproep om niet bezorgd te zijn. Het evangelie eindigt op een berg in Galilea met de opdracht om alle volken tot discipelen te maken, en met de belofte 'Ik ben met ulieden al de dagen tot de voleinding der wereld'.",
    ],
    outline: [
      { range: "1-4", title: "Geboorte en begin", summary: "Geslachtsregister, de wijzen, de doop en de verzoeking in de woestijn." },
      { range: "5-7", title: "De Bergrede", summary: "Zaligsprekingen, de vervulling van de wet, het Onze Vader en het huis op de rots." },
      { range: "8-16", title: "Optreden in Galilea", summary: "Wonderen, de uitzending van de twaalf, gelijkenissen en de belijdenis van Petrus." },
      { range: "17-25", title: "Naar Jeruzalem", summary: "Verheerlijking op de berg, de gemeenterede, de intocht en de rede over de laatste dingen." },
      { range: "26-28", title: "Lijden en opstanding", summary: "Het laatste avondmaal, Gethsemané, kruisiging, opstanding en het zendingsbevel." },
    ],
    keyVerses: ["Mattheüs 5:16", "Mattheüs 6:33", "Mattheüs 16:16", "Mattheüs 28:19-20"],
    studyQuestions: [
      "Zoek de vijf redevoeringen op en de terugkerende slotzin. Wat doet die structuur met het geheel?",
      "Wat bedoelt Jezus met 'Ik ben niet gekomen om te ontbinden, maar te vervullen' (5:17)?",
      "Waarom staan er vier vrouwen in het geslachtsregister, en wie zijn ze?",
    ],
  },
  {
    slug: "markus",
    name: "Markus",
    position: 41,
    testament: "nieuwe-testament",
    genre: "Evangelie",
    chapters: 16,
    author: "Anoniem; de traditie noemt Johannes Markus, metgezel van Petrus.",
    written: "Waarschijnlijk rond 65-70 n.Chr.; door de meeste uitleggers als het oudste evangelie beschouwd.",
    theme: "Jezus als de Zoon van God die dient en lijdt - en dat pas aan het kruis wordt herkend.",
    blurb:
      "Markus: het kortste en snelste evangelie, met het messiaanse geheim en de belijdenis van de hoofdman. Hoofdlijn en studievragen.",
    summary: [
      "Markus is het kortste evangelie en het snelste. Het woord 'terstond' staat er tientallen keren in. Er is geen kerstverhaal en geen geslachtsregister; het begint met Johannes de Doper en meteen daarna staat Jezus in het water.",
      "Twee dingen vallen op. Het eerste is het zogenoemde messiaanse geheim: telkens als iemand doorheeft wie Jezus is, verbiedt Hij het rond te vertellen. Het tweede is hoe slecht de discipelen het snappen. Ze zien de wonderen en begrijpen niets; Petrus belijdt Hem als de Christus en krijgt vijf verzen later 'ga weg achter Mij, satanas' te horen.",
      "Het scharnier ligt in hoofdstuk 8. Vanaf daar loopt het boek in één lijn naar Jeruzalem en het kruis, met drie lijdensaankondigingen die de discipelen alle drie missen. De eerste mens die het hardop goed zegt is een Romeinse hoofdman, onder het kruis: 'waarlijk, deze Mens was Gods Zoon'.",
    ],
    outline: [
      { range: "1-8", title: "Wie is Hij?", summary: "Optreden in Galilea, wonderen, gelijkenissen, en de belijdenis van Petrus." },
      { range: "8-10", title: "Op weg", summary: "Drie lijdensaankondigingen en onderwijs over dienen in plaats van heersen." },
      { range: "11-13", title: "In Jeruzalem", summary: "Intocht, tempelreiniging, twistgesprekken en de rede over de laatste dingen." },
      { range: "14-16", title: "Lijden en opstanding", summary: "Zalving, avondmaal, proces, kruis, en het lege graf." },
    ],
    keyVerses: ["Markus 1:15", "Markus 8:29", "Markus 10:45", "Markus 15:39"],
    studyQuestions: [
      "Waarom verbiedt Jezus mensen om te vertellen wie Hij is?",
      "Volg de drie lijdensaankondigingen (8:31, 9:31, 10:33) en de reactie van de discipelen erna. Welk patroon zie je?",
      "Wat betekent 10:45 voor het beeld van leiderschap dat Markus schetst?",
    ],
  },
  {
    slug: "lukas",
    name: "Lukas",
    position: 42,
    testament: "nieuwe-testament",
    genre: "Evangelie",
    chapters: 24,
    author: "Toegeschreven aan Lukas, de arts en metgezel van Paulus.",
    written: "Waarschijnlijk 70-90 n.Chr.",
    theme: "Het evangelie voor wie buiten staan: armen, vrouwen, tollenaars en Samaritanen.",
    blurb:
      "Lukas: het uitvoerigste evangelie, met de kerstgeschiedenis, de barmhartige Samaritaan en de verloren zoon. Hoofdlijn en studievragen.",
    summary: [
      "Lukas opent met een voorwoord dat klinkt als een historicus: hij heeft alles nauwkeurig nagegaan om Theofilus de zekerheid te geven van wat hij geleerd heeft. Zijn evangelie is het langste en het is het eerste deel van een tweeluik - Handelingen is deel twee.",
      "Wat Lukas kenmerkt is voor wie hij oog heeft. Herders horen het geboortebericht als eersten. Vrouwen spelen een grotere rol dan in de andere evangeliën. Een Samaritaan is de held van de bekendste gelijkenis, en een tollenaar gaat gerechtvaardigd naar huis terwijl de Farizeeër dat niet doet. Het Magnificat van Maria zingt over machtigen die van de troon worden gestoten.",
      "Het middendeel is de lange reis naar Jeruzalem (9:51 tot 19:27), waarin het meeste materiaal staat dat alleen Lukas heeft: de barmhartige Samaritaan, de verloren zoon, de rijke man en Lazarus. Het boek eindigt met de Emmaüsgangers, die Jezus pas herkennen bij het breken van het brood.",
    ],
    outline: [
      { range: "1-2", title: "Aankondiging en geboorte", summary: "Zacharias, Maria, de herders en de twaalfjarige Jezus in de tempel." },
      { range: "3-9", title: "Optreden in Galilea", summary: "Doop, verzoeking, de rede in Nazareth, wonderen en de uitzending." },
      { range: "9-19", title: "De reis naar Jeruzalem", summary: "De grote gelijkenissen, onderwijs over bezit, gebed en het Koninkrijk." },
      { range: "19-24", title: "Jeruzalem", summary: "Intocht, avondmaal, kruis, opstanding en de Emmaüsgangers." },
    ],
    keyVerses: ["Lukas 1:46-47", "Lukas 4:18", "Lukas 15:20", "Lukas 19:10"],
    studyQuestions: [
      "Lees de rede in Nazareth (4:16-30). Waarom loopt die zo uit de hand?",
      "De drie gelijkenissen in hoofdstuk 15 horen bij elkaar. Wat voegt elk verhaal toe aan het vorige?",
      "Welke rol spelen bezit en geld in dit evangelie? Zoek vijf plaatsen.",
    ],
  },
  {
    slug: "johannes",
    name: "Johannes",
    position: 43,
    testament: "nieuwe-testament",
    genre: "Evangelie",
    chapters: 21,
    author: "Anoniem; toegeschreven aan 'de discipel dien Jezus liefhad', traditioneel de apostel Johannes.",
    written: "Waarschijnlijk 90-100 n.Chr.",
    theme: "Het Woord is vlees geworden - opdat u gelooft en leven hebt.",
    blurb:
      "Johannes: de proloog, zeven tekenen, zeven Ik-ben-woorden en de afscheidsrede. Hoofdlijn, kernverzen en studievragen.",
    summary: [
      "Johannes is anders dan de drie andere evangeliën. Geen geboorteverhaal maar een proloog die teruggaat tot vóór de schepping: 'in den beginne was het Woord'. Geen korte spreuken maar lange gesprekken - met Nicodemus 's nachts, met een Samaritaanse vrouw bij een put, met Pilatus over waarheid.",
      "Het boek is opgebouwd rond zeven tekenen, van water dat wijn wordt tot de opwekking van Lazarus, en rond zeven 'Ik ben'-uitspraken: het brood des levens, het licht der wereld, de deur, de goede Herder, de opstanding en het leven, de weg, de waarheid en het leven, en de ware Wijnstok.",
      "De hoofdstukken 13 tot 17 vormen de afscheidsrede: de voetwassing, de belofte van de Trooster, de wijnstok en de ranken, en het hogepriesterlijk gebed. Johannes zegt aan het eind zelf waarom hij dit alles opschreef - 'opdat gij gelooft dat Jezus is de Christus, de Zone Gods; en opdat gij, gelovende, het leven hebt in Zijn Naam'.",
    ],
    outline: [
      { range: "1", title: "Proloog", summary: "Het Woord dat vlees werd, en het getuigenis van Johannes de Doper." },
      { range: "2-12", title: "Het boek der tekenen", summary: "Zeven tekenen en de gesprekken eromheen, tot de opwekking van Lazarus." },
      { range: "13-17", title: "De afscheidsrede", summary: "Voetwassing, de Trooster, de wijnstok en het hogepriesterlijk gebed." },
      { range: "18-21", title: "Lijden en opstanding", summary: "Proces, kruis, het lege graf, Thomas, en het herstel van Petrus." },
    ],
    keyVerses: ["Johannes 1:14", "Johannes 3:16", "Johannes 14:6", "Johannes 20:31"],
    studyQuestions: [
      "Zoek de zeven 'Ik ben'-uitspraken. Wat voegt elk beeld toe?",
      "Wat maakt de gesprekken met Nicodemus (3) en de Samaritaanse vrouw (4) elkaars tegenbeeld?",
      "Waarom eindigt Johannes met het gesprek aan het meer in hoofdstuk 21?",
    ],
  },
  {
    slug: "handelingen",
    name: "Handelingen",
    position: 44,
    testament: "nieuwe-testament",
    genre: "Geschiedenis",
    chapters: 28,
    author: "Dezelfde schrijver als het evangelie naar Lukas.",
    written: "Waarschijnlijk 80-90 n.Chr.",
    theme: "Van Jeruzalem tot Rome: hoe het evangelie de grenzen van Israël overschrijdt.",
    blurb:
      "Handelingen: Pinksteren, de eerste gemeente, Paulus' zendingsreizen en de weg naar Rome. Hoofdlijn en studievragen.",
    summary: [
      "Handelingen is deel twee van Lukas' werk en vertelt hoe een groepje ontredderde Galileeërs binnen dertig jaar een beweging wordt die tot in Rome bekend is. De programmazin staat in 1:8: getuigen in Jeruzalem, in heel Judea en Samaria, en tot het uiterste der aarde - en precies zo is het boek geordend.",
      "De eerste helft draait om Petrus en de gemeente in Jeruzalem: Pinksteren, het delen van bezit, de eerste conflicten, Stefanus die gestenigd wordt, en de doorbraak in hoofdstuk 10 wanneer Petrus het huis van de Romein Cornelius binnengaat en moet toegeven dat God geen aannemer des persoons is.",
      "De tweede helft volgt Paulus op drie zendingsreizen door Klein-Azië en Griekenland. Het scharnier is de vergadering in Jeruzalem (hoofdstuk 15) waar wordt besloten dat heidenen geen Joden hoeven te worden om christen te zijn. Het boek eindigt open: Paulus in Rome, in huisarrest, verkondigend 'met alle vrijmoedigheid, onverhinderd'.",
    ],
    outline: [
      { range: "1-7", title: "Jeruzalem", summary: "Hemelvaart, Pinksteren, de eerste gemeente, en Stefanus." },
      { range: "8-12", title: "Judea en Samaria", summary: "Filippus, de bekering van Saulus, Cornelius, en Antiochië." },
      { range: "13-20", title: "De zendingsreizen", summary: "Drie reizen, de vergadering in Jeruzalem, en de gemeenten in Griekenland." },
      { range: "21-28", title: "Naar Rome", summary: "Arrestatie, verdedigingsredes, het beroep op de keizer, schipbreuk en Rome." },
    ],
    keyVerses: ["Handelingen 1:8", "Handelingen 2:42", "Handelingen 4:12", "Handelingen 17:11"],
    studyQuestions: [
      "Hoe is het boek geordend volgens de belofte in 1:8? Zoek de scharnierpunten.",
      "Wat verandert er in hoofdstuk 10-11 voor Petrus zelf, niet alleen voor Cornelius?",
      "Welke besluiten neemt de vergadering in hoofdstuk 15, en op welke gronden?",
    ],
  },
  {
    slug: "romeinen",
    name: "Romeinen",
    position: 45,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 16,
    author: "Paulus, gedicteerd aan Tertius.",
    written: "Waarschijnlijk 56-58 n.Chr., vanuit Korinthe.",
    theme: "Het evangelie als de kracht Gods tot zaligheid, voor Jood en Griek.",
    blurb:
      "Romeinen: rechtvaardiging door geloof, leven door de Geest, Israël, en het praktische slot. Hoofdlijn en studievragen.",
    summary: [
      "Romeinen is de meest systematische brief van Paulus, geschreven aan een gemeente die hij nog nooit heeft bezocht. Hij wil naar Spanje en zoekt in Rome een uitvalsbasis; daarom zet hij hier zorgvuldiger dan elders uiteen wat hij eigenlijk verkondigt.",
      "De opbouw is helder. Eerst de diagnose: heidenen én Joden staan schuldig, 'zij hebben allen gezondigd, en derven de heerlijkheid Gods' (1-3). Dan de kern: gerechtigheid uit geloof, met Abraham als kroongetuige, en de vrede met God die daaruit volgt (3-5). Dan het leven dat erop volgt: gestorven aan de zonde, worstelend met de wet, levend door de Geest, uitlopend op hoofdstuk 8 met zijn slot dat niets ons kan scheiden van de liefde van God.",
      "De hoofdstukken 9 tot 11 gaan over de vraag die Paulus geen rust laat: wat met Israël? Vanaf 12 wordt het praktisch - de gemeente als lichaam, de omgang met de overheid, en het lange geduld met wie zwak is in het geloof.",
    ],
    outline: [
      { range: "1-3", title: "Allen schuldig", summary: "Het evangelie, de toorn over heiden en Jood, en de conclusie dat niemand vrijuit gaat." },
      { range: "3-5", title: "Rechtvaardiging", summary: "Gerechtigheid uit geloof, Abraham, vrede met God, en Adam en Christus." },
      { range: "6-8", title: "Leven door de Geest", summary: "Dood aan de zonde, de worsteling met de wet, en de zekerheid van hoofdstuk 8." },
      { range: "9-11", title: "Israël", summary: "Verkiezing, ongeloof, en de olijfboom waarop heidenen zijn geënt." },
      { range: "12-16", title: "Het geleefde geloof", summary: "Het levend offer, gaven, overheid, de zwakke broeder, en de groeten." },
    ],
    keyVerses: ["Romeinen 1:16", "Romeinen 3:23-24", "Romeinen 8:1", "Romeinen 8:38-39", "Romeinen 12:2"],
    studyQuestions: [
      "Volg het woord 'gerechtigheid' door de eerste vijf hoofdstukken. Wat betekent het telkens?",
      "Wat is het verband tussen hoofdstuk 6 en hoofdstuk 7 - waarom volgt de worsteling ná de bevrijding?",
      "Hoe gebruikt Paulus het beeld van de olijfboom in hoofdstuk 11, en waartegen waarschuwt hij daarmee?",
    ],
  },
  {
    slug: "1-corinthiers",
    name: "1 Corinthiërs",
    position: 46,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 16,
    author: "Paulus, met Sosthenes.",
    written: "Waarschijnlijk 54-55 n.Chr., vanuit Efeze.",
    theme: "Een verdeelde gemeente in een havenstad, en het kruis dat alle status doorstreept.",
    blurb:
      "1 Corinthiërs: partijschappen, het avondmaal, geestelijke gaven, het liefdeshoofdstuk en de opstanding. Hoofdlijn en studievragen.",
    summary: [
      "Korinthe was een rijke, rumoerige havenstad, en de gemeente daar bracht de stad mee naar binnen. Paulus behandelt in deze brief het ene probleem na het andere: partijschappen rond leraren, een rechtszaak tussen gemeenteleden, seksuele moraal, huwelijk en ongehuwd zijn, offervlees, hoofdbedekking, een avondmaal waarbij de rijken al gegeten hebben voordat de armen aankomen, en chaos rond geestelijke gaven.",
      "Zijn antwoord is telkens hetzelfde en het staat aan het begin: het woord van het kruis. Wat de wereld voor wijsheid en status houdt, wordt door een gekruisigde Messias doorgestreept. Daarom is het onmogelijk om in een gemeente een rangorde op te bouwen.",
      "Twee hoofdstukken worden los van de brief het meest gelezen: hoofdstuk 13, over de liefde, dat níet los staat maar middenin het betoog over de gaven, en hoofdstuk 15, de uitvoerigste behandeling van de opstanding in het Nieuwe Testament.",
    ],
    outline: [
      { range: "1-4", title: "Verdeeldheid", summary: "Partijen rond Paulus en Apollos, en het woord van het kruis." },
      { range: "5-7", title: "Moraal en huwelijk", summary: "Tucht, rechtszaken, seksualiteit, huwelijk en ongehuwd blijven." },
      { range: "8-11", title: "Vrijheid en samenkomst", summary: "Offervlees, Paulus' eigen rechten, hoofdbedekking en het avondmaal." },
      { range: "12-14", title: "De gaven", summary: "Het lichaam met vele leden, de weg der liefde, en orde in de samenkomst." },
      { range: "15-16", title: "De opstanding", summary: "Getuigen, de logica van de opstanding, het opstandingslichaam, en slotzaken." },
    ],
    keyVerses: ["1 Corinthiërs 1:18", "1 Corinthiërs 12:12", "1 Corinthiërs 13:13", "1 Corinthiërs 15:3-4"],
    studyQuestions: [
      "Waarom zet Paulus het liefdeshoofdstuk midden tussen de hoofdstukken over de gaven?",
      "Wat is er volgens 11:17-34 precies mis met hun avondmaal?",
      "Wat betekent 15:14 - 'indien Christus niet opgewekt is, zo is dan onze prediking ijdel'?",
    ],
  },
  {
    slug: "2-corinthiers",
    name: "2 Corinthiërs",
    appBook: "2 Corinthiër",
    position: 47,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 13,
    author: "Paulus, met Timotheüs.",
    written: "Waarschijnlijk 55-56 n.Chr., vanuit Macedonië.",
    theme: "Kracht die in zwakheid volbracht wordt.",
    blurb:
      "2 Corinthiërs: de meest persoonlijke brief van Paulus, over lijden, verzoening, geven en de doorn in het vlees. Hoofdlijn en studievragen.",
    summary: [
      "2 Corinthiërs is de meest persoonlijke brief van Paulus. De relatie met de gemeente is beschadigd; er zijn andere apostelen langsgekomen die indrukwekkender spreken en zijn geloofsbrieven in twijfel trekken. Paulus verdedigt zich, maar op een manier die de hele logica van 'indrukwekkend' omkeert.",
      "Hij begint met troost - het woord staat tien keer in de eerste zeven verzen - en met zijn eigen radeloosheid in Asia, waar hij aan het leven wanhoopte. De schat zit in aarden vaten, zegt hij, opdat duidelijk is van wie de kracht is.",
      "De hoofdstukken 8 en 9 gaan over de collecte voor de arme gemeente in Jeruzalem en vormen het uitvoerigste stuk over geven in het Nieuwe Testament. Het slot is een ironische 'roem': als hij dan toch moet opsommen wat hij te bieden heeft, noemt hij schipbreuken, geselingen, gevangenschappen, en een doorn in het vlees die niet is weggenomen, met het antwoord dat hij wél kreeg: 'Mijn genade is u genoeg'.",
    ],
    outline: [
      { range: "1-7", title: "Bediening en verzoening", summary: "Troost in verdrukking, de schat in aarden vaten, en het ambt der verzoening." },
      { range: "8-9", title: "De collecte", summary: "Het voorbeeld van Macedonië, en de blijmoedige gever." },
      { range: "10-13", title: "Verdediging", summary: "De 'super-apostelen', Paulus' roem in zwakheid, en de doorn in het vlees." },
    ],
    keyVerses: ["2 Corinthiërs 1:3-4", "2 Corinthiërs 4:7", "2 Corinthiërs 5:17", "2 Corinthiërs 12:9"],
    studyQuestions: [
      "Wat bedoelt Paulus met 'de schat in aarden vaten', en hoe werkt dat beeld in de rest van de brief?",
      "Welke argumenten gebruikt hij in hoofdstuk 8-9 om de gemeente tot geven te bewegen?",
      "Waarom roemt Paulus juist in zijn zwakheid in plaats van in zijn prestaties?",
    ],
  },
  {
    slug: "galaten",
    name: "Galaten",
    position: 48,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 6,
    author: "Paulus.",
    written: "Waarschijnlijk 48-55 n.Chr.",
    theme: "Er is geen ander evangelie: vrijheid, niet opnieuw een juk.",
    blurb:
      "Galaten: de scherpste brief van Paulus, over de wet, de vrijheid en de vrucht van de Geest. Hoofdlijn en studievragen.",
    summary: [
      "Galaten is de enige brief van Paulus zonder dankzegging aan het begin. In plaats daarvan: 'ik verwonder mij dat gij zo haast wijkende van dengene die u in de genade van Christus geroepen heeft, overgebracht wordt tot een ander evangelie'. Er zijn leraren langsgekomen die eisen dat heidense gelovigen zich laten besnijden.",
      "Paulus verdedigt eerst zijn eigen positie - inclusief het moment waarop hij Petrus in Antiochië publiek tegenging omdat die zich terugtrok van de tafel met heidenen. Daarna komt het argument: Abraham werd gerechtvaardigd door geloof, ruim vóór de wet er was. De wet was een tuchtmeester tot Christus, niet de weg naar God.",
      "Het slot maakt duidelijk dat vrijheid geen losbandigheid is. 'Tot vrijheid zijt gij geroepen' staat vlak naast de opdracht elkaar door de liefde te dienen, en dan volgt de bekendste opsomming van de brief: de werken van het vlees tegenover de vrucht van de Geest.",
    ],
    outline: [
      { range: "1-2", title: "Geen ander evangelie", summary: "Paulus' roeping, het overleg in Jeruzalem, en het conflict met Petrus." },
      { range: "3-4", title: "Geloof en wet", summary: "Abraham, de belofte, de wet als tuchtmeester, en het zoonschap." },
      { range: "5-6", title: "Vrijheid", summary: "Sta in de vrijheid, de vrucht van de Geest, en het dragen van elkaars lasten." },
    ],
    keyVerses: ["Galaten 2:20", "Galaten 3:28", "Galaten 5:1", "Galaten 5:22-23"],
    studyQuestions: [
      "Waarom gaat Paulus Petrus publiek tegen in 2:11-14? Wat stond er op het spel?",
      "Welke rol geeft Paulus aan de wet in 3:19-25?",
      "Waarom is 'vrucht' enkelvoud in 5:22 terwijl er negen dingen worden genoemd?",
    ],
  },
  {
    slug: "efeziers",
    name: "Efeziërs",
    position: 49,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 6,
    author: "Paulus; sommige uitleggers achten de brief van een latere leerling.",
    written: "Waarschijnlijk rond 60-62 n.Chr., vanuit gevangenschap.",
    theme: "Eén nieuwe mens: de muur tussen Jood en heiden is afgebroken.",
    blurb:
      "Efeziërs: uitverkiezing, genade, de muur die afgebroken is, en de wapenrusting Gods. Hoofdlijn en studievragen.",
    summary: [
      "Efeziërs valt netjes in tweeën: drie hoofdstukken over wat God gedaan heeft, drie over hoe je dan leeft. Het scharnier staat in 4:1 - 'zo bid ik u dan, dat gij wandelt waardiglijk der roeping'.",
      "Het eerste deel is één lange lofzang. Uitverkoren vóór de grondlegging der wereld, verlost door het bloed, levend gemaakt terwijl we dood waren in zonden, en dat alles 'uit genade zijt gij zalig geworden door het geloof, en dat niet uit u, het is Gods gave'. Hoofdstuk 2 loopt uit op het punt waar de brief om draait: de scheidsmuur tussen Jood en heiden is weggebroken, en uit twee is één nieuwe mens gemaakt.",
      "Het tweede deel maakt dat concreet: eenheid, waarheid spreken, eerlijk werk, het huwelijk, ouders en kinderen, heren en slaven. En dan het slot met de wapenrusting Gods - een beeld dat vaak losgeknipt wordt gelezen, maar dat hier staat als afsluiting van een brief over samen staan, niet alleen.",
    ],
    outline: [
      { range: "1-3", title: "Wat God gedaan heeft", summary: "De zegen in de hemel, dood en levend gemaakt, en de muur die viel." },
      { range: "4-5", title: "Hoe je dan leeft", summary: "Eenheid, gaven, de nieuwe mens, en het huisgezin." },
      { range: "6", title: "De strijd", summary: "Ouders en kinderen, heren en dienstknechten, en de wapenrusting Gods." },
    ],
    keyVerses: ["Efeziërs 2:8-9", "Efeziërs 2:14", "Efeziërs 4:15", "Efeziërs 6:11"],
    studyQuestions: [
      "Welke muur is er in 2:14 afgebroken, en wat betekende die muur concreet?",
      "Wat is het verband tussen de drie eerste en de drie laatste hoofdstukken?",
      "Wat valt op aan de wapenrusting: welke onderdelen zijn defensief en welke offensief?",
    ],
  },
  {
    slug: "filippenzen",
    name: "Filippenzen",
    position: 50,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 4,
    author: "Paulus, met Timotheüs.",
    written: "Waarschijnlijk rond 60-62 n.Chr., vanuit gevangenschap.",
    theme: "Vreugde die niet afhangt van de omstandigheden.",
    blurb:
      "Filippenzen: de blijdste brief van Paulus, geschreven uit de gevangenis, met de Christushymne in hoofdstuk 2. Hoofdlijn en studievragen.",
    summary: [
      "Filippenzen is een bedankbriefje dat uitgroeide tot een van de warmste teksten van het Nieuwe Testament. De gemeente in Filippi had geld gestuurd; Paulus zit gevangen en schrijft terug. Het woord 'blijdschap' en zijn verwanten staan er ruim een dozijn keer in.",
      "Het hart van de brief is de hymne in 2:5-11, waarschijnlijk een bestaand lied dat Paulus aanhaalt. Christus, in de gestalte Gods, heeft Zichzelf ontledigd, is gehoorzaam geworden tot de dood des kruises, en is daarom uitermate verhoogd. Paulus haalt dat niet aan als leerstuk maar als argument: dénk zo over elkaar.",
      "Daaromheen staan zijn eigen afwegingen: leven of sterven, wat hem winst zou zijn; alles wat hij aan status had, geacht als drek; en het slot over tevredenheid - 'ik heb geleerd vergenoegd te zijn in hetgeen ik ben'.",
    ],
    outline: [
      { range: "1", title: "Gevangen en blij", summary: "Het evangelie gaat door dankzij de boeien; leven is Christus." },
      { range: "2", title: "Dezelfde gezindheid", summary: "De Christushymne, en het voorbeeld van Timotheüs en Epafroditus." },
      { range: "3", title: "Alles verlies", summary: "Paulus' cv, en het jagen naar het doel." },
      { range: "4", title: "Vrede en tevredenheid", summary: "Euodia en Syntyche, verheug u, en het geheim van vergenoegdheid." },
    ],
    keyVerses: ["Filippenzen 1:21", "Filippenzen 2:5-8", "Filippenzen 4:6-7", "Filippenzen 4:13"],
    studyQuestions: [
      "Waarvoor haalt Paulus de Christushymne aan? Let op vers 5 en op wat eraan voorafgaat.",
      "Wat noemt Paulus in 3:4-8 als zijn 'winst', en waarom noemt hij het nu verlies?",
      "Wat betekent 4:13 in zijn eigen context van vergenoegdheid?",
    ],
  },
  {
    slug: "colossenzen",
    name: "Colossenzen",
    position: 51,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 4,
    author: "Paulus, met Timotheüs; door sommige uitleggers aan een leerling toegeschreven.",
    written: "Waarschijnlijk rond 60-62 n.Chr.",
    theme: "In Christus wonen alle schatten van wijsheid - er hoeft niets bij.",
    blurb:
      "Colossenzen: de hymne over Christus als Beeld van de onzienlijke God, tegen een dwaalleer die er iets aan wilde toevoegen. Hoofdlijn en studievragen.",
    summary: [
      "In Kolosse circuleerde een leer die het christelijk geloof wilde aanvullen: met spijswetten, feestdagen, engelenverering en ascese. Paulus' antwoord is niet dat die dingen slecht zijn maar dat ze overbodig zijn geworden.",
      "Zijn argument staat in de hymne van 1:15-20, een van de hoogste christologische teksten in het Nieuwe Testament. Christus is het Beeld van de onzienlijke God, de Eerstgeborene van alle kreatuur, in Hem is alles geschapen, Hij is vóór alles en alles bestaat samen in Hem. Wie dat gelooft, kan geen aanvulling meer zoeken.",
      "Het praktische deel volgt hetzelfde spoor: zoek de dingen die boven zijn, doe de oude mens uit en de nieuwe aan, en laat het woord van Christus rijkelijk wonen. De gedragsregels aan het slot zijn niet nieuw, maar hun motivering wel - 'alles wat gij doet, doet dat van harte, als den Heere en niet den mensen'.",
    ],
    outline: [
      { range: "1", title: "De grootheid van Christus", summary: "Dankzegging, de hymne, en Paulus' dienst voor de gemeente." },
      { range: "2", title: "Tegen de dwaalleer", summary: "Volheid in Hem, en de waardeloosheid van menselijke inzettingen." },
      { range: "3", title: "De nieuwe mens", summary: "Zoek wat boven is, uittrekken en aandoen, en het huisgezin." },
      { range: "4", title: "Slot", summary: "Gebed, wandelen met wijsheid, en persoonlijke groeten." },
    ],
    keyVerses: ["Colossenzen 1:15-17", "Colossenzen 2:9", "Colossenzen 3:2", "Colossenzen 3:23"],
    studyQuestions: [
      "Wat zegt de hymne in 1:15-20 over de verhouding tussen Christus en de schepping?",
      "Welke concrete eisen stelde de dwaalleer (2:16-23), en waarom wijst Paulus ze af?",
      "Vergelijk Colossenzen 3 met Efeziërs 4-5. Wat is hetzelfde en wat verschilt?",
    ],
  },
  {
    slug: "1-thessalonicenzen",
    name: "1 Thessalonicenzen",
    position: 52,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 5,
    author: "Paulus, met Silvanus en Timotheüs.",
    written: "Waarschijnlijk rond 50-51 n.Chr.; mogelijk de oudste brief van Paulus.",
    theme: "Volhouden onder druk, en uitzien naar de komst van de Heere.",
    blurb:
      "1 Thessalonicenzen: waarschijnlijk het oudste geschrift van het Nieuwe Testament, over standhouden en de wederkomst. Hoofdlijn en studievragen.",
    summary: [
      "Paulus was maar kort in Thessalonica geweest - een paar weken - voordat hij de stad uit moest. Deze brief is zijn opluchting nadat Timotheüs terugkwam met goed nieuws: de jonge gemeente staat er nog.",
      "De eerste helft is bijna helemaal terugblik en dankzegging. Paulus verdedigt zich tegen de suggestie dat hij een rondtrekkende praatjesmaker was die zijn gehoor liet zitten, en herinnert eraan dat hij met eigen handen werkte om niemand tot last te zijn.",
      "De tweede helft geeft onderwijs, en één vraag speelt duidelijk in de gemeente: wat gebeurt er met de gelovigen die inmiddels gestorven zijn - lopen zij de komst van de Heere mis? Het antwoord in 4:13-18 is het bekendste gedeelte van de brief. Het slot bevat een reeks korte opdrachten: verblijdt u te allen tijde, bidt zonder ophouden, dankt in alles.",
    ],
    outline: [
      { range: "1-3", title: "Terugblik", summary: "Hun geloof, Paulus' optreden, en de opluchting na Timotheüs' bericht." },
      { range: "4", title: "Heilig leven en de doden", summary: "Seksuele reinheid, stil leven, en wat er gebeurt met wie ontslapen zijn." },
      { range: "5", title: "Waakzaam", summary: "De dag des Heeren als een dief in de nacht, en korte slotopdrachten." },
    ],
    keyVerses: ["1 Thessalonicenzen 1:3", "1 Thessalonicenzen 4:13", "1 Thessalonicenzen 5:16-18"],
    studyQuestions: [
      "Welke vraag leefde er in de gemeente, en hoe beantwoordt Paulus die in 4:13-18?",
      "Hoe beschrijft Paulus in hoofdstuk 2 zijn eigen optreden, en waartegen verdedigt hij zich?",
      "Lees 5:12-22 als een lijst. Welke opdracht vind je het lastigst en waarom?",
    ],
  },
  {
    slug: "2-thessalonicenzen",
    name: "2 Thessalonicenzen",
    position: 53,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 3,
    author: "Paulus, met Silvanus en Timotheüs; auteurschap wordt door sommigen betwist.",
    written: "Waarschijnlijk kort na de eerste brief, rond 51 n.Chr.",
    theme: "De dag des Heeren is nog niet geweest - blijf dus gewoon aan het werk.",
    blurb:
      "2 Thessalonicenzen: correctie op het gerucht dat de dag van de Heere al aangebroken was, en een oproep tot werken. Hoofdlijn en studievragen.",
    summary: [
      "Er gaat een bericht rond in Thessalonica, mogelijk met een vervalste brief 'als van ons', dat de dag des Heeren al aangebroken zou zijn. Sommigen in de gemeente zijn daarop gestopt met werken en teren op anderen.",
      "Paulus corrigeert op twee niveaus. Leerstellig: die dag komt niet zonder dat eerst de afval komt en 'de mens der zonde' geopenbaard wordt - een gedeelte dat notoir moeilijk uit te leggen is en waarover uitleggers het tot vandaag oneens zijn.",
      "Praktisch is hij een stuk directer: 'zo iemand niet wil werken, dat hij ook niet ete'. Hij wijst op zijn eigen voorbeeld - hij at bij niemand het brood voor niets - en draagt de gemeente op zich te onttrekken aan wie ongeregeld wandelt, zonder hem als vijand te behandelen.",
    ],
    outline: [
      { range: "1", title: "Volharding onder vervolging", summary: "Dank voor hun groeiend geloof, en het rechtvaardig oordeel." },
      { range: "2", title: "De dag des Heeren", summary: "Wat er eerst moet gebeuren, en de waarschuwing tegen misleiding." },
      { range: "3", title: "Aan het werk", summary: "Paulus' voorbeeld, en de omgang met wie ongeregeld leeft." },
    ],
    keyVerses: ["2 Thessalonicenzen 2:2", "2 Thessalonicenzen 3:3", "2 Thessalonicenzen 3:10"],
    studyQuestions: [
      "Welk misverstand corrigeert Paulus in hoofdstuk 2, en waarom is dat praktisch zo schadelijk?",
      "Hoe verhoudt 3:10 zich tot de zorg voor wie niet kán werken?",
      "Wat betekent 'onttrekt u van een iegelijk broeder die ongeregeld wandelt' in de praktijk (3:14-15)?",
    ],
  },
  {
    slug: "1-timotheus",
    name: "1 Timotheüs",
    position: 54,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 6,
    author: "Paulus; het auteurschap van de pastorale brieven wordt door veel uitleggers betwist.",
    written: "Waarschijnlijk 62-65 n.Chr., of later door een leerling.",
    theme: "Hoe je je gedraagt in het huis Gods.",
    blurb:
      "1 Timotheüs: instructies voor gemeenteleiding, over dwaalleer, opzieners, weduwen en geld. Hoofdlijn en studievragen.",
    summary: [
      "1 Timotheüs is een handleiding voor een jonge medewerker die in Efeze is achtergebleven met een lastige opdracht: er zijn leraren die zich verliezen in fabels en geslachtsregisters, en die de wet gebruiken zonder te weten waarvoor die dient.",
      "De brief wisselt daarom tussen correctie van die leer en heel praktische regels: hoe er gebeden wordt, welke eisen aan opzieners en diakenen worden gesteld, hoe met weduwen en ouderen wordt omgegaan, hoe slaven en meesters zich verhouden.",
      "Het bekendste slot gaat over geld: 'de geldgierigheid is een wortel van alle kwaad'. Let op de precieze formulering - niet het geld zelf maar de gierigheid, en niet dé wortel maar een wortel. Daarnaast staat de opdracht aan de rijken: rijk te zijn in goede werken, mededeelzaam, gaarne meedelende.",
    ],
    outline: [
      { range: "1", title: "Tegen de dwaalleer", summary: "De opdracht aan Timotheüs, en Paulus' eigen getuigenis." },
      { range: "2-3", title: "In de gemeente", summary: "Gebed, de rol van mannen en vrouwen, en de eisen aan opzieners en diakenen." },
      { range: "4-5", title: "Timotheüs zelf", summary: "Oefening in godzaligheid, omgang met verschillende groepen, en weduwen." },
      { range: "6", title: "Geld en godzaligheid", summary: "Tevredenheid, de geldgierigheid, en de opdracht aan de rijken." },
    ],
    keyVerses: ["1 Timotheüs 1:15", "1 Timotheüs 4:12", "1 Timotheüs 6:6", "1 Timotheüs 6:10"],
    studyQuestions: [
      "Welke eisen worden aan een opziener gesteld (3:1-7), en welke daarvan gaan over karakter en welke over vaardigheid?",
      "Wat zegt 6:6-10 precies over geld, en wat zegt het níet?",
      "Hoe moedigt Paulus Timotheüs aan om met zijn jonge leeftijd om te gaan?",
    ],
  },
  {
    slug: "2-timotheus",
    name: "2 Timotheüs",
    position: 55,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 4,
    author: "Paulus; auteurschap door sommigen betwist.",
    written: "Waarschijnlijk 64-67 n.Chr.",
    theme: "Het laatste woord van een man die weet dat hij niet vrijkomt.",
    blurb:
      "2 Timotheüs: het testament van Paulus, over volhouden, de Schrift, en de goede strijd die gestreden is. Hoofdlijn en studievragen.",
    summary: [
      "2 Timotheüs leest als een testament. Paulus zit opnieuw gevangen, en anders dan de vorige keer verwacht hij niet vrij te komen. Bijna iedereen heeft hem verlaten; alleen Lukas is bij hem. Hij vraagt Timotheüs te komen vóór de winter, en zijn mantel en de boeken mee te nemen.",
      "De brief is één lange aansporing om vol te houden. Schaam je niet voor het getuigenis; lijd verdrukking als een goed krijgsknecht; houd vast wat je gehoord hebt. Er komen zware tijden, zegt hij, waarin mensen leraren zoeken naar hun eigen begeerten en hun oren laten strelen.",
      "Twee gedeelten worden veel geciteerd. Het eerste is 3:16-17 over de Schrift die van God ingegeven is en nuttig tot lering, wederlegging, verbetering en onderwijzing. Het tweede is het slot: 'ik heb den goeden strijd gestreden, ik heb den loop geëindigd, ik heb het geloof behouden'.",
    ],
    outline: [
      { range: "1", title: "Schaam u niet", summary: "Het ongeveinsde geloof van Timotheüs, en de oproep het pand te bewaren." },
      { range: "2", title: "Volhouden", summary: "Krijgsknecht, kampvechter en landman; een arbeider die zich niet hoeft te schamen." },
      { range: "3", title: "Zware tijden", summary: "De mensen van de laatste dagen, en de Schrift die van God ingegeven is." },
      { range: "4", title: "Testament", summary: "Predik het woord, de goede strijd gestreden, en persoonlijke verzoeken." },
    ],
    keyVerses: ["2 Timotheüs 1:7", "2 Timotheüs 2:15", "2 Timotheüs 3:16-17", "2 Timotheüs 4:7"],
    studyQuestions: [
      "Welke drie beelden gebruikt Paulus in 2:3-6, en wat zegt elk beeld over volhouden?",
      "Wat zegt 3:16-17 over waartoe de Schrift nuttig is? Zet de vier woorden op een rij.",
      "Welke persoonlijke details in hoofdstuk 4 laten zien hoe Paulus er op dat moment aan toe was?",
    ],
  },
  {
    slug: "titus",
    name: "Titus",
    position: 56,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 3,
    author: "Paulus; auteurschap door sommigen betwist.",
    written: "Waarschijnlijk 62-66 n.Chr.",
    theme: "Gezonde leer die zichtbaar wordt in goede werken.",
    blurb:
      "Titus: instructies voor de jonge gemeenten op Kreta, over oudsten, gezonde leer en goede werken. Hoofdlijn en studievragen.",
    summary: [
      "Titus is achtergelaten op Kreta om 'hetgeen nog ontbrak' in orde te brengen en in elke stad oudsten aan te stellen. De brief is kort en zakelijk, met dezelfde thema's als 1 Timotheüs maar in gecomprimeerde vorm.",
      "Paulus citeert een Kretenzische dichter over het karakter van de eilandbewoners - een van de weinige keren dat hij heidense literatuur aanhaalt - en gaat dan in op de dwaalleraars die 'hele huizen verkeren' om vuil gewin.",
      "Wat de brief bij elkaar houdt is de koppeling tussen leer en leven. Elke groep in de gemeente krijgt een korte instructie, en telkens volgt de reden: opdat het woord Gods niet gelasterd worde, opdat de leer van God versierd worde. Hoofdstuk 3 zet daar de motivering onder: niet uit werken der rechtvaardigheid, maar naar Zijn barmhartigheid heeft Hij ons zalig gemaakt.",
    ],
    outline: [
      { range: "1", title: "Oudsten en dwaalleraars", summary: "De opdracht op Kreta, de eisen aan oudsten, en de tegenstanders." },
      { range: "2", title: "Gezonde leer per groep", summary: "Ouderen, jongeren, dienstknechten, en de genade die opvoedt." },
      { range: "3", title: "Goede werken", summary: "Onderdanigheid, de barmhartigheid die redde, en het mijden van twistvragen." },
    ],
    keyVerses: ["Titus 1:16", "Titus 2:11-12", "Titus 3:5"],
    studyQuestions: [
      "Wat is het verband tussen 'gezonde leer' en gedrag in deze brief?",
      "Wat leert de genade ons volgens 2:11-12?",
      "Waarom mijdt Paulus twistvragen en geslachtsregisters (3:9)?",
    ],
  },
  {
    slug: "filemon",
    name: "Filémon",
    position: 57,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 1,
    author: "Paulus, met Timotheüs.",
    written: "Waarschijnlijk rond 60-62 n.Chr., vanuit gevangenschap.",
    theme: "Een weggelopen slaaf teruggestuurd als broeder.",
    blurb:
      "Filémon: het kortste briefje van Paulus, over Onesimus, en het meesterlijke beroep dat het doet op vrijwilligheid. Hoofdlijn en studievragen.",
    summary: [
      "Filémon is de kortste brief van Paulus en de meest persoonlijke. Onesimus, een slaaf van Filémon, is weggelopen - waarschijnlijk met schade - en in Rome bij Paulus terechtgekomen, waar hij tot geloof kwam. Paulus stuurt hem terug.",
      "Het briefje is een lesje in overreding. Paulus zegt met zoveel woorden dat hij het als apostel zou kúnnen bevelen, en doet het daarom juist niet: 'zo bid ik u liever door de liefde'. Hij speelt met de naam Onesimus, die 'nuttig' betekent, biedt aan de schade zelf te vergoeden, en herinnert Filémon en passant eraan dat hij hem zijn eigen leven schuldig is.",
      "Wat hij vraagt zegt hij nooit ronduit. Onesimus moet ontvangen worden 'niet meer als een dienstknecht, maar meer dan een dienstknecht, namelijk een geliefde broeder'. Wat dat concreet betekent, laat hij aan Filémon over - en hij schrijft erbij dat hij weet dat die meer zal doen dan hij vraagt.",
    ],
    outline: [
      { range: "1", title: "Het verzoek", summary: "Dank voor Filémons liefde, het pleidooi voor Onesimus, en het aanbod de schade te vergoeden." },
    ],
    keyVerses: ["Filémon 1:10-11", "Filémon 1:16", "Filémon 1:21"],
    studyQuestions: [
      "Welke middelen gebruikt Paulus om Filémon te overtuigen? Maak een lijst.",
      "Waarom beveelt hij niet, terwijl hij zegt dat hij dat wel zou kunnen?",
      "Wat verandert er aan een slavenverhouding als beiden 'broeder' zijn?",
    ],
  },
  {
    slug: "hebreeen",
    name: "Hebreeën",
    position: 58,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 13,
    author: "Onbekend. Het geschrift noemt geen schrijver; talrijke voorstellen zijn gedaan.",
    written: "Waarschijnlijk vóór 70 n.Chr.",
    theme: "Christus is beter: beter dan engelen, dan Mozes, dan de priesters, dan de offers.",
    blurb:
      "Hebreeën: Christus als hogepriester naar de ordening van Melchizedek, en de geloofsgetuigen van hoofdstuk 11. Hoofdlijn en studievragen.",
    summary: [
      "Hebreeën leest minder als brief dan als preek: de schrijver noemt het zelf 'het woord der vermaning'. De lezers zijn Joodse christenen die onder druk staan en overwegen terug te gaan naar wat vertrouwd was.",
      "Het antwoord is één woord, dat als een refrein terugkeert: beter. Christus is meer dan de engelen, meer dan Mozes, meer dan Aäron. Zijn priesterschap is niet uit Levi maar naar de ordening van Melchizedek, en het offer hoeft niet herhaald te worden. De tabernakelvoorschriften uit Leviticus waren een schaduw van wat nu werkelijkheid is.",
      "Tussen de betogen door staan vijf scherpe waarschuwingen om niet af te drijven, en dan komt hoofdstuk 11: de lange lijst van mensen die geloofden zonder te ontvangen wat beloofd was. Het loopt uit op de oproep de loopbaan te lopen met lijdzaamheid, ziende op Jezus, en op een slot vol heel gewone opdrachten - gastvrijheid, trouw in het huwelijk, tevredenheid.",
    ],
    outline: [
      { range: "1-4", title: "Beter dan engelen en Mozes", summary: "God heeft gesproken in de Zoon; de rust die nog overblijft." },
      { range: "5-7", title: "De hogepriester", summary: "Melchizedek, en een priesterschap dat niet overgaat." },
      { range: "8-10", title: "Een beter verbond", summary: "Het nieuwe verbond, het hemelse heiligdom, en het ene offer." },
      { range: "11", title: "Het geloof", summary: "Van Abel tot de profeten: getuigen die geloofden zonder te ontvangen." },
      { range: "12-13", title: "Loop de loopbaan", summary: "De wolk der getuigen, de tucht, en praktische slotvermaningen." },
    ],
    keyVerses: ["Hebreeën 1:1-2", "Hebreeën 4:12", "Hebreeën 11:1", "Hebreeën 12:1-2"],
    studyQuestions: [
      "Tel hoe vaak het woord 'beter' voorkomt. Waarin is Christus telkens beter?",
      "Wat is de rol van Leviticus in het betoog van hoofdstuk 8-10?",
      "Wat hebben de mensen in hoofdstuk 11 gemeen, gelet op vers 13 en 39?",
    ],
  },
  {
    slug: "jakobus",
    name: "Jakobus",
    position: 59,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 5,
    author: "Jakobus; traditioneel de broer van Jezus en leider van de gemeente in Jeruzalem.",
    written: "Onzeker; voorstellen lopen van de jaren 40 tot het einde van de eerste eeuw.",
    theme: "Geloof zonder werken is dood.",
    blurb:
      "Jakobus: praktische wijsheid over beproeving, de tong, rijkdom en het geloof dat zichtbaar wordt. Hoofdlijn en studievragen.",
    summary: [
      "Jakobus lijkt op Spreuken en op de Bergrede: korte, harde uitspraken over hoe je leeft, zonder veel leerstellige uitweiding. Hij springt van onderwerp naar onderwerp - beproeving, wijsheid, armoede en rijkdom, de tong, ruzie, zwerende eden, geduld, gebed voor zieken.",
      "Zijn scherpste passage is 2:14-26 over geloof en werken. Wat baat het als iemand zegt dat hij geloof heeft en zijn broeder laat honger lijden? Geloof zonder werken is dood. Luther had er moeite mee, maar Jakobus en Paulus antwoorden op verschillende vragen: Paulus op de vraag hoe je bij God binnenkomt, Jakobus op de vraag of dat geloof echt is.",
      "Twee andere gedeelten vallen op. Hoofdstuk 2 opent met een messcherpe scène over voorkeursbehandeling van de rijk geklede bezoeker, en hoofdstuk 3 bevat de beroemdste tekst over de tong: een klein lid dat grote dingen roemt, een vuur, een wereld der ongerechtigheid.",
    ],
    outline: [
      { range: "1", title: "Beproeving en wijsheid", summary: "Volharding, bidden om wijsheid, en dader van het woord zijn." },
      { range: "2", title: "Aanzien en werken", summary: "Geen voorkeur voor de rijke, en geloof zonder werken." },
      { range: "3", title: "De tong", summary: "De macht van kleine dingen, en wijsheid van boven." },
      { range: "4-5", title: "Ruzie, rijkdom, gebed", summary: "Waar twisten vandaan komen, waarschuwing aan de rijken, geduld en gebed." },
    ],
    keyVerses: ["Jakobus 1:22", "Jakobus 2:17", "Jakobus 3:5", "Jakobus 5:16"],
    studyQuestions: [
      "Hoe verhoudt Jakobus 2:24 zich tot Romeinen 3:28? Beantwoorden ze dezelfde vraag?",
      "Wat is de aanleiding voor de passage over de tong in hoofdstuk 3?",
      "Welke beelden gebruikt Jakobus voor onstandvastigheid, en waarom werken die zo goed?",
    ],
  },
  {
    slug: "1-petrus",
    name: "1 Petrus",
    position: 60,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 5,
    author: "Petrus, met Silvanus als schrijver.",
    written: "Waarschijnlijk 62-64 n.Chr.",
    theme: "Vreemdelingen in de verstrooiing: hoe je goed leeft terwijl je lijdt.",
    blurb:
      "1 Petrus: een brief aan christenen onder druk, over levende hoop, het koninklijk priesterschap en lijden zonder terug te slaan. Hoofdlijn en studievragen.",
    summary: [
      "1 Petrus is gericht aan gelovigen in Klein-Azië die Petrus aanspreekt als 'vreemdelingen in de verstrooiing'. Zij worden niet door de staat vervolgd maar door hun omgeving gewantrouwd, belasterd en buitengesloten - de vorm van druk die het langst duurt.",
      "Zijn antwoord begint niet met advies maar met een lofzang op de levende hoop en een onverderfelijke erfenis. Vanuit die hoop ontvouwt hij een manier van leven: heilig zijn, elkaar vurig liefhebben, en zo goed leven dat de laster nergens op slaat.",
      "Het lastigste deel is de reeks aanwijzingen over overheid, slaven en huwelijk. Petrus vraagt geen berusting maar een specifieke strategie: geen kwaad met kwaad vergelden, zoals Christus die 'gescholden zijnde, niet wederschold'. Het slot bevat de bekendste uitnodiging van de brief - 'werpt al uw bekommernis op Hem, want Hij zorgt voor u'.",
    ],
    outline: [
      { range: "1", title: "Levende hoop", summary: "De erfenis die bewaard wordt, en de oproep tot heiligheid." },
      { range: "2", title: "Het volk van God", summary: "Levende stenen, koninklijk priesterschap, en het voorbeeld van Christus." },
      { range: "3-4", title: "Leven onder druk", summary: "Huwelijk, antwoord geven op de hoop die in u is, en lijden om der gerechtigheid wil." },
      { range: "5", title: "Herders en kudde", summary: "Aan de oudsten, de tegenstander als briesende leeuw, en de slotzegen." },
    ],
    keyVerses: ["1 Petrus 1:3", "1 Petrus 2:9", "1 Petrus 3:15", "1 Petrus 5:7"],
    studyQuestions: [
      "Wat betekent 'vreemdelingen en bijwoners' voor hoe de lezers in hun samenleving stonden?",
      "Wat vraagt 3:15 precies - en let op de toon die erbij hoort ('met zachtmoedigheid en vreze')?",
      "Hoe gebruikt Petrus het voorbeeld van Christus in 2:21-25?",
    ],
  },
  {
    slug: "2-petrus",
    name: "2 Petrus",
    position: 61,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 3,
    author: "Petrus; het auteurschap is een van de meest besproken kwesties van het Nieuwe Testament.",
    written: "Onzeker; late eerste of vroege tweede eeuw.",
    theme: "Tegen spotters die zeggen dat er niets gebeurt.",
    blurb:
      "2 Petrus: waarschuwing tegen dwaalleraars en tegen spot met de wederkomst, met 'één dag is bij den Heere als duizend jaren'. Hoofdlijn en studievragen.",
    summary: [
      "2 Petrus begint positief: alles wat tot het leven en de godzaligheid nodig is, is gegeven. Daarop volgt een keten van deugden die op elkaar voortbouwen - geloof, deugd, kennis, matigheid, lijdzaamheid, godzaligheid, broederliefde, liefde.",
      "Hoofdstuk 2 slaat om in een felle waarschuwing tegen dwaalleraars. De beeldspraak is genadeloos: bronnen zonder water, wolken door een draaiwind gedreven, een hond die terugkeert tot zijn uitbraaksel. Het gedeelte vertoont opvallende overeenkomsten met de brief van Judas.",
      "Hoofdstuk 3 gaat over spotters die vragen waar de belofte van Zijn toekomst blijft, want alles blijft zoals het was. Het antwoord is niet dat het snel komt, maar dat God anders met tijd omgaat en dat het uitstel lankmoedigheid is: Hij wil niet dat sommigen verloren gaan, maar dat allen tot bekering komen.",
    ],
    outline: [
      { range: "1", title: "Alles gegeven", summary: "De keten van deugden, en de betrouwbaarheid van het profetische woord." },
      { range: "2", title: "Dwaalleraars", summary: "Hun optreden, hun voorbeelden uit het verleden, en hun einde." },
      { range: "3", title: "De dag des Heeren", summary: "De spotters, Gods lankmoedigheid, en de nieuwe hemel en aarde." },
    ],
    keyVerses: ["2 Petrus 1:3", "2 Petrus 1:21", "2 Petrus 3:9"],
    studyQuestions: [
      "Wat is het argument van de spotters in 3:4, en hoe weerlegt Petrus het?",
      "Lees 2 Petrus 2 naast Judas. Wat komt overeen?",
      "Wat betekent 3:9 voor hoe je over uitstel en geduld denkt?",
    ],
  },
  {
    slug: "1-johannes",
    name: "1 Johannes",
    position: 62,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 5,
    author: "Anoniem; toegeschreven aan dezelfde kring als het evangelie naar Johannes.",
    written: "Waarschijnlijk 90-100 n.Chr.",
    theme: "God is licht, God is liefde - en daaraan is te toetsen wat echt is.",
    blurb:
      "1 Johannes: drie toetsen voor echt geloof, met 'God is liefde' en de zekerheid van het eeuwige leven. Hoofdlijn en studievragen.",
    summary: [
      "1 Johannes heeft geen adres, geen groet en geen naam - het leest als een rondzendbrief. De aanleiding is een scheuring: mensen zijn uit de gemeenschap weggegaan, en de achterblijvers zijn onzeker geworden over de vraag wie er nu eigenlijk gelijk heeft.",
      "De schrijver geeft daarom toetsen, die hij in kringen steeds opnieuw langsloopt. Een leerstellige toets: erkent iemand dat Jezus Christus in het vlees gekomen is? Een morele toets: doet iemand de geboden? En een relationele toets: heeft iemand zijn broeder lief? Wie zegt dat hij God liefheeft en zijn broeder haat, is een leugenaar.",
      "De toon is streng en tegelijk buitengewoon warm. 'Kinderkens' staat er telkens. En twee keer schrijft hij de zin waar de hele brief op rust: God is liefde. Het slot geeft de bedoeling: dit is geschreven opdat u weet dat u het eeuwige leven hebt.",
    ],
    outline: [
      { range: "1-2", title: "Wandelen in het licht", summary: "Wat wij gehoord en gezien hebben, belijdenis van zonde, en de nieuwe gebod." },
      { range: "3", title: "Kinderen van God", summary: "Wat wij zijn, en de liefde die zich in daden toont." },
      { range: "4", title: "God is liefde", summary: "Beproef de geesten, en de liefde die de vrees uitdrijft." },
      { range: "5", title: "Zekerheid", summary: "Het geloof dat de wereld overwint, en het getuigenis over de Zoon." },
    ],
    keyVerses: ["1 Johannes 1:9", "1 Johannes 3:18", "1 Johannes 4:8", "1 Johannes 5:13"],
    studyQuestions: [
      "Welke drie toetsen gebruikt Johannes, en waar komen ze telkens terug?",
      "Wat betekent 'God is liefde' in het licht van 4:9-10, waar hij het uitlegt?",
      "Hoe verhoudt 1:8 ('indien wij zeggen dat wij geen zonde hebben') zich tot 3:9?",
    ],
  },
  {
    slug: "2-johannes",
    name: "2 Johannes",
    position: 63,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 1,
    author: "'De ouderling'; toegeschreven aan dezelfde kring als 1 Johannes.",
    written: "Waarschijnlijk 90-100 n.Chr.",
    theme: "Liefhebben en tegelijk niet alles binnenlaten.",
    blurb:
      "2 Johannes: dertien verzen aan 'de uitverkoren vrouw', over waarheid, liefde en rondreizende dwaalleraars. Hoofdlijn en studievragen.",
    summary: [
      "2 Johannes past op één vel papyrus: dertien verzen, gericht aan 'de uitverkoren vrouw en haar kinderen' - vrijwel zeker een gemeente, niet een persoon.",
      "Twee woorden dragen het briefje: waarheid en liefde, en ze staan niet tegenover elkaar. De liefde bestaat erin dat wij naar Zijn geboden wandelen; het gebod is dat wij elkaar liefhebben.",
      "Dan komt de aanleiding. Er zijn rondreizende leraars die niet belijden dat Jezus Christus in het vlees gekomen is. In een tijd waarin gastvrijheid aan reizigers vanzelfsprekend was, is de instructie hard: neem hen niet in huis en groet hen niet. Wie het briefje bestudeert, moet die scherpte niet wegpoetsen maar wel plaatsen: het gaat om leraars die actief komen ontwrichten, niet om mensen die iets anders denken.",
    ],
    outline: [
      { range: "1", title: "Waarheid en waakzaamheid", summary: "Wandelen in de waarheid, het gebod van de liefde, en de omgang met dwaalleraars." },
    ],
    keyVerses: ["2 Johannes 1:6", "2 Johannes 1:7", "2 Johannes 1:10"],
    studyQuestions: [
      "Hoe verhouden waarheid en liefde zich in dit briefje?",
      "Wat is de dwaling waar het om gaat, en waarom is die zo ernstig?",
      "Hoe zou je vers 10 verantwoord toepassen zonder het te misbruiken?",
    ],
  },
  {
    slug: "3-johannes",
    name: "3 Johannes",
    position: 64,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 1,
    author: "'De ouderling'; toegeschreven aan dezelfde kring als 1 en 2 Johannes.",
    written: "Waarschijnlijk 90-100 n.Chr.",
    theme: "Drie mannen, drie manieren om met gezag om te gaan.",
    blurb:
      "3 Johannes: het kortste boek van het Nieuwe Testament, over Gajus, Diotrefes en Demetrius. Hoofdlijn en studievragen.",
    summary: [
      "3 Johannes is het kortste boek van het Nieuwe Testament en gaat over een heel concreet conflict in één gemeente. Er staan drie mensen in.",
      "Gajus wordt geprezen: hij neemt rondreizende broeders op, ook wie hij niet kent, en helpt hen verder op hun reis. Diotrefes doet het tegenovergestelde: hij 'zoekt onder hen de eerste te zijn', erkent het gezag van de ouderling niet, praat kwaad, weigert de broeders te ontvangen en werpt zelfs mensen uit de gemeente die dat wél willen. Demetrius krijgt een goed getuigenis van iedereen.",
      "Het briefje laat zien dat kerkelijke machtsstrijd zo oud is als de kerk zelf, en dat het Nieuwe Testament dat niet verzwijgt. De maatstaf die de schrijver aanlegt is eenvoudig: 'die goed doet, is uit God; maar die kwaad doet, heeft God niet gezien'.",
    ],
    outline: [
      { range: "1", title: "Gajus, Diotrefes, Demetrius", summary: "Lof voor gastvrijheid, een aanklacht tegen machtsmisbruik, en een goed getuigenis." },
    ],
    keyVerses: ["3 Johannes 1:4", "3 Johannes 1:9", "3 Johannes 1:11"],
    studyQuestions: [
      "Wat wordt Diotrefes precies verweten? Zet de verwijten op een rij.",
      "Waarom is gastvrijheid aan reizende broeders in deze tijd zo belangrijk?",
      "Wat is de maatstaf in vers 11, en hoe eenvoudig is die eigenlijk?",
    ],
  },
  {
    slug: "judas",
    name: "Judas",
    position: 65,
    testament: "nieuwe-testament",
    genre: "Brief",
    chapters: 1,
    author: "Judas, 'broeder van Jakobus'; traditioneel een broer van Jezus.",
    written: "Onzeker; late eerste eeuw.",
    theme: "Strijden voor het geloof dat eenmaal overgeleverd is.",
    blurb:
      "Judas: vijfentwintig verzen tegen binnengeslopen dwaalleraars, met een van de mooiste slotzegens van de Bijbel. Hoofdlijn en studievragen.",
    summary: [
      "Judas schrijft dat hij eigenlijk een heel andere brief wilde sturen - over de gemeenschappelijke zaligheid - maar dat de omstandigheden hem dwingen tot iets dringenders: strijd voor het geloof dat eenmaal aan de heiligen overgeleverd is.",
      "De aanleiding zijn mensen die 'ingeslopen' zijn en de genade van God veranderen in ongebondenheid. Judas stapelt voorbeelden op uit de geschiedenis en uit joodse overlevering - inclusief een verwijzing naar het boek Henoch en naar een twist over het lichaam van Mozes, wat het briefje voor uitleggers extra interessant maakt.",
      "Zijn beeldspraak is fel: wolken zonder water, bomen in de late herfst zonder vrucht, dwalende sterren. Maar het slot is opvallend zacht: ontferm u over sommigen, red anderen door vrees, en dan die slotzegen - 'Hem nu, Die machtig is u van struikelen te bewaren'.",
    ],
    outline: [
      { range: "1", title: "Strijd voor het geloof", summary: "De aanleiding, de voorbeelden uit het verleden, de beschrijving van de dwaalleraars, en de slotzegen." },
    ],
    keyVerses: ["Judas 1:3", "Judas 1:22-23", "Judas 1:24-25"],
    studyQuestions: [
      "Welke voorbeelden uit het verleden gebruikt Judas, en wat hebben ze gemeen?",
      "Hoe verhouden de scherpe beelden zich tot de zachte opdracht in vers 22-23?",
      "Wat betekent 'het geloof dat eenmaal den heiligen overgeleverd is'?",
    ],
  },
  {
    slug: "openbaring",
    name: "Openbaring",
    position: 66,
    testament: "nieuwe-testament",
    genre: "Apocalyptiek",
    chapters: 22,
    author: "Johannes, op Patmos; over zijn identiteit bestaat discussie.",
    written: "Waarschijnlijk rond 95 n.Chr.",
    theme: "Het Lam heeft overwonnen - hoe het er ook uitziet.",
    blurb:
      "Openbaring: de zeven brieven, de zegels, bazuinen en schalen, en het nieuwe Jeruzalem. Hoofdlijn, uitlegstromingen en studievragen.",
    summary: [
      "Openbaring is het moeilijkste boek van de Bijbel en tegelijk het enige dat een zegen belooft aan wie het leest. Het is geschreven aan zeven concrete gemeenten in Klein-Azië die onder druk staan, en het gebruikt de beeldtaal van de apocalyptiek: dieren, getallen, kleuren en kosmische taferelen.",
      "Er zijn ruwweg vier manieren waarop het door de eeuwen is uitgelegd. De preteristische leest het over gebeurtenissen in de eerste eeuw, de historische als een overzicht van de kerkgeschiedenis, de futuristische over een nog komende eindtijd, en de idealistische als een tijdloze uitbeelding van de strijd tussen goed en kwaad. Wie het bestudeert, wint erbij te weten welke bril hij opheeft.",
      "Waar de uitleggingen elkaar raken is de kern. Het boek opent met de verhoogde Christus tussen de kandelaren en zeven brieven die pijnlijk concreet zijn. Daarna volgen reeksen van zeven - zegels, bazuinen, schalen - met steeds hemelse tussenscènes waarin het Lam aanbeden wordt. En het eindigt niet in de hemel maar op aarde: een nieuwe hemel en een nieuwe aarde, een stad die neerdaalt, en God die de tranen van de ogen afwist.",
    ],
    outline: [
      { range: "1-3", title: "De zeven brieven", summary: "Het visioen van de Mensenzoon, en zeven brieven aan zeven gemeenten." },
      { range: "4-11", title: "Troon, boek en bazuinen", summary: "De hemelse troonzaal, het Lam dat de zegels opent, en de zeven bazuinen." },
      { range: "12-16", title: "De strijd", summary: "De vrouw en de draak, de twee beesten, en de zeven schalen." },
      { range: "17-20", title: "Babylon valt", summary: "De hoer op het beest, de val van Babylon, en het oordeel." },
      { range: "21-22", title: "Alles nieuw", summary: "De nieuwe hemel en aarde, het nieuwe Jeruzalem, en de rivier van het leven." },
    ],
    keyVerses: ["Openbaring 1:8", "Openbaring 3:20", "Openbaring 5:9", "Openbaring 21:4"],
    studyQuestions: [
      "Lees de zeven brieven (2-3) en zet naast elkaar wat elke gemeente wordt geprezen en verweten.",
      "Welke uitlegstroming lijkt jou het meest overtuigend, en welke tekstgegevens ondersteunen die?",
      "Waarom eindigt het boek met een stad die neerdaalt in plaats van met mensen die opstijgen?",
    ],
  },
];
