import type { BibleBook } from "./types";

/** Job t/m Maleachi - de poëtische boeken en de profeten. */
export const OT_POETRY_PROPHETS: BibleBook[] = [
  {
    slug: "job",
    name: "Job",
    position: 18,
    testament: "oude-testament",
    genre: "Poëzie en wijsheid",
    chapters: 42,
    author: "Anoniem.",
    written: "Onzeker; het boek wordt zeer verschillend gedateerd, van de patriarchale tijd tot na de ballingschap.",
    theme: "Waarom lijdt een rechtvaardige - en wat blijft er over als het antwoord uitblijft?",
    blurb:
      "Job: het lijden van een rechtvaardige, drie vrienden met een sluitend systeem, en Gods antwoord uit de storm. Hoofdlijn en studievragen.",
    summary: [
      "Job is de meest onverbiddelijke tekst in de Bijbel over lijden. Een man die 'oprecht en vroom' is verliest binnen twee hoofdstukken zijn bezit, zijn tien kinderen en zijn gezondheid. De lezer heeft de hemelse scène gezien en weet dus iets wat Job zelf nooit te horen krijgt.",
      "Het grootste deel van het boek is poëzie: drie rondes gesprek tussen Job en zijn vrienden Elifaz, Bildad en Zofar, gevolgd door de jongere Elihu. De vrienden hebben één sluitende theorie - wie lijdt, heeft gezondigd - en passen die met toenemende hardheid toe. Job weigert die verklaring, houdt zijn onschuld vol, en richt zijn klacht rechtstreeks tot God in plaats van over Hem te praten.",
      "Als God dan spreekt, uit een storm, geeft Hij geen verklaring. Hij stelt vragen: over de zee, de morgensterren, de wilde ezel, de struisvogel, de Behemoth. Job krijgt geen antwoord op het waarom maar wel een ontmoeting, en dat blijkt genoeg. In het slot worden juist de vrienden terechtgewezen - 'gij hebt niet recht van Mij gesproken, gelijk Mijn knecht Job'.",
    ],
    outline: [
      { range: "1-2", title: "Proloog", summary: "Jobs voorspoed, twee hemelse scènes en het verlies van alles." },
      { range: "3-31", title: "De gesprekken", summary: "Jobs klacht en drie rondes met Elifaz, Bildad en Zofar." },
      { range: "32-37", title: "Elihu", summary: "Een vierde stem die het lijden als vorming leest." },
      { range: "38-41", title: "God spreekt", summary: "Twee redevoeringen uit de storm, vol vragen over de schepping." },
      { range: "42", title: "Epiloog", summary: "Jobs antwoord, het oordeel over de vrienden en het herstel." },
    ],
    keyVerses: ["Job 1:21", "Job 13:15", "Job 19:25", "Job 42:5"],
    studyQuestions: [
      "Wat zeggen de vrienden dat feitelijk waar is, en waar gaat hun toepassing mis?",
      "God beantwoordt Jobs vraag niet. Wat doet Hij in plaats daarvan, en waarom is dat toereikend voor Job?",
      "Vergelijk Job 1:21 met Job 3. Kan dezelfde man beide zeggen?",
    ],
  },
  {
    slug: "psalmen",
    name: "Psalmen",
    position: 19,
    testament: "oude-testament",
    genre: "Poëzie en wijsheid",
    chapters: 150,
    author: "Meerdere dichters: David, Asaf, de zonen van Korach, Salomo, Mozes en anonieme auteurs.",
    written: "Ontstaan over vele eeuwen; als verzameling voltooid na de ballingschap.",
    theme: "Het volledige gebedsboek van Israël: lof, klacht, dank, schuld en vertrouwen.",
    blurb:
      "Psalmen: 150 gebeden en liederen in vijf boeken. Soorten psalmen, hoofdlijn, kernpsalmen en studievragen.",
    summary: [
      "De Psalmen zijn het gebedsboek van Israël en van de kerk. Ze zijn niet ontstaan als één boek maar als vijf verzamelingen, elk afgesloten met een lofprijzing, en de indeling in vijf 'boeken' wordt vaak gelezen als een echo van de vijf boeken van Mozes.",
      "Wat de Psalmen bruikbaar maakt is hun eerlijkheid. Naast de bekende lofpsalmen staan tientallen klaagpsalmen die God verwijten dat Hij zwijgt, en enkele psalmen die om onbeschaamd harde dingen vragen. Psalm 88 eindigt in het donker zonder te draaien. Die breedte is het punt: er is geen stemming waarin je niet bij God terechtkunt.",
      "Voor bijbelstudie helpt het om psalmen op soort te lezen: lofpsalmen, klaagpsalmen (individueel en gemeenschappelijk), dankpsalmen, koningspsalmen, wijsheidspsalmen, bedevaartsliederen (120-134) en boetpsalmen. Wie de vorm herkent, ziet meteen wat de dichter aan het doen is.",
    ],
    outline: [
      { range: "1-41", title: "Boek I", summary: "Overwegend van David; opent met de twee wegen (Ps 1) en de gezalfde koning (Ps 2)." },
      { range: "42-72", title: "Boek II", summary: "Korach en David; eindigt met een gebed voor de koning." },
      { range: "73-89", title: "Boek III", summary: "Asaf en Korach; donkere psalmen rond de val van Jeruzalem." },
      { range: "90-106", title: "Boek IV", summary: "Begint bij Mozes; de HEERE is Koning, ook zonder aardse troon." },
      { range: "107-150", title: "Boek V", summary: "Bedevaartsliederen, Psalm 119, en vijf slotpsalmen van pure lof." },
    ],
    keyVerses: ["Psalm 1:1-2", "Psalm 23:1", "Psalm 51:12", "Psalm 119:105", "Psalm 150:6"],
    studyQuestions: [
      "Kies een klaagpsalm en markeer waar de toon omslaat. Wat gebeurt er op dat punt?",
      "Lees Psalm 1 en 2 samen. Waarom staan juist deze twee vooraan?",
      "Psalm 119 is een acrostichon over de wet. Welke woorden gebruikt de dichter voor Gods woord, en verschillen ze?",
    ],
  },
  {
    slug: "spreuken",
    name: "Spreuken",
    position: 20,
    testament: "oude-testament",
    genre: "Poëzie en wijsheid",
    chapters: 31,
    author: "Voornamelijk Salomo; daarnaast Agur, Lemuël en 'de wijzen'.",
    written: "Verzameld over eeuwen; eindredactie waarschijnlijk in de tijd van Hizkia of later.",
    theme: "De vreze des HEEREN is het beginsel der wijsheid - en wijsheid is praktisch.",
    blurb:
      "Spreuken: wijsheid voor het dagelijks leven, over geld, tong, vriendschap en werk. Hoofdlijn, kernverzen en studievragen.",
    summary: [
      "Spreuken leert hoe je leeft, niet wat je gelooft. Het gaat over geld lenen, roddel, luiheid, drank, opvoeding, borgstelling, eerlijke weegschalen en de vraag met wie je omgaat. Wijsheid is hier geen abstractie maar vakmanschap in het gewone bestaan.",
      "De eerste negen hoofdstukken vormen een samenhangend betoog van een vader aan zijn zoon, met de Wijsheid als vrouw die op straat roept en de Dwaasheid als haar tegenbeeld. Vanaf hoofdstuk 10 volgen de losse spreuken: honderden tweeregelige uitspraken die je niet in één ruk moet lezen maar per stuk moet wegen.",
      "Belangrijk bij het bestuderen: spreuken zijn vuistregels, geen beloften. 'Leer den jongen de eerste beginselen naar den eis zijns wegs' beschrijft hoe het meestal gaat, niet hoe het altijd gaat. Job en Prediker staan in dezelfde Bijbel juist om die randen te bewaken.",
    ],
    outline: [
      { range: "1-9", title: "De lofzang op de wijsheid", summary: "Vaderlijke vermaningen en de twee vrouwen: Wijsheid en Dwaasheid." },
      { range: "10-22", title: "Spreuken van Salomo", summary: "Losse tweeregelige spreuken over vrijwel elk terrein van het leven." },
      { range: "22-24", title: "Woorden der wijzen", summary: "Dertig uitspraken, verwant aan Egyptische wijsheidsliteratuur." },
      { range: "25-29", title: "Verzameld door Hizkia's mannen", summary: "Nog een reeks spreuken van Salomo." },
      { range: "30-31", title: "Agur en Lemuël", summary: "Getalspreuken en het slotgedicht over de deugdelijke huisvrouw." },
    ],
    keyVerses: ["Spreuken 1:7", "Spreuken 3:5-6", "Spreuken 15:1", "Spreuken 31:30"],
    studyQuestions: [
      "Wat betekent 'de vreze des HEEREN' hier praktisch, gezien de spreuken die erop volgen?",
      "Zoek alle spreuken over de tong of het spreken en zet ze naast elkaar. Welk beeld ontstaat?",
      "Waar botst Spreuken met Prediker, en hoe ga je daarmee om?",
    ],
  },
  {
    slug: "prediker",
    name: "Prediker",
    position: 21,
    testament: "oude-testament",
    genre: "Poëzie en wijsheid",
    chapters: 12,
    author: "'De Prediker, de zoon van David'; de traditie leest dat als Salomo.",
    written: "Onzeker; het Hebreeuws wijst voor veel uitleggers op een late datering.",
    theme: "Alles is vluchtig - en juist daarom is het gewone leven een gave.",
    blurb:
      "Prediker: ijdelheid der ijdelheden, de tijd voor alles, en de conclusie onder de zon. Hoofdlijn en studievragen.",
    summary: [
      "Prediker is het eerlijkste boek van het Oude Testament over zinloosheid. Het Hebreeuwse woord hevel, in de Statenvertaling 'ijdelheid', betekent letterlijk damp of adem: iets wat je ziet en niet kunt vastpakken. Dat woord staat bijna veertig keer in twaalf hoofdstukken.",
      "De Prediker probeert het één voor één: wijsheid, plezier, werk, rijkdom, roem. Alles loopt stuk op dezelfde twee muren - je gaat dood, en je hebt geen controle over wat er daarna met je werk gebeurt. Hij weigert dat weg te praten, en hij weigert ook cynisch te worden.",
      "Zijn conclusie is niet somber maar nuchter: eet je brood, drink je wijn, geniet van je werk en van de vrouw die je liefhebt, want dat is je deel. En vrees God. Het boek eindigt met een oproep die pas gewicht heeft omdat alles ervoor zo grondig is doorgeprikt.",
    ],
    outline: [
      { range: "1-2", title: "Het grote experiment", summary: "Wijsheid, genot, bouwen en bezit - en alles blijkt damp." },
      { range: "3-6", title: "Tijd en onrecht", summary: "Het gedicht over de tijd, en de vraag naar recht, eenzaamheid en rijkdom." },
      { range: "7-10", title: "Wijsheid onder de zon", summary: "Wat wijsheid wel en niet kan, en de grenzen van het weten." },
      { range: "11-12", title: "Slotsom", summary: "Zaai je zaad, gedenk je Schepper in je jeugd, en vrees God." },
    ],
    keyVerses: ["Prediker 1:2", "Prediker 3:1", "Prediker 3:11", "Prediker 12:13"],
    studyQuestions: [
      "Wat betekent 'ijdelheid' als je het leest als 'damp' in plaats van 'zinloosheid'?",
      "De Prediker zegt zeven keer dat je moet eten, drinken en genieten. Waar staan die plaatsen, en wat is de functie ervan?",
      "Hoe verhoudt 12:13-14 zich tot de rest van het boek - is het een correctie of een conclusie?",
    ],
  },
  {
    slug: "hooglied",
    name: "Hooglied",
    position: 22,
    testament: "oude-testament",
    genre: "Poëzie en wijsheid",
    chapters: 8,
    author: "Toegeschreven aan Salomo.",
    written: "Onzeker.",
    theme: "Liefde tussen man en vrouw, bezongen zonder terughoudendheid.",
    blurb:
      "Hooglied: liefdespoëzie tussen bruid en bruidegom, en de twee manieren waarop het door de eeuwen is gelezen. Hoofdlijn en studievragen.",
    summary: [
      "Hooglied is een bundel liefdesliederen tussen een vrouw en een man, met een koor van 'dochters van Jeruzalem' erbij. Er wordt niet over God gesproken, niet over de tempel, niet over de wet. Er wordt gesproken over verlangen, lichamen, tuinen, geuren en gemis.",
      "Door de eeuwen is het op twee manieren gelezen. De allegorische lezing ziet er de liefde van God voor Israël of van Christus voor de gemeente in; die uitleg domineerde eeuwenlang en zit in veel oude commentaren. De letterlijke lezing neemt het als wat het is: een lofzang op de huwelijksliefde, die door in de canon te staan zegt dat lichamelijke liefde niet buiten het geloofsleven valt.",
      "Beide lezingen kunnen elkaar aanvullen. Wie het bestudeert doet er goed aan eerst goed te lezen wat er staat, en pas daarna te vragen wat het beeld verder kan dragen.",
    ],
    outline: [
      { range: "1-2", title: "Verlangen", summary: "De bruid spreekt, de bruidegom antwoordt, en de liefde wordt bezongen." },
      { range: "3-5", title: "Zoeken en vinden", summary: "Een droom, de bruiloftsstoet, en de beschrijving van de geliefde." },
      { range: "6-7", title: "Terugvinden", summary: "Hernieuwde ontmoeting en wederzijdse lof." },
      { range: "8", title: "De kracht van liefde", summary: "Liefde sterk als de dood, en niet te koop." },
    ],
    keyVerses: ["Hooglied 2:4", "Hooglied 4:7", "Hooglied 8:6-7"],
    studyQuestions: [
      "Wie spreekt er in elk gedeelte? Markeer de wisselingen tussen bruid, bruidegom en koor.",
      "Wat zegt 8:6-7 over wat liefde is - en waarmee wordt zij vergeleken?",
      "Welke uitleg overtuigt jou, en welke argumenten zijn er voor de andere?",
    ],
  },
  {
    slug: "jesaja",
    name: "Jesaja",
    position: 23,
    testament: "oude-testament",
    genre: "Grote profeten",
    chapters: 66,
    author: "Jesaja, zoon van Amoz; over de eenheid van het boek bestaat wetenschappelijk debat.",
    written: "8e eeuw v.Chr. en later; eindvorm na de ballingschap.",
    theme: "De Heilige Israëls oordeelt en redt - en het redden krijgt het laatste woord.",
    blurb:
      "Jesaja: oordeel over Juda, de troonvisioen, Immanuël, de Knecht des HEEREN en de nieuwe hemel. Hoofdlijn en studievragen.",
    summary: [
      "Jesaja is het langste profetenboek en het meest geciteerde in het Nieuwe Testament. Het opent met een aanklacht: het volk brengt offers, viert feesten, en onderdrukt ondertussen de wees en de weduwe. Godsdienst zonder recht is voor Jesaja geen halve godsdienst maar een belediging.",
      "Het boek valt grofweg in twee delen. De hoofdstukken 1-39 spelen in de achtste eeuw, met de Assyrische dreiging op de achtergrond, en bevatten het roepingsvisioen in hoofdstuk 6, de Immanuël-profetie en het optreden bij koning Hizkia. Vanaf hoofdstuk 40 verandert de toon volledig: 'Troost, troost Mijn volk'. Er wordt gesproken tot ballingen in Babel over terugkeer, en Kores wordt bij name genoemd.",
      "Het hart van dat tweede deel zijn de vier liederen over de Knecht des HEEREN, uitlopend op Jesaja 53 - de tekst die de kerk van het begin af aan op Jezus heeft betrokken. Het boek eindigt met een nieuwe hemel en een nieuwe aarde.",
    ],
    outline: [
      { range: "1-12", title: "Oordeel over Juda", summary: "Aanklacht, het roepingsvisioen, Immanuël en de twijg uit Isaï." },
      { range: "13-27", title: "Over de volken", summary: "Godsspraken over Babel, Moab, Egypte en Tyrus, en de grote apocalyps." },
      { range: "28-39", title: "Wee en vertrouwen", summary: "Waarschuwing tegen bondgenootschappen en de belegering onder Hizkia." },
      { range: "40-55", title: "Troost", summary: "Terugkeer uit Babel, de nietigheid van afgoden en de vier Knechtsliederen." },
      { range: "56-66", title: "Herstel", summary: "Recht, echt vasten, en een nieuwe hemel en aarde." },
    ],
    keyVerses: ["Jesaja 6:8", "Jesaja 9:5", "Jesaja 40:31", "Jesaja 53:5", "Jesaja 55:8-9"],
    studyQuestions: [
      "Wat ziet Jesaja in hoofdstuk 6, en wat is zijn eerste reactie voordat hij 'zend mij' zegt?",
      "Zoek de vier Knechtsliederen op (42, 49, 50, 52-53). Wat verandert er van lied tot lied?",
      "Hoe beschrijft Jesaja 58 het vasten dat God wél wil?",
    ],
  },
  {
    slug: "jeremia",
    name: "Jeremia",
    position: 24,
    testament: "oude-testament",
    genre: "Grote profeten",
    chapters: 52,
    author: "Jeremia, met zijn schrijver Baruch.",
    written: "Late 7e en vroege 6e eeuw v.Chr.",
    theme: "Veertig jaar preken tegen een volk dat niet luistert - en de belofte van een nieuw verbond.",
    blurb:
      "Jeremia: roeping van jongs af, de tempelrede, de pottenbakker, en het nieuwe verbond. Hoofdlijn en studievragen.",
    summary: [
      "Jeremia profeteert in de laatste veertig jaar van Juda, van koning Josia tot na de val van Jeruzalem. Hij wordt geroepen als jonge man, protesteert dat hij niet spreken kan, en krijgt een boodschap die hem eenzaam en gehaat zal maken.",
      "Zijn kernpunt is dat het onafwendbaar is geworden: Babel komt, en verzet is zinloos. Dat maakt hem in de ogen van het hof een landverrader. Hij wordt in het blok gezet, in een put met modder gegooid, en zijn boekrol wordt door de koning stukje bij beetje in het vuur gesneden. Jeremia dicteert hem opnieuw.",
      "Wat het boek uitzonderlijk maakt zijn de 'confessies': gedeelten waarin Jeremia God rechtstreeks verwijt dat Hij hem overgehaald heeft. En midden in al dat donker staat de belofte van hoofdstuk 31, over een verbond dat God in het hart schrijft - het gedeelte dat de brief aan de Hebreeën in zijn geheel citeert.",
    ],
    outline: [
      { range: "1-10", title: "Roeping en aanklacht", summary: "De amandeltak en de kokende pot, en de tempelrede." },
      { range: "11-20", title: "De confessies", summary: "Jeremia's klachten, de linnen gordel en de pottenbakker." },
      { range: "21-33", title: "Koningen en herstel", summary: "Oordeel over de koningen, de zeventig jaar, en het nieuwe verbond." },
      { range: "34-45", title: "Belegering en val", summary: "De boekrol in het vuur, de put, en de vlucht naar Egypte." },
      { range: "46-52", title: "Over de volken", summary: "Godsspraken tegen Egypte tot Babel, en de val van Jeruzalem." },
    ],
    keyVerses: ["Jeremia 1:5", "Jeremia 17:9", "Jeremia 29:11", "Jeremia 31:33"],
    studyQuestions: [
      "Lees Jeremia 29:1-14 als geheel. Aan wie is vers 11 geschreven, en wat verandert dat aan de toepassing?",
      "Wat is er nieuw aan het nieuwe verbond in 31:31-34?",
      "Hoe praat Jeremia in zijn confessies tegen God? Wat zegt het dat die gebeden in de Bijbel staan?",
    ],
  },
  {
    slug: "klaagliederen",
    name: "Klaagliederen",
    position: 25,
    testament: "oude-testament",
    genre: "Grote profeten",
    chapters: 5,
    author: "Anoniem; traditioneel toegeschreven aan Jeremia.",
    written: "Kort na de val van Jeruzalem in 586 v.Chr.",
    theme: "Rouw om een verwoeste stad, met één lichtpunt in het midden.",
    blurb:
      "Klaagliederen: vijf gedichten over de verwoesting van Jeruzalem, met 'Zijn barmhartigheden zijn elken morgen nieuw' in het hart. Hoofdlijn en studievragen.",
    summary: [
      "Klaagliederen bestaat uit vijf gedichten over de puinhopen van Jeruzalem. Vier ervan zijn acrostichons: elk couplet begint met de volgende letter van het Hebreeuwse alfabet. Die strakke vorm om zulke ontredderde inhoud is opzettelijk - het is rouw die zich laat beteugelen om niet te verstommen.",
      "Het boek verdoezelt niets. Er is honger tot kannibalisme toe, priesters die omkomen in het heiligdom, kinderen die op straat bezwijken. De dichter zegt bovendien onomwonden dat dit oordeel verdiend is; er wordt geen zondebok aangewezen.",
      "En dan, precies in het midden van het middelste gedicht, staan de verzen 3:22-23: 'Het zijn de goedertierenheden des HEEREN, dat wij niet vernield zijn... zij zijn allen morgen nieuw'. Niet als afsluiting, want daarna gaat de klacht door, en het boek eindigt met een vraag die openblijft. Dat maakt het een onvervangbaar boek voor wie zelf in de puinhopen zit.",
    ],
    outline: [
      { range: "1", title: "De verlaten stad", summary: "Jeruzalem als weduwe, alleen tussen de volken." },
      { range: "2", title: "De dag van Gods toorn", summary: "Wat er met tempel, muren en leiders gebeurd is." },
      { range: "3", title: "Ik ben de man", summary: "Persoonlijke klacht, en midden erin de trouw die elke morgen nieuw is." },
      { range: "4", title: "Toen en nu", summary: "Het contrast tussen de vroegere glans en de honger van nu." },
      { range: "5", title: "Gebed", summary: "Een slotgebed dat eindigt in een openstaande vraag." },
    ],
    keyVerses: ["Klaagliederen 1:12", "Klaagliederen 3:22-23", "Klaagliederen 3:32", "Klaagliederen 5:21"],
    studyQuestions: [
      "Waarom staat 3:22-23 in het midden en niet aan het slot?",
      "Wat doet de alfabetische vorm met de manier waarop je het leest?",
      "Het boek eindigt zonder oplossing. Wat betekent het dat de Bijbel dat toestaat?",
    ],
  },
  {
    slug: "ezechiel",
    name: "Ezechiël",
    position: 26,
    testament: "oude-testament",
    genre: "Grote profeten",
    chapters: 48,
    author: "Ezechiël, priester en profeet in ballingschap.",
    written: "Eerste helft van de 6e eeuw v.Chr.",
    theme: "De heerlijkheid van God verlaat de tempel en komt terug.",
    blurb:
      "Ezechiël: de troonwagen, tekenhandelingen, het dal van dorre beenderen en de nieuwe tempel. Hoofdlijn en studievragen.",
    summary: [
      "Ezechiël is priester, maar hij zit in Babel en er is geen tempel om in te dienen. Zijn boek begint met een van de vreemdste visioenen in de Bijbel: een troonwagen met wielen vol ogen en vier levende wezens. De pointe is dat God niet aan Jeruzalem vastzit - Hij is ook hier, bij de ballingen aan de rivier Kebar.",
      "Ezechiël krijgt opdrachten die je bij niemand anders vindt. Hij ligt maandenlang op één zij, bakt brood op een afgemeten rantsoen, scheert zijn haar af en verdeelt het in drieën, en mag na de dood van zijn vrouw niet rouwen. Zijn lichaam wordt de preek.",
      "Het scharnier is de val van Jeruzalem halverwege het boek. Daarvoor is de boodschap oordeel, daarna herstel: het dal van dorre beenderen dat weer gaat leven, een hart van vlees in plaats van steen, en negen slothoofdstukken over een nieuwe tempel waaruit een rivier stroomt. De laatste woorden zijn de nieuwe naam van de stad: 'de HEERE is aldaar'.",
    ],
    outline: [
      { range: "1-3", title: "Roeping", summary: "De troonwagen, de boekrol die hij moet eten, en de wachterstaak." },
      { range: "4-24", title: "Oordeel over Jeruzalem", summary: "Tekenhandelingen, het vertrek van Gods heerlijkheid en de aanklacht." },
      { range: "25-32", title: "Over de volken", summary: "Godsspraken tegen Ammon, Moab, Tyrus en Egypte." },
      { range: "33-39", title: "Herstel", summary: "De ware herder, het nieuwe hart, de dorre beenderen en Gog." },
      { range: "40-48", title: "De nieuwe tempel", summary: "Het visioen van tempel, rivier en verdeeld land." },
    ],
    keyVerses: ["Ezechiël 1:28", "Ezechiël 18:32", "Ezechiël 36:26", "Ezechiël 37:5"],
    studyQuestions: [
      "Volg de heerlijkheid van God door het boek: waar komt zij, waar gaat zij weg, en waar keert zij terug?",
      "Wat is de kern van hoofdstuk 18 over persoonlijke verantwoordelijkheid?",
      "Wat betekent het dorre-beenderenvisioen voor de eerste hoorders in ballingschap?",
    ],
  },
  {
    slug: "daniel",
    name: "Daniël",
    position: 27,
    testament: "oude-testament",
    genre: "Apocalyptiek",
    chapters: 12,
    author: "Anoniem; de verhalen spelen rond Daniël aan het Babylonische en Perzische hof.",
    written: "Datering omstreden: 6e eeuw v.Chr. volgens de traditionele lezing, 2e eeuw v.Chr. volgens veel moderne uitleggers.",
    theme: "God regeert over rijken die zichzelf eeuwig wanen.",
    blurb:
      "Daniël: de vurige oven, het schrift aan de wand, de leeuwenkuil en de visioenen over vier rijken. Hoofdlijn en studievragen.",
    summary: [
      "Daniël valt in twee helften uiteen die heel verschillend lezen. De hoofdstukken 1-6 zijn verhalen: vier Joodse jongens aan het hof van Nebukadnezar, het standbeeld en de vurige oven, de droom die niemand kan uitleggen, het schrift aan de wand, en de leeuwenkuil. Ze gaan allemaal over dezelfde vraag - hoe blijf je trouw als je in dienst staat van een rijk dat je God niet erkent?",
      "De hoofdstukken 7-12 zijn visioenen, en ze zijn taaier. Vier dieren uit de zee, een ram en een bok, de zeventig weken, en een lange strijd tussen koningen van het noorden en het zuiden. De beeldtaal is die van de apocalyptiek: hevig, symbolisch en gericht op lezers onder druk.",
      "Door beide helften loopt dezelfde overtuiging. Rijken komen op en gaan onder, en Iemand als eens mensen zoon ontvangt een heerschappij die niet vergaat. Daniël is daarmee de belangrijkste oudtestamentische achtergrond bij het Nieuwe Testament wanneer Jezus zichzelf 'de Zoon des mensen' noemt.",
    ],
    outline: [
      { range: "1-6", title: "Verhalen aan het hof", summary: "Het dieet, de droom van het standbeeld, de oven, de waanzin van Nebukadnezar, het schrift aan de wand en de leeuwenkuil." },
      { range: "7", title: "De vier dieren", summary: "Vier rijken en de Zoon des mensen die het koningschap ontvangt." },
      { range: "8-9", title: "Ram, bok en zeventig weken", summary: "Visioen over Perzië en Griekenland, en Daniëls gebed." },
      { range: "10-12", title: "Het laatste visioen", summary: "Koningen van noord en zuid, verdrukking, en de opstanding." },
    ],
    keyVerses: ["Daniël 2:21", "Daniël 3:17-18", "Daniël 6:11", "Daniël 7:13-14"],
    studyQuestions: [
      "Waar trekken Daniël en zijn vrienden wél en niet de grens in hun dienst aan Babel?",
      "Wat zeggen de drie mannen in 3:17-18, en waarom is dat 'maar zo niet' zo belangrijk?",
      "Hoe gebruikt Jezus in de evangeliën de titel 'Zoon des mensen' uit Daniël 7?",
    ],
  },
  {
    slug: "hosea",
    name: "Hosea",
    position: 28,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 14,
    author: "Hosea, zoon van Beëri.",
    written: "8e eeuw v.Chr., in het noordrijk vlak voor de val van Samaria.",
    theme: "Een profeet moet trouwen met een ontrouwe vrouw om Gods pijn te laten zien.",
    blurb:
      "Hosea: het huwelijk als profetie, de namen van de kinderen, en Gods weigering om los te laten. Hoofdlijn en studievragen.",
    summary: [
      "Hosea krijgt de zwaarste opdracht van alle profeten: trouw met Gomer, een vrouw van wie vaststaat dat ze hem ontrouw zal zijn, en noem je kinderen naar het oordeel - Jizreël, Lo-Ruchama ('geen ontferming') en Lo-Ammi ('niet mijn volk'). Zijn gezin wordt de preek.",
      "De boodschap raakt het noordrijk in zijn laatste decennia. Israël is materieel welvarend en religieus door en door vermengd met de Baälsdienst. Hosea noemt dat wat het volgens hem is: overspel. Niet een regeltje overtreden maar een relatie verraden.",
      "Wat het boek onvergetelijk maakt is hoofdstuk 11, waar God hardop worstelt: 'Hoe zou Ik u overgeven, Efraïm? ... Mijn hart is in Mij omgekeerd'. Het oordeel wordt niet ingetrokken, maar de liefde eronder blijkt sterker dan de woede. Het boek eindigt met een uitnodiging: 'Bekeer u, o Israël, tot den HEERE, uw God'.",
    ],
    outline: [
      { range: "1-3", title: "Het huwelijk", summary: "Gomer, de drie kinderen, en de terugkoop van de ontrouwe vrouw." },
      { range: "4-10", title: "De aanklacht", summary: "Geen kennis van God, priesters die falen, en politiek gemanoeuvreer." },
      { range: "11-14", title: "Liefde die niet loslaat", summary: "Efraïm als kind, Gods omkering, en de oproep tot terugkeer." },
    ],
    keyVerses: ["Hosea 2:18", "Hosea 4:6", "Hosea 6:6", "Hosea 11:8"],
    studyQuestions: [
      "Wat betekenen de namen van Hosea's kinderen, en wat gebeurt er later met die namen?",
      "Wat bedoelt 6:6 met 'Ik heb lust tot weldadigheid, en niet tot offer'? Waar citeert Jezus dit?",
      "Hoe verandert de toon tussen hoofdstuk 4 en hoofdstuk 11?",
    ],
  },
  {
    slug: "joel",
    name: "Joël",
    position: 29,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 3,
    author: "Joël, zoon van Pethuël.",
    written: "Onzeker; voorstellen lopen van de 9e tot de 4e eeuw v.Chr.",
    theme: "Een sprinkhanenplaag als voorbode van de dag des HEEREN - en de uitstorting van de Geest.",
    blurb:
      "Joël: sprinkhanen, de dag des HEEREN, en de belofte van de Geest die Petrus op Pinksteren citeert. Hoofdlijn en studievragen.",
    summary: [
      "Joël begint met een ramp die iedereen kan zien: een sprinkhanenplaag heeft het land kaalgevreten. Vier soorten sprinkhanen worden genoemd, laag na laag, tot er niets meer over is. De priesters kunnen geen spijsoffer meer brengen omdat er geen graan is.",
      "De profeet gebruikt die ramp als venster. Wat je nu ziet, zegt hij, is een voorproefje van de dag des HEEREN - een dag die niet vanzelf gunstig is, ook niet voor Israël. Zijn oproep is een nationale vastendag: 'scheurt uw hart en niet uw klederen'.",
      "Het derde deel bevat de belofte die Petrus op de Pinksterdag aanhaalt: God zal Zijn Geest uitstorten op alle vlees, en zonen en dochters, oude en jonge mensen, dienstknechten en dienstmaagden zullen profeteren. Voor het Nieuwe Testament is dit hoofdstuk het antwoord op de vraag wat er in Handelingen 2 gebeurt.",
    ],
    outline: [
      { range: "1", title: "De plaag", summary: "Sprinkhanen, misoogst en een oproep tot rouw." },
      { range: "2", title: "De dag des HEEREN", summary: "Het leger uit het noorden, en de oproep het hart te scheuren." },
      { range: "3", title: "Geest en oordeel", summary: "De uitstorting van de Geest en het oordeel in het dal van Josafat." },
    ],
    keyVerses: ["Joël 2:13", "Joël 2:25", "Joël 2:28-29"],
    studyQuestions: [
      "Wat bedoelt Joël met 'scheurt uw hart en niet uw klederen'?",
      "Lees Handelingen 2:16-21 naast Joël 2:28-32. Wat neemt Petrus over, en wat laat hij staan?",
      "Wat betekent de belofte dat God de jaren vergoedt die de sprinkhaan heeft afgegeten?",
    ],
  },
  {
    slug: "amos",
    name: "Amos",
    position: 30,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 9,
    author: "Amos, veehouder en moerbeikweker uit Thekoa.",
    written: "Midden 8e eeuw v.Chr.",
    theme: "Er kan geen eredienst zijn waar recht ontbreekt.",
    blurb:
      "Amos: een boer die naar het noorden trekt om welvarend Israël aan te klagen over onrecht. Hoofdlijn en studievragen.",
    summary: [
      "Amos is geen beroepsprofeet. Hij is veehouder in Juda en wordt weggehaald achter zijn kudde om in het welvarende noordrijk te spreken. Dat maakt hem daar meteen een buitenstaander, en de priester van Bethel stuurt hem prompt terug.",
      "Zijn opening is retorisch briljant. Hij begint met oordeelsspraken over de buurvolken - Damascus, Gaza, Tyrus, Edom, Ammon, Moab - waar zijn gehoor het hartgrondig mee eens zal zijn geweest. Dan Juda. En dan, als iedereen knikt, Israël zelf, met de langste aanklacht van allemaal.",
      "Wat hij aanklaagt is niet afgoderij maar onrecht: de armen worden voor een paar schoenen verkocht, de weegschalen zijn vervalst, en ondertussen draaien de feesten op volle toeren. Zijn beroemdste vers is de weigering van die eredienst: 'laat het oordeel zich daarhenen wenden als de wateren, en de gerechtigheid als een sterke beek'.",
    ],
    outline: [
      { range: "1-2", title: "Oordeel over de volken", summary: "Zeven buurvolken, en dan Juda en Israël." },
      { range: "3-6", title: "Drie aanklachten", summary: "Tegen luxe, onrecht en valse zekerheid; de koeien van Basan en de dag des HEEREN." },
      { range: "7-9", title: "Vijf visioenen", summary: "Sprinkhanen, vuur, het paslood, de zomervruchten, en de belofte van herstel." },
    ],
    keyVerses: ["Amos 3:7", "Amos 5:14", "Amos 5:24", "Amos 8:11"],
    studyQuestions: [
      "Hoe is de opbouw van hoofdstuk 1-2 opgezet, en wat doet die opbouw met de hoorder?",
      "Wat wijst Amos precies af in 5:21-24 - de eredienst zelf of iets anders?",
      "Wat is volgens 8:11 de ergste honger die kan komen?",
    ],
  },
  {
    slug: "obadja",
    name: "Obadja",
    position: 31,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 1,
    author: "Obadja; verder onbekend.",
    written: "Waarschijnlijk kort na de val van Jeruzalem in 586 v.Chr.",
    theme: "Wie toekijkt bij het onrecht van een ander, is niet onschuldig.",
    blurb:
      "Obadja: het kortste boek van het Oude Testament, een godsspraak tegen Edom dat toekeek bij de val van Jeruzalem. Hoofdlijn en studievragen.",
    summary: [
      "Obadja telt eenentwintig verzen en is daarmee het kortste boek van het Oude Testament. Het richt zich volledig tegen Edom, het buurvolk dat volgens de overlevering afstamt van Ezau - de broer van Jakob.",
      "De aanklacht is die van medeplichtigheid door toekijken. Toen Jeruzalem viel, stond Edom erbij. Erger: het verheugde zich, sneed vluchtelingen de pas af en plunderde mee. Obadja noemt dat 'geweld tegen uw broeder Jakob'.",
      "Het antwoord is dat Edoms rotsvestingen hem niet zullen redden: 'al verhieft gij u gelijk de arend, en al steldet gij uw nest tussen de sterren, zo zal Ik u van daar nederstoten'. Het boekje eindigt met de omkering - het koninkrijk zal des HEEREN zijn.",
    ],
    outline: [
      { range: "1", title: "Tegen Edom", summary: "Hoogmoed en val, de schuld van het toekijken, en de dag des HEEREN over alle volken." },
    ],
    keyVerses: ["Obadja 1:3", "Obadja 1:12", "Obadja 1:15"],
    studyQuestions: [
      "Wat verwijt Obadja Edom precies? Maak een lijst van de werkwoorden in vers 11-14.",
      "Waarom weegt de broederrelatie tussen Edom en Israël zo zwaar in de aanklacht?",
      "Wat betekent 'gelijk gij gedaan hebt, zal u gedaan worden' in dit verband?",
    ],
  },
  {
    slug: "jona",
    name: "Jona",
    position: 32,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 4,
    author: "Anoniem; het boek gaat over Jona, zoon van Amitthai.",
    written: "Onzeker; vaak na de ballingschap gedateerd.",
    theme: "Een profeet die vlucht omdat hij bang is dat God genadig zal zijn.",
    blurb:
      "Jona: vluchten naar Tarsis, de grote vis, de bekering van Ninevé en de wonderboom. Hoofdlijn en studievragen.",
    summary: [
      "Jona is het enige profetenboek dat vrijwel geheel verhaal is en waarin de profeet zelf het probleem is. Hij krijgt opdracht naar Ninevé te gaan, de hoofdstad van Assyrië, en gaat de andere kant op.",
      "Wat volgt is een reeks omkeringen. De heidense zeelieden bidden terwijl de profeet slaapt. De vis spuwt hem uit. Ninevé bekeert zich na één zin preek - de kortste en meest succesvolle preek in de Bijbel - tot en met het vee toe.",
      "En dan komt de clou. Jona is woedend, en zegt eindelijk waarom hij vluchtte: 'ik wist, dat Gij een genadig en barmhartig God zijt'. Hij was niet bang dat het oordeel zou komen, maar dat het niet zou komen. Het boek eindigt met een vraag van God over de wonderboom en de honderdtwintigduizend mensen in Ninevé - en Jona's antwoord staat er niet.",
    ],
    outline: [
      { range: "1", title: "De vlucht", summary: "De opdracht, het schip naar Tarsis, de storm en de zeelieden." },
      { range: "2", title: "Het gebed", summary: "Jona's psalm uit de buik van de vis." },
      { range: "3", title: "Ninevé", summary: "De preek van één zin en de bekering van de hele stad." },
      { range: "4", title: "De boze profeet", summary: "Jona's woede, de wonderboom, en Gods slotvraag." },
    ],
    keyVerses: ["Jona 1:3", "Jona 2:10", "Jona 3:10", "Jona 4:2"],
    studyQuestions: [
      "Waarom vlucht Jona? Het antwoord staat pas in 4:2 - wat doet dat met je lezing van hoofdstuk 1?",
      "Vergelijk het gedrag van de heidenen (zeelieden, Ninevieten) met dat van de profeet.",
      "Het boek eindigt met een onbeantwoorde vraag. Aan wie is die vraag eigenlijk gesteld?",
    ],
  },
  {
    slug: "micha",
    name: "Micha",
    position: 33,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 7,
    author: "Micha van Moresheth.",
    written: "Late 8e eeuw v.Chr., tijdgenoot van Jesaja.",
    theme: "Wat eist de HEERE van u? Recht doen, weldadigheid liefhebben, ootmoedig wandelen.",
    blurb:
      "Micha: aanklacht tegen leiders die het volk uitbuiten, Bethlehem, en de bekendste samenvatting van wat God vraagt. Hoofdlijn en studievragen.",
    summary: [
      "Micha komt uit een dorp in het heuvelland van Juda en spreekt met de scherpte van iemand die ziet wat het beleid van de stad op het platteland aanricht. Hij klaagt grootgrondbezitters aan die 's nachts akkers begeren en ze 's ochtends inpikken, rechters die zich laten omkopen en profeten die spreken naar wie er betaalt.",
      "Het boek wisselt tussen oordeel en belofte. Hij voorzegt dat Jeruzalem tot een puinhoop wordt - een uitspraak die honderd jaar later in Jeremia's proces nog wordt aangehaald - en kondigt in hetzelfde boek aan dat uit Bethlehem-Efratha een heerser zal voortkomen, de tekst die de schriftgeleerden in Mattheüs 2 citeren.",
      "Het slot bevat de bekendste samenvatting van het Oude Testament: God vraagt geen duizenden rammen, maar recht doen, weldadigheid liefhebben en ootmoedig wandelen met je God.",
    ],
    outline: [
      { range: "1-3", title: "Aanklacht", summary: "Oordeel over Samaria en Jeruzalem, en over leiders, priesters en profeten." },
      { range: "4-5", title: "Belofte", summary: "De berg van het huis des HEEREN, zwaarden tot spaden, en Bethlehem." },
      { range: "6-7", title: "Rechtszaak en hoop", summary: "Gods pleidooi, de drie eisen, en het slotvertrouwen." },
    ],
    keyVerses: ["Micha 4:3", "Micha 5:1", "Micha 6:8", "Micha 7:18"],
    studyQuestions: [
      "Wat betekenen de drie eisen in 6:8 concreet, gezien de aanklachten in hoofdstuk 2 en 3?",
      "Hoe wordt Micha 5:1 in Mattheüs 2 gebruikt, en wat voegt de context bij Micha toe?",
      "Micha 6 is opgezet als rechtszaak. Wie zijn de partijen en wie zijn de getuigen?",
    ],
  },
  {
    slug: "nahum",
    name: "Nahum",
    position: 34,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 3,
    author: "Nahum, de Elkosiet.",
    written: "7e eeuw v.Chr., voor de val van Ninevé in 612 v.Chr.",
    theme: "Het imperium dat op terreur draaide, valt.",
    blurb:
      "Nahum: de val van Ninevé aangekondigd, honderd jaar na Jona. Wat het boek zegt over Gods geduld en Gods grens. Hoofdlijn en studievragen.",
    summary: [
      "Nahum is Jona's tegenhanger. Waar Jona zag hoe Ninevé zich bekeerde, kondigt Nahum ruim een eeuw later de ondergang van diezelfde stad aan. Assyrië was in de tussentijd het wreedste rijk van zijn tijd geworden, met deportaties en gedocumenteerde terreur als beleidsinstrument.",
      "Het boek is korte, felle poëzie: de belegering wordt beschreven alsof je erbij staat, met rode schilden, ratelende wagens en struikelende soldaten. Ninevé wordt de stad der bloedschulden genoemd.",
      "Wie het alleen als wraakzang leest, mist het begin. Hoofdstuk 1 zegt eerst dat de HEERE 'lankmoedig' is, en pas daarna dat Hij de schuldige niet onschuldig houdt. Voor de kleine volken die onder Assyrië leden was dit boek geen bloeddorst maar het bericht dat er een grens is.",
    ],
    outline: [
      { range: "1", title: "Wie God is", summary: "Lankmoedig en groot van kracht; toevlucht voor wie op Hem vertrouwt." },
      { range: "2", title: "De belegering", summary: "De aanval op Ninevé in beeld gebracht." },
      { range: "3", title: "De stad der bloedschulden", summary: "Waarom het zo loopt, en de vergelijking met No-Amon." },
    ],
    keyVerses: ["Nahum 1:3", "Nahum 1:7", "Nahum 3:1"],
    studyQuestions: [
      "Lees Nahum naast Jona. Wat zegt het samen over Gods geduld en Gods oordeel?",
      "Wat voor troost bood dit boek aan volken die onder Assyrië leden?",
      "Hoe verhoudt 1:3 zich tot de rest van het boek?",
    ],
  },
  {
    slug: "habakuk",
    name: "Habakuk",
    position: 35,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 3,
    author: "De profeet Habakuk.",
    written: "Late 7e eeuw v.Chr., rond de opkomst van Babel.",
    theme: "Hoe kan een rechtvaardige God een erger volk gebruiken om een slecht volk te straffen?",
    blurb:
      "Habakuk: twee klachten, twee antwoorden, en een slotlied dat blijft juichen als alles misgaat. Hoofdlijn en studievragen.",
    summary: [
      "Habakuk is uniek onder de profeten omdat hij niet tot het volk spreekt maar tot God, en met een klacht. Hoe lang moet hij nog roepen over het geweld in Juda voordat er iets gebeurt?",
      "Gods antwoord maakt het erger: Hij verwekt de Chaldeeën. Habakuk kaatst terug met de vraag die het boek beroemd heeft gemaakt - hoe kan God zwijgen als de goddeloze verslindt wie rechtvaardiger is dan hij? Dan gaat hij op de wachttoren staan om te zien wat er wordt geantwoord.",
      "Het antwoord bevat de zin die Paulus twee keer en Hebreeën één keer citeert: 'de rechtvaardige zal door zijn geloof leven'. En het boek eindigt met een lied dat het geloof pijnlijk concreet maakt: al zou de vijgenboom niet bloeien en het vee uit de stal verdwijnen, 'zo zal ik nochtans in den HEERE van vreugde opspringen'.",
    ],
    outline: [
      { range: "1", title: "Twee klachten", summary: "Waarom zwijgt God over het onrecht - en waarom gebruikt Hij de Chaldeeën?" },
      { range: "2", title: "Het antwoord", summary: "Wachten op het visioen, de rechtvaardige leeft door geloof, en vijf weeroepen." },
      { range: "3", title: "Het gebed", summary: "Een psalm over Gods verschijnen, eindigend in vreugde zonder oogst." },
    ],
    keyVerses: ["Habakuk 1:13", "Habakuk 2:4", "Habakuk 2:20", "Habakuk 3:17-18"],
    studyQuestions: [
      "Hoe stelt Habakuk zijn vragen? Let op de toon - is dit ongeloof of geloof?",
      "Wat betekent 'door zijn geloof leven' in de context van Habakuk 2, en wat maakt Paulus ervan in Romeinen 1:17?",
      "Wat is er zo radicaal aan de vreugde in 3:17-18?",
    ],
  },
  {
    slug: "zefanja",
    name: "Zefanja",
    position: 36,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 3,
    author: "Zefanja, met een geslachtsregister tot Hizkia.",
    written: "7e eeuw v.Chr., tijdens de regering van Josia.",
    theme: "De dag des HEEREN komt over allen - en aan de andere kant zingt God zelf.",
    blurb:
      "Zefanja: de dag des HEEREN, de mensen die 'op hun droesem gestold' zijn, en het slotlied waarin God van vreugde zingt. Hoofdlijn en studievragen.",
    summary: [
      "Zefanja profeteert in de tijd van koning Josia, waarschijnlijk vóór diens hervorming. Hij begint zo breed als het maar kan: God zal alles wegvagen van de aardbodem. Daarna versmalt hij naar Juda en Jeruzalem.",
      "Zijn scherpste beeld geldt niet de goddelozen maar de onverschilligen: mensen 'die op hun droesem gestold zijn', die in hun hart zeggen dat de HEERE geen goed en geen kwaad doet. Religieuze onverschilligheid is voor Zefanja geen neutrale positie.",
      "Het derde hoofdstuk keert alles om. Wat overblijft is een 'ellendig en arm volk' dat op de naam van de HEERE vertrouwt. En dan volgt een van de opvallendste verzen van het Oude Testament: God zal over hen vrolijk zijn met blijdschap en zingen. Niet het volk zingt over God - God zingt over het volk.",
    ],
    outline: [
      { range: "1", title: "De dag des HEEREN", summary: "Oordeel over Juda, over Jeruzalem en over de onverschilligen." },
      { range: "2", title: "Over de volken", summary: "Filistea, Moab, Kusch en Assyrië, met een oproep God te zoeken." },
      { range: "3", title: "Oordeel en lied", summary: "De weerspannige stad, het overblijfsel, en Gods vreugdelied." },
    ],
    keyVerses: ["Zefanja 1:12", "Zefanja 2:3", "Zefanja 3:17"],
    studyQuestions: [
      "Wat is 'op zijn droesem gestold' voor houding, en hoe herken je die vandaag?",
      "Wie is het overblijfsel dat Zefanja beschrijft, en waaraan is het te herkennen?",
      "Wat verandert er aan je Godsbeeld door 3:17?",
    ],
  },
  {
    slug: "haggai",
    name: "Haggaï",
    position: 37,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 2,
    author: "De profeet Haggaï.",
    written: "520 v.Chr., precies gedateerd in het boek zelf.",
    theme: "De tempel ligt in puin terwijl iedereen zijn eigen huis afwerkt.",
    blurb:
      "Haggaï: vier gedateerde godsspraken die de herbouw van de tempel weer op gang brengen. Hoofdlijn en studievragen.",
    summary: [
      "Haggaï is het meest precies gedateerde boek van de Bijbel: vier godsspraken, elk met dag en maand, verspreid over vier maanden in het jaar 520 v.Chr. Het tempelwerk ligt dan al zestien jaar stil.",
      "Zijn diagnose is kort. Het volk zegt dat de tijd nog niet gekomen is, terwijl het ondertussen zijn eigen huizen van gewelfd hout voorziet. Haggaï wijst op de misoogsten en de lege beurzen: 'gij zaait veel, en gij brengt weinig in'. Wie zijn prioriteiten omkeert, houdt niets over.",
      "Wat opvalt is de reactie. Anders dan bij vrijwel elke andere profeet luistert het volk werkelijk: drieëntwintig dagen na de eerste godsspraak wordt het werk hervat. De tweede godsspraak troost de ouderen die de eerste tempel nog kenden en dit een schamel geheel vinden - de heerlijkheid van dit laatste huis zal groter zijn dan van het eerste.",
    ],
    outline: [
      { range: "1", title: "Bouw het huis", summary: "De aanklacht over uitstel, en de hervatting van het werk." },
      { range: "2", title: "Drie godsspraken", summary: "Troost voor wie de eerste tempel kende, een les over rein en onrein, en de belofte aan Zerubbabel." },
    ],
    keyVerses: ["Haggaï 1:4", "Haggaï 1:6", "Haggaï 2:10"],
    studyQuestions: [
      "Waarom is 'de tijd is nog niet gekomen' zo'n herkenbare drogreden?",
      "Wat is het verband dat Haggaï legt tussen de stilstand en de misoogsten?",
      "Hoe troost hij de ouderen die de eerste tempel nog gezien hebben?",
    ],
  },
  {
    slug: "zacharia",
    name: "Zacharia",
    position: 38,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 14,
    author: "Zacharia, zoon van Berechja; over de eenheid van het boek bestaat debat.",
    written: "Vanaf 520 v.Chr.; de tweede helft mogelijk later.",
    theme: "Acht nachtvisioenen en een koning die op een ezel komt.",
    blurb:
      "Zacharia: nachtvisioenen, de hogepriester in vuile klederen, 'niet door kracht noch door geweld', en de koning op een ezel. Hoofdlijn en studievragen.",
    summary: [
      "Zacharia werkt naast Haggaï aan hetzelfde doel - de tempel moet af - maar met heel andere middelen. Waar Haggaï nuchter aanspoort, krijgt Zacharia acht nachtvisioenen achter elkaar: ruiters tussen de mirten, hoorns en smeden, een man met een meetsnoer, een vliegende boekrol, een vrouw in een efa.",
      "Het bekendste is het vierde: de hogepriester Josua staat in vuile klederen voor de engel, de satan staat rechts van hem om hem aan te klagen, en hij krijgt schone klederen aan. Het vijfde levert de zin op die generaties heeft gedragen: 'niet door kracht, noch door geweld, maar door Mijn Geest zal het geschieden'.",
      "De tweede helft van het boek is anders van toon en bevat de teksten die de evangeliën het meest aanhalen bij de laatste week van Jezus: de koning die rijdt op een ezelsveulen, de dertig zilverstukken, de herder die geslagen wordt, en 'zij zullen Mij aanschouwen, Dien zij doorstoken hebben'.",
    ],
    outline: [
      { range: "1-6", title: "Acht nachtvisioenen", summary: "Van de ruiters tussen de mirten tot de vier wagens, met de kroning van Josua." },
      { range: "7-8", title: "Vasten en herstel", summary: "Een vraag over vasten, en de belofte van oude mensen op de pleinen van Jeruzalem." },
      { range: "9-11", title: "Eerste last", summary: "De koning op een ezel, en de herder die verworpen wordt." },
      { range: "12-14", title: "Tweede last", summary: "Rouw over de doorstokene, de bron tegen zonde, en de dag des HEEREN." },
    ],
    keyVerses: ["Zacharia 3:4", "Zacharia 4:6", "Zacharia 9:9", "Zacharia 12:10"],
    studyQuestions: [
      "Wat gebeurt er in het visioen over Josua, en wie doet daarin het werk?",
      "Zoek de plaatsen in de evangeliën waar Zacharia 9:9 en 12:10 worden aangehaald.",
      "Wat betekent 4:6 in de context van een halfafgebouwde tempel?",
    ],
  },
  {
    slug: "maleachi",
    name: "Maleachi",
    position: 39,
    testament: "oude-testament",
    genre: "Kleine profeten",
    chapters: 4,
    author: "Maleachi; de naam betekent 'mijn bode' en wordt soms als titel gelezen.",
    written: "Waarschijnlijk 5e eeuw v.Chr.",
    theme: "Sleet: de tempel staat er weer, en de eredienst is een routine geworden.",
    blurb:
      "Maleachi: zes twistgesprekken over halfslachtige offers, echtscheiding en tienden, en de belofte van Elia. Hoofdlijn en studievragen.",
    summary: [
      "Maleachi is het laatste boek van het Oude Testament en het speelt in een tijd zonder crisis. De tempel is herbouwd, de eredienst loopt, er is geen ballingschap in zicht. En precies daar zit het probleem: alles is sleets geworden.",
      "Het boek is opgebouwd als zes twistgesprekken, elk met hetzelfde patroon - God stelt iets vast, het volk vraagt 'waarin dan?', en God antwoordt. Priesters brengen blind en kreupel vee op het altaar; Maleachi zegt: bied dat je landvoogd eens aan. Mannen verstoten de vrouw van hun jeugd. De tienden worden achtergehouden.",
      "Toch eindigt het niet in verbittering. Er is een gedenkboek voor wie de HEERE vrezen, er is de belofte van de Zon der gerechtigheid met genezing onder haar vleugels, en er is de aankondiging van Elia die komen zal - de tekst waarmee het Nieuwe Testament vierhonderd jaar later Johannes de Doper introduceert.",
    ],
    outline: [
      { range: "1", title: "Liefde en minachting", summary: "Gods liefde voor Jakob, en de offers die de priesters brengen." },
      { range: "2", title: "Priesters en huwelijk", summary: "Het verbond met Levi, en trouwbreuk in het huwelijk." },
      { range: "3", title: "De bode en de tienden", summary: "De Heere die tot Zijn tempel komt, en de proef met de tienden." },
      { range: "4", title: "De dag die komt", summary: "De Zon der gerechtigheid en de belofte van Elia." },
    ],
    keyVerses: ["Maleachi 1:8", "Maleachi 2:16", "Maleachi 3:10", "Maleachi 4:2"],
    studyQuestions: [
      "Zoek de zes keer dat het volk terugvraagt ('waarin dan?'). Wat zegt die reactie over hun zelfbeeld?",
      "Wat is er mis met de offers in hoofdstuk 1, technisch gezien en principieel gezien?",
      "Waarom eindigt het Oude Testament met de belofte van Elia?",
    ],
  },
];
