import type { BibleBook } from "./types";

/** Genesis t/m Esther - de Wet en de historische boeken. */
export const OT_LAW_HISTORY: BibleBook[] = [
  {
    slug: "genesis",
    name: "Genesis",
    position: 1,
    testament: "oude-testament",
    genre: "Wet",
    chapters: 50,
    author:
      "Anoniem. De joodse en christelijke traditie schrijft de vijf boeken van Mozes aan Mozes toe; het boek zelf noemt geen schrijver.",
    written: "Definitieve vorm waarschijnlijk tussen de 10e en de 5e eeuw v.Chr.",
    theme: "God schept, de mens breekt, en God begint opnieuw met één familie.",
    blurb:
      "Genesis: schepping, zondeval, zondvloed en de aartsvaders. Schrijver, ontstaanstijd, hoofdlijn per hoofdstuk, kernverzen en studievragen.",
    summary: [
      "Genesis - Grieks voor 'oorsprong' - vertelt hoe alles begint: de wereld, de mens, de zonde, de volken en het volk Israël. De eerste elf hoofdstukken beslaan een onafzienbare tijd en werken op wereldschaal: schepping, zondeval, de zondvloed, de torenbouw van Babel. Vanaf hoofdstuk 12 versmalt het verhaal abrupt tot één man en zijn nageslacht.",
      "Die versmalling is de hoofdbeweging van het boek. God kiest Abram uit Ur, belooft hem land, nakomelingen en een zegen die alle volken zal bereiken, en houdt vier generaties lang aan die belofte vast terwijl Abraham, Izak, Jakob en Jozef er van alles doorheen gooien. Bedrog, jaloezie, onvruchtbaarheid en hongersnood bedreigen de belofte telkens opnieuw, en telkens blijkt de belofte sterker dan de mensen die haar dragen.",
      "Voor bijbelstudie is Genesis het fundament onder de rest van de Schrift. Vrijwel elk later bijbelboek grijpt erop terug: de schepping, het verbond met Abraham, de twaalf stammen. Wie Genesis kent, leest de rest van de Bijbel met een kaart in de hand.",
    ],
    outline: [
      { range: "1-11", title: "Oergeschiedenis", summary: "Schepping, hof van Eden, Kaïn en Abel, de zondvloed en Babel: hoe de wereld goed begon en scheefgroeide." },
      { range: "12-25", title: "Abraham", summary: "Roeping uit Ur, het verbond, Ismaël en Izak, en het offer op de berg Moria." },
      { range: "25-36", title: "Izak en Jakob", summary: "Het eerstgeboorterecht, Jakobs vlucht en terugkeer, Pniël en de twaalf zonen." },
      { range: "37-50", title: "Jozef", summary: "Van slaaf tot onderkoning van Egypte, en de verzoening die de familie in Egypte brengt." },
    ],
    keyVerses: ["Genesis 1:1", "Genesis 3:15", "Genesis 12:1-3", "Genesis 50:20"],
    studyQuestions: [
      "Wat belooft God Abram precies in Genesis 12:1-3, en welke onderdelen van die belofte zijn aan het eind van Genesis vervuld?",
      "Volg het woord 'zegen' door het hele boek. Wie zegent wie, en waarom?",
      "Jozef zegt in 50:20 dat God ten goede dacht wat zijn broers ten kwade bedachten. Hoe verhoudt dat zich tot wat hij eerder heeft moeten doorstaan?",
    ],
  },
  {
    slug: "exodus",
    name: "Exodus",
    position: 2,
    testament: "oude-testament",
    genre: "Wet",
    chapters: 40,
    author: "Anoniem; traditioneel toegeschreven aan Mozes.",
    written: "Definitieve vorm waarschijnlijk tussen de 10e en de 5e eeuw v.Chr.",
    theme: "God bevrijdt een slavenvolk en gaat met hen wonen.",
    blurb:
      "Exodus: uittocht uit Egypte, de tien plagen, de Sinaï en de tabernakel. Hoofdlijn, kernverzen en studievragen bij het tweede boek van Mozes.",
    summary: [
      "Exodus begint waar Genesis eindigde: Jakobs familie woont in Egypte, maar 'er stond een nieuwe koning op, die Jozef niet gekend had'. Uit een gastvolk is een slavenvolk geworden. Het boek vertelt hoe God dat volk eruit haalt - via Mozes, tien plagen en een doortocht door de zee.",
      "De uittocht is niet het eindpunt. Halverwege het boek staat het volk bij de Sinaï, waar God een verbond sluit en de Tien Geboden geeft. De tweede helft gaat bijna geheel over de tabernakel: hoe die gebouwd moet worden en hoe die gebouwd wordt. Dat lijkt gedetailleerd tot vervelens toe, tot je ziet waar het op uitloopt - de heerlijkheid van de HEERE die de tabernakel vult in het laatste hoofdstuk.",
      "Dat is de boog van Exodus: van slavernij naar aanwezigheid. God bevrijdt niet alleen ergens vandaan, maar ook ergens naartoe - naar een leven waarin Hij midden in het kamp woont.",
    ],
    outline: [
      { range: "1-12", title: "Slavernij en bevrijding", summary: "Onderdrukking, de roeping van Mozes bij de braamstruik, de tien plagen en het Pascha." },
      { range: "13-18", title: "Van Egypte naar de Sinaï", summary: "Doortocht door de zee, manna, water uit de rots en de raad van Jethro." },
      { range: "19-24", title: "Het verbond bij de Sinaï", summary: "De Tien Geboden en de bondssluiting met bloed." },
      { range: "25-40", title: "De tabernakel", summary: "Bouwvoorschriften, het gouden kalf, vernieuwing van het verbond en de bouw zelf." },
    ],
    keyVerses: ["Exodus 3:14", "Exodus 12:13", "Exodus 20:2-3", "Exodus 40:34"],
    studyQuestions: [
      "Wat zegt Gods naam in Exodus 3:14 over wie Hij is, en hoe wordt dat in de rest van het boek waargemaakt?",
      "Waarom staat het verhaal van het gouden kalf midden tussen de tabernakelhoofdstukken in?",
      "Vergelijk Exodus 20:2 met de geboden die erop volgen. Wat gaat er aan de geboden vooraf?",
    ],
  },
  {
    slug: "leviticus",
    name: "Leviticus",
    position: 3,
    testament: "oude-testament",
    genre: "Wet",
    chapters: 27,
    author: "Anoniem; traditioneel toegeschreven aan Mozes.",
    written: "Definitieve vorm waarschijnlijk in de periode van de ballingschap of daarvoor.",
    theme: "Hoe een onheilig volk kan leven in de buurt van een heilige God.",
    blurb:
      "Leviticus: offers, priesters, reinheid en de Grote Verzoendag. Uitleg van de hoofdlijn, met kernverzen en studievragen.",
    summary: [
      "Leviticus is het boek waar de meeste lezers stranden, en dat is jammer, want het beantwoordt de vraag die Exodus openlaat. Als God nu midden in het kamp woont - hoe overleef je dat? Hoe kom je in de buurt van Iemand die volstrekt anders is dan jij?",
      "Het antwoord komt in twee delen. De eerste helft gaat over de offers en het priesterschap: er is een geregelde manier om schuld weg te doen en gemeenschap te vieren. Het scharnier is hoofdstuk 16, de Grote Verzoendag, waarop het hele volk in één rite wordt gereinigd. De tweede helft, vaak de Heiligheidswet genoemd, trekt de lijn door naar het gewone leven: seksualiteit, eerlijkheid in de handel, de omgang met vreemdelingen, het sabbatsjaar en het jubeljaar.",
      "De sleutelzin staat in 19:2: 'Weest heilig, want Ik ben heilig.' Heiligheid is in Leviticus geen stemming maar een manier van leven die tot in de akkerranden en de weegschaal doorwerkt.",
    ],
    outline: [
      { range: "1-7", title: "De offers", summary: "Brandoffer, spijsoffer, dankoffer, zondoffer en schuldoffer, en wat elk ervan doet." },
      { range: "8-10", title: "Het priesterschap", summary: "Wijding van Aäron en zijn zonen, en het oordeel over Nadab en Abihu." },
      { range: "11-15", title: "Rein en onrein", summary: "Voedsel, geboorte, huidziekten en lichamelijke onreinheid." },
      { range: "16", title: "De Grote Verzoendag", summary: "Het hart van het boek: verzoening voor het hele volk en de bok voor Azazel." },
      { range: "17-27", title: "De Heiligheidswet", summary: "Heilig leven in seksualiteit, recht, feesten, sabbatsjaar en jubeljaar." },
    ],
    keyVerses: ["Leviticus 11:45", "Leviticus 16:30", "Leviticus 17:11", "Leviticus 19:18"],
    studyQuestions: [
      "Wat is volgens Leviticus 17:11 de reden dat bloed verzoening doet?",
      "Lees hoofdstuk 19 als geheel. Welke geboden verrassen je door hoe alledaags ze zijn?",
      "Hoe gebruikt de brief aan de Hebreeën de Grote Verzoendag uit Leviticus 16?",
    ],
  },
  {
    slug: "numeri",
    name: "Numeri",
    position: 4,
    testament: "oude-testament",
    genre: "Wet",
    chapters: 36,
    author: "Anoniem; traditioneel toegeschreven aan Mozes.",
    written: "Definitieve vorm waarschijnlijk tussen de 7e en de 5e eeuw v.Chr.",
    theme: "Een generatie die het beloofde land weigert binnen te gaan, en de God die toch doorgaat.",
    blurb:
      "Numeri: de tellingen, de veertig jaar in de woestijn, Korach, de koperen slang en Bileam. Hoofdlijn en studievragen.",
    summary: [
      "Numeri dankt zijn naam aan de twee volkstellingen die het boek omlijsten: één van de generatie die uit Egypte kwam, en één van de generatie die het land binnengaat. Tussen die twee tellingen ligt veertig jaar woestijn, en de reden daarvoor staat in de hoofdstukken 13 en 14: twaalf verspieders gaan het land in, tien komen terug met een verhaal over reuzen, en het volk weigert.",
      "Het boek is daardoor grimmiger dan Exodus. Er wordt gemord over eten, over leiderschap, over water. Korach komt in opstand, Mirjam en Aäron keren zich tegen Mozes, Mozes zelf slaat op de rots in plaats van te spreken en verspeelt daarmee zijn toegang tot het land.",
      "En toch loopt het niet stuk. De heidense ziener Bileam, ingehuurd om Israël te vervloeken, kan zijn mond niet opendoen zonder te zegenen. Dat is de tegenstem van het boek: Gods belofte hangt niet af van de kwaliteit van het volk dat haar draagt.",
    ],
    outline: [
      { range: "1-10", title: "Bij de Sinaï", summary: "Telling, indeling van het kamp, de Levieten en het vertrek naar het noorden." },
      { range: "11-19", title: "Opstand in de woestijn", summary: "Gemor, de verspieders, Korach, en veertig jaar rondtrekken." },
      { range: "20-25", title: "Naar de vlakten van Moab", summary: "Water uit de rots, de koperen slang, Bileams zegeningen en Baäl-Peor." },
      { range: "26-36", title: "De nieuwe generatie", summary: "Tweede telling, de dochters van Zelafead, en de verdeling van het land." },
    ],
    keyVerses: ["Numeri 6:24-26", "Numeri 13:30", "Numeri 14:18", "Numeri 21:9"],
    studyQuestions: [
      "Vergelijk het rapport van Kaleb (13:30) met dat van de tien anderen. Waarin verschillen ze feitelijk, en waarin niet?",
      "Waarom mag Mozes het land niet in? Lees Numeri 20:1-13 zorgvuldig.",
      "Wat doet Jezus in Johannes 3:14-15 met de koperen slang uit Numeri 21?",
    ],
  },
  {
    slug: "deuteronomium",
    name: "Deuteronomium",
    position: 5,
    testament: "oude-testament",
    genre: "Wet",
    chapters: 34,
    author: "Anoniem; grotendeels opgetekend als toespraken van Mozes.",
    written: "Kern waarschijnlijk 7e eeuw v.Chr., met oudere tradities.",
    theme: "Onthoud wat God gedaan heeft, en heb Hem lief met alles wat je bent.",
    blurb:
      "Deuteronomium: Mozes' afscheidsredes, het Sjema, zegen en vloek. Hoofdlijn per hoofdstuk, kernverzen en studievragen.",
    summary: [
      "Deuteronomium speelt zich af op één plek en in één week: het volk staat aan de oostkant van de Jordaan, klaar om over te steken, en Mozes houdt zijn afscheidsredes. Hij gaat niet mee. Alles wat hij nog te zeggen heeft, staat in dit boek.",
      "De naam betekent 'tweede wet', maar het is geen herhaling. Het is een uitleg voor een nieuwe generatie, die Egypte niet zelf heeft meegemaakt. Daarom staat het woord 'gedenk' er zo vaak: wie vergeet waar hij vandaan komt, gaat denken dat hij het land aan zichzelf te danken heeft.",
      "Het hart is het Sjema in 6:4-5, het gebed dat het jodendom tot vandaag twee keer per dag bidt en dat Jezus het grote gebod noemt. Het boek eindigt met een keuze die zo scherp mogelijk wordt gesteld - zegen of vloek, leven of dood - en met de dood van Mozes op de Nebo, in zicht van het land dat hij nooit zal betreden.",
    ],
    outline: [
      { range: "1-4", title: "Terugblik", summary: "Wat er sinds de Horeb gebeurd is, en wat daaruit te leren valt." },
      { range: "5-11", title: "Het grote gebod", summary: "De Tien Geboden herhaald, het Sjema, en de waarschuwing tegen vergeten." },
      { range: "12-26", title: "De wetten", summary: "Eredienst, rechtspraak, koningschap, oorlog, armenzorg en eerlijk handelsverkeer." },
      { range: "27-34", title: "Zegen, vloek en afscheid", summary: "Ebal en Gerizim, het lied van Mozes, de zegen over de stammen en zijn dood." },
    ],
    keyVerses: ["Deuteronomium 6:4-5", "Deuteronomium 8:3", "Deuteronomium 30:19", "Deuteronomium 31:6"],
    studyQuestions: [
      "Tel hoe vaak 'gedenk' of 'vergeet niet' voorkomt. Waartegen waarschuwt Mozes precies?",
      "Wat betekent het om God lief te hebben 'met geheel uw hart, en met geheel uw ziel, en met geheel uw vermogen'?",
      "Jezus citeert Deuteronomium drie keer in de verzoeking in de woestijn. Zoek de drie plaatsen op en let op hun oorspronkelijke context.",
    ],
  },
  {
    slug: "jozua",
    name: "Jozua",
    position: 6,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 24,
    author: "Anoniem.",
    written: "Definitieve vorm waarschijnlijk 7e-6e eeuw v.Chr.",
    theme: "God geeft het beloofde land - en het volk moet kiezen wie het dient.",
    blurb:
      "Jozua: de intocht, Jericho, de verdeling van het land en de bondsvernieuwing in Sichem. Hoofdlijn, kernverzen en studievragen.",
    summary: [
      "Jozua vertelt hoe de belofte aan Abraham grond onder de voeten krijgt. Het volk trekt door de Jordaan zoals het door de Schelfzee trok, en de eerste stad die valt - Jericho - valt zonder dat er een muur wordt gebeukt.",
      "Het boek is in drie delen te lezen: de intocht en de veroveringen (1-12), de verdeling van het land onder de stammen (13-21), en het slot waarin Jozua het volk voor een keuze stelt (22-24). Dat middendeel met zijn eindeloze grenslijsten lijkt saai, maar het is het bewijsstuk: wat beloofd was, is uitgemeten en toegewezen.",
      "Jozua is ook een lastig boek, want de verovering gaat gepaard met geweld dat moderne lezers doet terugdeinzen. Wie het serieus bestudeert, laat die vragen staan in plaats van ze weg te poetsen, en let op hoe het boek zelf de nadruk legt: niet op de kracht van Israël, maar op wat God geeft, en op Rachab en de Gibeonieten, buitenstaanders die erbij gaan horen.",
    ],
    outline: [
      { range: "1-5", title: "De intocht", summary: "Roeping van Jozua, Rachab, de doortocht door de Jordaan en de besnijdenis bij Gilgal." },
      { range: "6-12", title: "De veroveringen", summary: "Jericho, de zonde van Achan, Ai, de list van Gibeon en de veldtochten." },
      { range: "13-21", title: "De verdeling", summary: "Het erfdeel van elke stam, de vrijsteden en de steden van de Levieten." },
      { range: "22-24", title: "Afscheid en keuze", summary: "Het altaar bij de Jordaan en de bondsvernieuwing te Sichem." },
    ],
    keyVerses: ["Jozua 1:8-9", "Jozua 2:11", "Jozua 21:45", "Jozua 24:15"],
    studyQuestions: [
      "Wat krijgt Jozua in hoofdstuk 1 als opdracht mee, en hoe vaak wordt 'wees sterk en heb goeden moed' herhaald?",
      "Rachab en Achan staan vlak bij elkaar in het boek. Wat zegt die volgorde?",
      "Wat maakt de keuze in 24:15 scherp, gezien wat het volk op dat moment al bezit?",
    ],
  },
  {
    slug: "richteren",
    name: "Richteren",
    position: 7,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 21,
    author: "Anoniem.",
    written: "Definitieve vorm waarschijnlijk 7e-6e eeuw v.Chr.",
    theme: "Zonder koning doet ieder wat goed is in eigen ogen - en het gaat steeds verder mis.",
    blurb:
      "Richteren: Debora, Gideon, Simson en de spiraal van afval en redding. Hoofdlijn, kernverzen en studievragen.",
    summary: [
      "Richteren is het boek na de overwinning, en dat valt tegen. Het land is ingenomen maar niet doorleefd. Steeds herhaalt zich hetzelfde patroon: Israël dient andere goden, een vijand krijgt de overhand, het volk roept om hulp, God zendt een richter, er komt rust - en dan begint het opnieuw.",
      "Wie oplet ziet dat het geen cirkel is maar een spiraal naar beneden. De vroege richters zijn indrukwekkend, de latere steeds dubieuzer. Gideon maakt aan het eind een efod waar het volk achteraan hoereert. Jefta doet een gelofte die hem zijn dochter kost. Simson, de sterkste van allemaal, is een man die zijn roeping vrijwel volledig verspeelt.",
      "De laatste vijf hoofdstukken zijn de donkerste van het Oude Testament, en het boek geeft er zelf de diagnose bij: 'in die dagen was er geen koning in Israël; een ieder deed wat recht was in zijn ogen'. Daarmee zet Richteren precies de vraag op tafel die Samuël en Koningen gaan behandelen.",
    ],
    outline: [
      { range: "1-2", title: "Onvoltooide verovering", summary: "Wat er niet is ingenomen, en de aankondiging van het patroon dat volgt." },
      { range: "3-5", title: "De eerste richters", summary: "Othniël, Ehud, Samgar, en het lied van Debora en Barak." },
      { range: "6-12", title: "Gideon, Abimelech, Jefta", summary: "De 300 van Gideon, het koningschap van Abimelech, en Jefta's gelofte." },
      { range: "13-16", title: "Simson", summary: "Nazireeër van de geboorte af, en de val door Delila." },
      { range: "17-21", title: "Twee gruwelverhalen", summary: "Micha's huisgod en de misdaad in Gibea: hoe diep het wegzakt." },
    ],
    keyVerses: ["Richteren 2:16-19", "Richteren 6:15-16", "Richteren 16:20", "Richteren 21:25"],
    studyQuestions: [
      "Schrijf het patroon uit Richteren 2:16-19 uit in stappen en test het op drie richters. Waar wijkt het af?",
      "Wat maakt Simson tot een tragische figuur in plaats van een held?",
      "Waarom eindigt het boek met twee verhalen zonder richter erin?",
    ],
  },
  {
    slug: "ruth",
    name: "Ruth",
    position: 8,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 4,
    author: "Anoniem.",
    written: "Onzeker; voorstellen lopen van de vroege koningstijd tot na de ballingschap.",
    theme: "Trouw in het klein bouwt aan een geschiedenis die veel groter is dan de betrokkenen zien.",
    blurb:
      "Ruth: een Moabitische weduwe, Boaz als losser, en de lijn naar David. Korte hoofdlijn, kernverzen en studievragen.",
    summary: [
      "Ruth speelt 'in de dagen als de richters richtten' - precies de tijd waarin volgens Richteren alles misging. En dan vertelt dit boekje van vier hoofdstukken over drie mensen die eenvoudigweg trouw zijn.",
      "Naomi verliest in Moab haar man en beide zonen. Haar Moabitische schoondochter Ruth weigert terug te gaan naar haar eigen volk en spreekt de woorden die generaties lang bij huwelijken worden gelezen: 'uw volk is mijn volk, en uw God mijn God'. In Bethlehem raapt ze aren op het veld van Boaz, die als losser zijn verantwoordelijkheid neemt in plaats van hem te ontlopen.",
      "Het slot laat zien waar dit allemaal op uitliep: Ruth wordt de overgrootmoeder van David, en daarmee staat een Moabitische in de stamboom van Jezus. Voor bijbelstudie is het een uitgelezen boek om in één zitting te lezen - kort genoeg om het geheel te overzien, rijk genoeg om er weken over te doen.",
    ],
    outline: [
      { range: "1", title: "Verlies", summary: "Hongersnood, Moab, drie doden en de terugkeer van Naomi met Ruth." },
      { range: "2", title: "Het veld van Boaz", summary: "Aren rapen onder de wet op de nalezing, en de eerste ontmoeting." },
      { range: "3", title: "De dorsvloer", summary: "Naomi's plan en Ruths verzoek aan de losser." },
      { range: "4", title: "De losser", summary: "De poort, de nadere bloedverwant, het huwelijk en de geboorte van Obed." },
    ],
    keyVerses: ["Ruth 1:16-17", "Ruth 2:12", "Ruth 3:9", "Ruth 4:17"],
    studyQuestions: [
      "Naomi noemt zich Mara, 'bitter'. Hoe verandert haar taal over God in de loop van het boek?",
      "Wat houdt het lossersrecht in, en wat kost het Boaz om het uit te oefenen?",
      "Wat betekent het dat een Moabitische in Mattheüs 1 in het geslachtsregister van Jezus staat?",
    ],
  },
  {
    slug: "1-samuel",
    name: "1 Samuël",
    position: 9,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 31,
    author: "Anoniem.",
    written: "Definitieve vorm waarschijnlijk 7e-6e eeuw v.Chr.",
    theme: "Israël vraagt om een koning als de andere volken, en krijgt eerst Saul en dan David.",
    blurb:
      "1 Samuël: Hanna, de roeping van Samuël, koning Saul, David en Goliath. Hoofdlijn, kernverzen en studievragen.",
    summary: [
      "1 Samuël is het scharnier tussen de richters en het koningschap. Het begint klein: een kinderloze vrouw, Hanna, die in Silo zo hartstochtelijk bidt dat de priester haar voor dronken aanziet. Haar zoon Samuël wordt de laatste richter en de profeet die twee koningen zal zalven.",
      "Het volk vraagt om een koning 'gelijk al de volken'. Samuël waarschuwt precies wat dat gaat kosten - dienstplicht, belasting, onteigening - en het volk wil het toch. Saul begint veelbelovend en loopt vast op ongehoorzaamheid; het oordeel in 15:22 is de scherpste zin van het boek: 'zie, gehoorzamen is beter dan slachtoffer'.",
      "Daarna verschuift het licht naar David: gezalfd als jongste zoon, held tegen Goliath, en vervolgens jarenlang opgejaagd door de koning die hij twee keer had kunnen doden en twee keer spaart. Het boek eindigt met Sauls dood op de Gilboa, en met David nog niet op de troon.",
    ],
    outline: [
      { range: "1-7", title: "Samuël", summary: "Hanna's gebed, de roeping in Silo, de ark bij de Filistijnen en Eben-Haëzer." },
      { range: "8-15", title: "Saul", summary: "De vraag om een koning, Sauls zalving, zijn overwinningen en zijn verwerping." },
      { range: "16-20", title: "David gezalfd", summary: "De zalving in Bethlehem, Goliath, en de vriendschap met Jonathan." },
      { range: "21-31", title: "David op de vlucht", summary: "Nob, Adullam, twee keer sparen van Saul, en Sauls dood op de Gilboa." },
    ],
    keyVerses: ["1 Samuël 2:1-10", "1 Samuël 8:7", "1 Samuël 15:22", "1 Samuël 16:7"],
    studyQuestions: [
      "Lees het lied van Hanna (2:1-10) en vergelijk het met het Magnificat in Lukas 1. Wat valt op?",
      "Wat zegt Samuël dat een koning gaat doen (hoofdstuk 8), en klopt dat later?",
      "David spaart Saul twee keer. Wat is zijn motief, en wat zegt dat over hoe hij het koningschap ziet?",
    ],
  },
  {
    slug: "2-samuel",
    name: "2 Samuël",
    position: 10,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 24,
    author: "Anoniem.",
    written: "Definitieve vorm waarschijnlijk 7e-6e eeuw v.Chr.",
    theme: "Gods belofte aan David houdt stand, ook als David zelf instort.",
    blurb:
      "2 Samuël: David koning, Jeruzalem, het verbond met David, Bathseba en Absalom. Hoofdlijn, kernverzen en studievragen.",
    summary: [
      "2 Samuël is het verhaal van één man op de troon, en het valt netjes in twee helften uiteen. In de eerste helft gaat alles goed: David wordt koning over Juda en daarna over heel Israël, neemt Jeruzalem in, haalt de ark binnen, en krijgt in hoofdstuk 7 de belofte dat zijn huis en koningschap voor eeuwig zullen bestaan.",
      "In hoofdstuk 11 kantelt het. David blijft thuis terwijl zijn leger uittrekt, ziet Bathseba, en laat haar man vermoorden om het te bedekken. De profeet Nathan zet hem in vier woorden vast: 'gij zijt die man'. David belijdt, maar de gevolgen blijven: verkrachting binnen zijn eigen gezin, broedermoord, en de opstand van zijn zoon Absalom die hem Jeruzalem uit jaagt.",
      "Wat het boek onderscheidt van hofpropaganda is precies dat het dit alles opschrijft. De belofte van hoofdstuk 7 wordt niet ingetrokken, maar hij hangt van dat moment af aan Gods trouw en niet aan Davids gedrag.",
    ],
    outline: [
      { range: "1-10", title: "Opkomst", summary: "Koning over Juda en Israël, Jeruzalem, de ark, en het verbond met David." },
      { range: "11-12", title: "Bathseba", summary: "Overspel, moord, Nathans gelijkenis en Davids belijdenis." },
      { range: "13-20", title: "Gevolgen", summary: "Amnon en Tamar, Absaloms wraak en opstand, en Davids vlucht en terugkeer." },
      { range: "21-24", title: "Aanhangsel", summary: "Verhalen, twee liederen, de helden van David en de volkstelling." },
    ],
    keyVerses: ["2 Samuël 7:12-16", "2 Samuël 12:7", "2 Samuël 12:13", "2 Samuël 22:2-3"],
    studyQuestions: [
      "Wat belooft God David precies in 7:12-16, en welke voorwaarden staan erbij?",
      "Nathan gebruikt een gelijkenis in plaats van een aanklacht. Waarom werkt dat?",
      "Lees Psalm 51 naast 2 Samuël 12. Wat voegt de psalm toe aan wat het verhaal vertelt?",
    ],
  },
  {
    slug: "1-koningen",
    name: "1 Koningen",
    position: 11,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 22,
    author: "Anoniem.",
    written: "Definitieve vorm tijdens of kort na de ballingschap (6e eeuw v.Chr.).",
    theme: "Van Salomo's tempel naar een gespleten koninkrijk en de profeet die ertegenin gaat.",
    blurb:
      "1 Koningen: Salomo, de tempelbouw, de scheuring van het rijk en Elia op de Karmel. Hoofdlijn en studievragen.",
    summary: [
      "1 Koningen begint op het hoogtepunt. Salomo vraagt om een verstandig hart in plaats van om rijkdom, bouwt de tempel, en ontvangt de koningin van Scheba die verbijsterd achterblijft. Het is de kortste periode van glans in de hele geschiedenis van Israël.",
      "Het houdt niet. Salomo's vele buitenlandse vrouwen brengen hun goden mee, en na zijn dood scheurt het rijk in tweeën: tien stammen in het noorden onder Jerobeam, Juda en Benjamin in het zuiden onder Rehabeam. Jerobeam zet twee gouden kalveren neer zodat niemand meer naar Jeruzalem hoeft, en dat wordt de standaardformule waarmee de rest van het boek noordelijke koningen beoordeelt.",
      "De tweede helft wordt beheerst door Achab, Izebel en de profeet Elia. De confrontatie op de Karmel is het bekendste hoofdstuk, maar het aangrijpendste komt daarna: Elia onder de jeneverstruik, doodmoe, en God die hem niet in storm of vuur maar in een zacht suizen tegemoetkomt.",
    ],
    outline: [
      { range: "1-11", title: "Salomo", summary: "Troonsbestijging, wijsheid, tempelbouw, rijkdom en afgoderij." },
      { range: "12-16", title: "De scheuring", summary: "Rehabeam en Jerobeam, de kalveren in Dan en Bethel, en een reeks koningen." },
      { range: "17-19", title: "Elia", summary: "Droogte, de weduwe van Zarfath, de Karmel en de Horeb." },
      { range: "20-22", title: "Achab", summary: "Oorlogen met Syrië, de wijngaard van Naboth en Achabs dood." },
    ],
    keyVerses: ["1 Koningen 3:9", "1 Koningen 8:27", "1 Koningen 18:21", "1 Koningen 19:12"],
    studyQuestions: [
      "Wat vraagt Salomo in 3:9, en waarom is dat volgens het boek de juiste vraag?",
      "Waarom is Jerobeams besluit in hoofdstuk 12 zo bepalend voor alles wat volgt?",
      "Vergelijk de Karmel (18) met de Horeb (19). Wat leert het contrast over hoe God werkt?",
    ],
  },
  {
    slug: "2-koningen",
    name: "2 Koningen",
    position: 12,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 25,
    author: "Anoniem.",
    written: "Definitieve vorm tijdens of kort na de ballingschap (6e eeuw v.Chr.).",
    theme: "Twee koninkrijken lopen, ondanks waarschuwing na waarschuwing, op ballingschap uit.",
    blurb:
      "2 Koningen: Elisa, de val van Samaria, Hizkia, Josia en de ballingschap in Babel. Hoofdlijn en studievragen.",
    summary: [
      "2 Koningen zet in waar 1 Koningen ophield: Elia wordt in een storm opgenomen, Elisa vraagt om een dubbel deel van zijn geest en krijgt het. De eerste hoofdstukken staan vol wonderen die opvallend vaak buitenstaanders en armen betreffen - een weduwe met een oliekruik, een Syrische legeroverste met melaatsheid.",
      "Daarna wordt het boek een aftelling. Het noordrijk gaat door met de zonde van Jerobeam en valt in 722 v.Chr. aan Assyrië; de bevolking wordt gedeporteerd. Juda houdt het langer vol en kent twee opmerkelijke hervormers: Hizkia, die de belegering van Jeruzalem overleeft, en Josia, die bij een tempelrestauratie het wetboek terugvindt en het volk erop wijst.",
      "Ook dat is niet genoeg. In 586 v.Chr. neemt Nebukadnezar Jeruzalem in, verbrandt de tempel en voert het volk weg. Het boek eindigt met een minieme lichtstraal: koning Jojachin mag in Babel aan de tafel van de koning eten. De lijn van David is dun geworden, maar niet afgesneden.",
    ],
    outline: [
      { range: "1-8", title: "Elisa", summary: "Elia's hemelvaart, de wonderen van Elisa en Naäman de Syriër." },
      { range: "9-17", title: "Het einde van Israël", summary: "Jehu's revolutie, de laatste noordelijke koningen en de val van Samaria." },
      { range: "18-20", title: "Hizkia", summary: "Hervorming, de Assyrische belegering en Jesaja's woord." },
      { range: "21-25", title: "Het einde van Juda", summary: "Manasse, Josia's hervorming, en de val van Jeruzalem." },
    ],
    keyVerses: ["2 Koningen 2:9", "2 Koningen 5:14", "2 Koningen 17:7", "2 Koningen 22:8"],
    studyQuestions: [
      "Wat is de vaste maatstaf waarmee het boek koningen beoordeelt? Zoek de terugkerende formule.",
      "Waarom besteedt 17:7-23 zoveel ruimte aan de uitleg van de val van Samaria?",
      "Josia's hervorming is grondig en toch keert het oordeel niet. Wat zegt 23:26-27 daarover?",
    ],
  },
  {
    slug: "1-kronieken",
    name: "1 Kronieken",
    position: 13,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 29,
    author: "Anoniem; traditioneel 'de kroniekschrijver', soms met Ezra vereenzelvigd.",
    written: "Waarschijnlijk 4e eeuw v.Chr., na de ballingschap.",
    theme: "Wie zijn wij nog, na de ballingschap? Het antwoord begint bij de geslachtsregisters.",
    blurb:
      "1 Kronieken: negen hoofdstukken geslachtsregisters, David en de voorbereiding van de tempel. Hoofdlijn en studievragen.",
    summary: [
      "Kronieken vertelt dezelfde geschiedenis als Samuël en Koningen, maar voor een ander publiek en met een ander doel. De lezers zijn teruggekeerde ballingen: een klein volk, zonder koning, met een bescheiden tempel. De vraag onder het boek is of zij nog wel bij Israël horen.",
      "Daarom die negen hoofdstukken geslachtsregisters aan het begin, van Adam tot de terugkeer uit Babel. Ze zijn niet overgeslagen materiaal maar het argument zelf: de lijn is niet doorgeknipt.",
      "De rest van 1 Kronieken gaat over David, maar over een andere David dan in 2 Samuël. Bathseba ontbreekt, Absalom ontbreekt. Wat overblijft is David als organisator van de eredienst: hij haalt de ark binnen, koopt de dorsvloer van Ornan, verzamelt materiaal en stelt de zangers, poortwachters en priesterafdelingen in. Niet omdat de kroniekschrijver de zonde verzwijgt, maar omdat zijn onderwerp de tempeldienst is die zijn lezers weer moeten oppakken.",
    ],
    outline: [
      { range: "1-9", title: "Geslachtsregisters", summary: "Van Adam via de stammen naar de bewoners van Jeruzalem na de terugkeer." },
      { range: "10-12", title: "Van Saul naar David", summary: "Sauls dood en de helden die zich bij David voegen." },
      { range: "13-17", title: "De ark en de belofte", summary: "De ark naar Jeruzalem en het verbond met David." },
      { range: "18-29", title: "Voorbereiding van de tempel", summary: "Oorlogen, de volkstelling, de dorsvloer, en de indeling van priesters en zangers." },
    ],
    keyVerses: ["1 Kronieken 4:10", "1 Kronieken 16:11", "1 Kronieken 17:11-14", "1 Kronieken 29:14"],
    studyQuestions: [
      "Waarom besteedt de schrijver negen hoofdstukken aan namen? Wat wil hij zijn lezers laten zien?",
      "Vergelijk 1 Kronieken 17 met 2 Samuël 7. Welke verschillen zie je, en wat doen ze?",
      "Wat zegt Davids gebed in 29:10-19 over bezit en geven?",
    ],
  },
  {
    slug: "2-kronieken",
    name: "2 Kronieken",
    position: 14,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 36,
    author: "Anoniem; dezelfde hand als 1 Kronieken.",
    written: "Waarschijnlijk 4e eeuw v.Chr., na de ballingschap.",
    theme: "De tempel en de koningen van Juda, gelezen als les over omkeer.",
    blurb:
      "2 Kronieken: Salomo's tempel, de koningen van Juda, hervorming en ballingschap, en het bevel van Kores. Hoofdlijn en studievragen.",
    summary: [
      "2 Kronieken begint met Salomo en de bouw van de tempel, en volgt daarna uitsluitend de koningen van Juda - het noordrijk komt alleen in beeld waar het Juda raakt. Dat is geen slordigheid maar keuze: de lijn die telt voor de teruggekeerde ballingen loopt via Jeruzalem.",
      "Het boek werkt met een duidelijk patroon van omkeer. Waar Koningen vaak alleen het oordeel meldt, laat Kronieken uitgebreid zien wat een koning deed die zich wél bekeerde. Asa, Josafat, Joas, Hizkia en Josia krijgen ruime hervormingsverslagen. Zelfs Manasse, in Koningen de slechtste koning die Juda gehad heeft, wordt hier in Babel verootmoedigd en hersteld.",
      "De sleutelzin is 7:14: 'zo Mijn volk, over dewelke Mijn Naam genoemd wordt, zich verootmoedigt, en zij bidden...'. Het boek eindigt niet met de puinhopen maar met het bevel van Kores dat de terugkeer mogelijk maakt - midden in een zin, alsof het verhaal nog doorloopt.",
    ],
    outline: [
      { range: "1-9", title: "Salomo", summary: "Wijsheid, tempelbouw, inwijding en de koningin van Scheba." },
      { range: "10-20", title: "De eerste koningen", summary: "De scheuring, Asa en Josafat en hun hervormingen." },
      { range: "21-28", title: "Verval", summary: "Joram, Athalia, Joas, Uzzia en Achaz." },
      { range: "29-36", title: "Hizkia tot de ballingschap", summary: "Hizkia's pascha, Manasse's ommekeer, Josia's hervorming en de val van Jeruzalem." },
    ],
    keyVerses: ["2 Kronieken 7:14", "2 Kronieken 16:9", "2 Kronieken 20:12", "2 Kronieken 36:23"],
    studyQuestions: [
      "Wat zijn de vier werkwoorden in 7:14, en in welke volgorde staan ze?",
      "Vergelijk het verslag over Manasse hier (33) met dat in 2 Koningen 21. Wat is toegevoegd?",
      "Josafats gebed in 20:1-12 eindigt met 'onze ogen zijn op U'. Hoe bouwt hij zijn gebed op?",
    ],
  },
  {
    slug: "ezra",
    name: "Ezra",
    position: 15,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 10,
    author: "Anoniem; delen zijn geschreven in de ik-vorm van Ezra.",
    written: "Waarschijnlijk 4e eeuw v.Chr.",
    theme: "Terug uit ballingschap: eerst het altaar, dan de tempel, dan de wet.",
    blurb:
      "Ezra: terugkeer uit Babel, de herbouw van de tempel, tegenstand, en de hervorming van Ezra. Hoofdlijn en studievragen.",
    summary: [
      "Ezra opent met het edict van Kores, de Perzische koning die de ballingen laat terugkeren. Het boek beschrijft twee golven: eerst een groep onder Zerubbabel die het altaar herstelt en aan de tempel begint, ruim tachtig jaar later een groep onder de schriftgeleerde Ezra.",
      "De herbouw gaat niet vanzelf. Buren bieden hulp aan, worden geweigerd, en dwarsbomen het werk vervolgens via de Perzische administratie tot het bouwen jaren stilligt. Pas als de profeten Haggaï en Zacharia optreden komt het weer op gang, en in 516 v.Chr. staat de tweede tempel er.",
      "Het slot is ongemakkelijk. Ezra ontdekt dat teruggekeerden gemengde huwelijken hebben gesloten met de omringende volken, scheurt zijn kleed en leidt een pijnlijke scheiding. Wie dit gedeelte bestudeert doet er goed aan de context te wegen: een minuscule gemeenschap die vreest opnieuw op te gaan in de volken, en het boek Ruth dat vlakbij in dezelfde Bijbel een Moabitische in de stamboom van David zet.",
    ],
    outline: [
      { range: "1-2", title: "De terugkeer", summary: "Het bevel van Kores en de lijst van wie terugging." },
      { range: "3-6", title: "De tempel", summary: "Altaar, fundament, tegenstand, hervatting en inwijding." },
      { range: "7-8", title: "Ezra komt", summary: "Zijn opdracht van Artachsasta en de tocht naar Jeruzalem." },
      { range: "9-10", title: "De hervorming", summary: "Gemengde huwelijken, Ezra's gebed en de maatregelen." },
    ],
    keyVerses: ["Ezra 1:2-3", "Ezra 3:11-12", "Ezra 7:10", "Ezra 9:6"],
    studyQuestions: [
      "In 3:12 huilen de oudsten terwijl anderen juichen. Waarom?",
      "Wat zegt 7:10 over de volgorde waarin Ezra met de wet omging?",
      "Hoe bidt Ezra in hoofdstuk 9 over zonde die niet de zijne is?",
    ],
  },
  {
    slug: "nehemia",
    name: "Nehemia",
    position: 16,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 13,
    author: "Grotendeels de memoires van Nehemia zelf, in de ik-vorm.",
    written: "Waarschijnlijk 4e eeuw v.Chr.",
    theme: "Bidden en bouwen: een muur in tweeënvijftig dagen en een volk dat opnieuw luistert.",
    blurb:
      "Nehemia: de herbouw van de muur van Jeruzalem, tegenstand van Sanballat, en de wetlezing van Ezra. Hoofdlijn en studievragen.",
    summary: [
      "Nehemia is schenker aan het Perzische hof wanneer hij hoort dat de muur van Jeruzalem in puin ligt. Hij bidt vier maanden, vraagt dan verlof aan de koning, en vertrekt met bouwmateriaal en een escorte.",
      "Het middendeel is een van de meest concrete stukken projectleiding in de Bijbel. Nehemia inspecteert 's nachts, verdeelt de muur in secties per familie, en reageert op tegenstand die achtereenvolgens spot, dreiging, sabotage, uitnodigingen tot overleg en laster is. Ondertussen pakt hij een interne kwestie aan: rijke Judeeërs die hun eigen volksgenoten tot schuldslavernij drijven. De muur staat er in tweeënvijftig dagen.",
      "Dan verschuift het boek van steen naar mens. Ezra leest de wet voor op het plein bij de Waterpoort, van de ochtend tot de middag, met uitleggers ernaast. Het volk huilt, viert loofhutten, belijdt, en verbindt zich opnieuw. Het slot laat zien hoe snel dat weer wegzakt zodra Nehemia een tijd weg is - een eerlijk einde.",
    ],
    outline: [
      { range: "1-2", title: "Het bericht en het plan", summary: "Nehemia's gebed, het verzoek aan de koning en de nachtelijke inspectie." },
      { range: "3-7", title: "De bouw", summary: "De verdeling van het werk, de tegenstand van Sanballat en de sociale hervorming." },
      { range: "8-10", title: "De wet", summary: "Ezra leest voor, het loofhuttenfeest, de schuldbelijdenis en het verbond." },
      { range: "11-13", title: "Bewoning en terugval", summary: "Wie in Jeruzalem gaat wonen, de inwijding van de muur en Nehemia's laatste maatregelen." },
    ],
    keyVerses: ["Nehemia 1:4-6", "Nehemia 4:6", "Nehemia 6:3", "Nehemia 8:10"],
    studyQuestions: [
      "Tel de korte gebeden die Nehemia midden in het handelen bidt. Wat valt op aan hun lengte en timing?",
      "Welke vijf vormen van tegenstand komt Nehemia tegen, en hoe reageert hij op elke vorm?",
      "Waarom huilt het volk bij het horen van de wet, en waarom zegt Nehemia dat ze dat niet moeten doen?",
    ],
  },
  {
    slug: "esther",
    name: "Esther",
    position: 17,
    testament: "oude-testament",
    genre: "Geschiedenis",
    chapters: 10,
    author: "Anoniem.",
    written: "Waarschijnlijk 4e-3e eeuw v.Chr.",
    theme: "God wordt niet genoemd en is overal: een dreigende genocide loopt uit op Purim.",
    blurb:
      "Esther: een Joodse koningin aan het Perzische hof, het plan van Haman, en de omkering die Purim werd. Hoofdlijn en studievragen.",
    summary: [
      "Esther is het enige bijbelboek waarin God niet één keer wordt genoemd. Geen gebed dat verhoord wordt, geen profeet, geen wonder. En juist daardoor is het een van de scherpste boeken over voorzienigheid die er zijn.",
      "Het verhaal speelt aan het hof van Ahasveros in Susan. Een Joods meisje wordt koningin zonder dat haar afkomst bekend is. Haman, de hoogste rijksbestuurder, raakt gekrenkt door Mordechai en zet daarop een decreet in gang om alle Joden in het rijk te doden. Mordechai's woorden aan Esther - 'wie weet of gij niet om zulken tijd als deze tot dit koninkrijk geraakt zijt' - laten precies de ruimte open die het hele boek kenmerkt.",
      "De ontknoping bestaat uit een reeks omkeringen: een slapeloze nacht, een verkeerd begrepen vraag, een galg die de bouwer zelf treft. Het feest van Purim, dat het jodendom tot vandaag viert, komt hier vandaan.",
    ],
    outline: [
      { range: "1-2", title: "Aan het hof", summary: "Vasthi's weigering en de kroning van Esther." },
      { range: "3-5", title: "Hamans plan", summary: "Het decreet, Mordechai's rouw, en Esthers riskante gang naar de koning." },
      { range: "6-7", title: "De omkering", summary: "De slapeloze nacht van de koning en de val van Haman." },
      { range: "8-10", title: "Redding en Purim", summary: "Het tweede decreet, de verdediging en de instelling van het feest." },
    ],
    keyVerses: ["Esther 4:14", "Esther 4:16", "Esther 6:1", "Esther 9:22"],
    studyQuestions: [
      "God wordt niet genoemd. Waar in het verhaal zie je toch sturing, en waaraan herken je die?",
      "Wat riskeert Esther precies in 4:16, en waarom vraagt ze om vasten?",
      "Welke omkeringen kun je opsommen? Maak een lijst van wat er precies omdraait.",
    ],
  },
];
