/**
 * Cache-Control for the public content endpoints.
 *
 * These routes are pure functions of their query string: the same book,
 * chapter and version produce the same bytes for every caller, and none of
 * them reads a session, a cookie or an entitlement. Until now they sent no
 * Cache-Control at all, so every re-read of a chapter woke a serverless
 * function to re-serve bytes it had already served - which on Vercel's Fluid
 * pricing is Active CPU billed per request.
 *
 * With this header the Edge Network answers the repeats and the function is
 * only reached on a miss.
 *
 * **Never put this on a response that depends on who is asking.** A shared
 * cache entry is shared with everyone who can reach the URL, so an
 * entitlement-gated body would leak a subscriber's copy to a free reader.
 * `/api/commentary` is exactly that case and stays `private, no-store`; see
 * the note in that route.
 *
 * `s-maxage` is a week rather than a year even though scripture does not
 * change, because the data files are regenerated by `npm run sync-data` at
 * build time: a correction to the source needs a bounded window in which it
 * reaches readers even if nothing invalidates the cache explicitly. The
 * browser copy is deliberately short - a stale CDN entry can be purged, a
 * stale entry in someone's browser cannot.
 */
export const PUBLIC_CONTENT_CACHE_CONTROL =
  'public, max-age=3600, s-maxage=604800, stale-while-revalidate=86400';

/** Seconds left in the current Europe/Amsterdam calendar day (at least 1). */
export function secondsUntilAmsterdamMidnight(now = new Date()): number {
  const parts = new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Europe/Amsterdam',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hourCycle: 'h23',
  }).formatToParts(now);
  const part = (type: string) => Number(parts.find((p) => p.type === type)?.value ?? 0);
  const elapsed = part('hour') * 3600 + part('minute') * 60 + part('second');
  return Math.max(1, 86_400 - elapsed);
}

/**
 * The verse of the day changes at Amsterdam midnight, so every cache lifetime
 * - browser, CDN, and the stale-while-revalidate window after it - is capped
 * at the time left in the day. Hourly shared copies as before during the day;
 * no cache can hand out yesterday's verse after 00:00.
 */
export function dayTextCacheControl(now = new Date()): string {
  const left = secondsUntilAmsterdamMidnight(now);
  const sMaxAge = Math.min(3600, left);
  return `public, max-age=${Math.min(600, left)}, s-maxage=${sMaxAge}, stale-while-revalidate=${left - sMaxAge}`;
}
