/**
 * Cache-Control for the public content endpoints.
 *
 * These routes are pure functions of their query string: the same book,
 * chapter and version produce the same bytes for every caller, and none of
 * them reads a session, a cookie or an entitlement. Until now they sent no
 * Cache-Control at all, so every re-read of a chapter woke a serverless
 * function to re-serve bytes it had already served - which on Vercel's Fluid
 * pricing is Active CPU billed per request.
 *
 * With this header the Edge Network answers the repeats and the function is
 * only reached on a miss.
 *
 * **Never put this on a response that depends on who is asking.** A shared
 * cache entry is shared with everyone who can reach the URL, so an
 * entitlement-gated body would leak a subscriber's copy to a free reader.
 * `/api/commentary` is exactly that case and stays `private, no-store`; see
 * the note in that route.
 *
 * `s-maxage` is a week rather than a year even though scripture does not
 * change, because the data files are regenerated by `npm run sync-data` at
 * build time: a correction to the source needs a bounded window in which it
 * reaches readers even if nothing invalidates the cache explicitly. The
 * browser copy is deliberately short - a stale CDN entry can be purged, a
 * stale entry in someone's browser cannot.
 */
export const PUBLIC_CONTENT_CACHE_CONTROL =
  'public, max-age=3600, s-maxage=604800, stale-while-revalidate=86400';

/** One verse per day upstream, so the shared copy expires hourly. */
export const DAY_TEXT_CACHE_CONTROL =
  'public, max-age=600, s-maxage=3600, stale-while-revalidate=86400';
