import type { LucideIcon } from "lucide-react";
import {
  Award,
  Bell,
  BookMarked,
  Bookmark,
  CircleHelp,
  CreditCard,
  Eye,
  FileText,
  GraduationCap,
  House,
  KeyRound,
  Library,
  LifeBuoy,
  LogIn,
  LogOut,
  Mail,
  MessageSquare,
  Monitor,
  Moon,
  NotebookPen,
  Pencil,
  Play,
  Plus,
  Settings,
  Shield,
  Smartphone,
  SunMedium,
  SunMoon,
  Trash2,
  TreeDeciduous,
  Type,
  User,
  Users,
  Volume2,
  Newspaper,
  File,
} from "lucide-react";
import type { IconKey } from "../../lib/commands/types";

/** Registry icon keys to lucide components. Every icon names a data type or a control. */
export const COMMAND_ICONS: Record<IconKey, LucideIcon> = {
  page: File,
  home: House,
  book: BookMarked,
  study: GraduationCap,
  note: NotebookPen,
  bookmark: Bookmark,
  group: Users,
  library: Library,
  user: User,
  tree: TreeDeciduous,
  settings: Settings,
  subscription: CreditCard,
  feedback: MessageSquare,
  help: LifeBuoy,
  mail: Mail,
  guide: Newspaper,
  phone: Smartphone,
  document: FileText,
  admin: Shield,
  login: LogIn,
  logout: LogOut,
  sun: SunMedium,
  moon: Moon,
  monitor: Monitor,
  theme: SunMoon,
  text: Type,
  voice: Volume2,
  bell: Bell,
  key: KeyRound,
  trash: Trash2,
  plus: Plus,
  edit: Pencil,
  badge: Award,
  play: Play,
  eye: Eye,
  question: CircleHelp,
};
