import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { it } from 'vitest';
import { generateTree, GROUND_Y } from '../../lib/levensboom/generate';
import { generateTreeV1 } from '../../lib/levensboom/v1/generateV1';

/**
 * `npm run tree:calibrate` - regenerates `lib/levensboom/growthRef.ts`:
 * `LEGACY_EQUIV`, for each v1 level the smallest v2 position whose median eik
 * is at least as tall as the v1 eik was (plan §5.4). Eik is the reference for
 * every species, so switching species never moves a floor. Server-only: the
 * app receives floors ready-made.
 *
 * Run it after every change to the growth table. Deterministic: the same
 * generator always writes the same numbers.
 */

const SEEDS = Array.from({ length: 48 }, (_, i) => `65f0c1a2b3c4d5e6f7a8${(0x1000 + i * 7919).toString(16).padStart(4, '0')}`);
const LEGACY_LEVELS = 80;
const V2_STEP = 0.1;
const V2_MAX = 90;

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

function v2Height(position: number): number {
  const level = Math.floor(position);
  return median(
    SEEDS.map((seed) => {
      const { bounds } = generateTree({ seed, level, frac: position - level, health: 1, species: 'eik', at: { position } });
      return GROUND_Y - bounds.minY;
    }),
  );
}

function v1Height(level: number): number {
  return median(
    SEEDS.map((seed) => GROUND_Y - generateTreeV1({ seed, level, frac: 0.5, health: 1, species: 'eik' }).bounds.minY),
  );
}

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

it('calibrates the legacy table', async () => {
  // Yield now and then so the vitest worker can answer its RPC heartbeats.
  const breathe = () => new Promise((resolve) => setTimeout(resolve, 0));

  // v2 eik heights on a fine grid, made non-decreasing so "the first position
  // at least this tall" is well defined.
  const grid: [number, number][] = [];
  let tallest = 0;
  for (let p = 1; p <= V2_MAX + 1e-9; p += V2_STEP) {
    tallest = Math.max(tallest, v2Height(p));
    grid.push([Math.round(p * 10) / 10, tallest]);
    if (grid.length % 50 === 0) await breathe();
  }
  const legacy: [number, number][] = [];
  let last = 1;
  for (let level = 1; level <= LEGACY_LEVELS; level += 1) {
    const want = v1Height(level);
    const hit = grid.find(([, h]) => h >= want);
    // Past the grid the v2 tree never gets that tall: no floor can promise it,
    // so the table stops promising more than the grid's end.
    const e = Math.max(last, hit ? hit[0] : V2_MAX, level);
    legacy.push([level, Math.round(e * 10) / 10]);
    last = e;
  }

  const ts = [
    '/**',
    ' * GENERATED by `npm run tree:calibrate` - do not edit by hand.',
    ' *',
    ' * [v1 level, v2 position of equal median eik height], plan §5.4. Server-only:',
    ' * clients receive the floor ready-made. Linear in between, +1 per step past',
    ' * the end.',
    ' */',
    '',
    'export const LEGACY_EQUIV: readonly (readonly [number, number])[] = [',
    ...chunk(legacy.map(([p, e]) => `[${p}, ${e}]`), 8).map((row) => `  ${row.join(', ')},`),
    '];',
    '',
  ].join('\n');
  writeFileSync(path.resolve(__dirname, '../../lib/levensboom/growthRef.ts'), ts);

  console.log('legacy', legacy.map(([p, e]) => `${p}->${e}`).join(' '));
});
