import { HELP_TOPICS, faqAnchor } from "../content/helpFaq";
import type { CommandItem } from "./types";

/**
 * Every command the palette knows, as plain data.
 *
 * Only platform surfaces live here: pages, individual settings, actions and
 * help. Nothing in this file may search or list bible text, commentaries,
 * studies content or the reader's notes.
 *
 * Links into /instellingen use `?sectie=<tab>#instelling-<control>`; links into
 * /groepen and /profiel use `?actie=`. The allowed values live in
 * lib/commands/deepLink.ts and tests/commandRegistry.test.ts keeps both honest.
 */

const setting = (sectie: string, anchor: string) => `/instellingen?sectie=${sectie}#instelling-${anchor}`;

export const PAGE_COMMANDS: CommandItem[] = [
  {
    id: "pagina-dashboard",
    group: "pagina",
    title: "Dashboard",
    subtitle: "Je voortgang, streak en dagtekst",
    keywords: ["home", "start", "overzicht", "beginscherm", "hoofdpagina", "streak", "dagtekst", "tekst van de dag", "reeks"],
    icon: "home",
    visibility: "ingelogd",
    target: { type: "link", href: "/dashboard" },
    pageKey: "dashboard",
    showWhenEmpty: true,
  },
  {
    id: "pagina-lezen",
    group: "pagina",
    title: "Lezen",
    subtitle: "De Bijbel lezen",
    keywords: ["bijbel", "bijbel lezen", "hoofdstuk", "tekst", "lezer", "vertaling", "bijbeltekst", "schrift"],
    icon: "book",
    visibility: "iedereen",
    target: { type: "link", href: "/lezen" },
    pageKey: "read",
    // Not under "Snel naar": "Verder lezen" already goes to /lezen there.
  },
  {
    id: "pagina-studies",
    group: "pagina",
    title: "Studies",
    subtitle: "Begeleide bijbelstudies",
    keywords: ["begeleide studies", "bijbelstudies", "cursus", "lessen", "studieplan", "leesplan"],
    icon: "study",
    visibility: "iedereen",
    target: { type: "link", href: "/studies" },
    pageKey: "studies",
    showWhenEmpty: true,
  },
  {
    id: "pagina-notities",
    group: "pagina",
    title: "Notities",
    subtitle: "Al je notities en markeringen",
    keywords: ["aantekeningen", "markeringen", "highlights", "opmerkingen", "dagboek"],
    icon: "note",
    visibility: "ingelogd",
    target: { type: "link", href: "/notities" },
    pageKey: "notes",
    showWhenEmpty: true,
  },
  {
    id: "pagina-notities-bewaard",
    group: "pagina",
    title: "Bewaarde studies",
    subtitle: "Notities · Bewaard",
    keywords: ["bewaard", "opgeslagen", "favorieten", "later lezen", "bladwijzer"],
    icon: "bookmark",
    visibility: "ingelogd",
    target: { type: "link", href: "/notities?tab=bewaard" },
  },
  {
    id: "pagina-groepen",
    group: "pagina",
    title: "Groepen",
    subtitle: "Samen studeren",
    keywords: ["groep", "bijbelkring", "gemeente", "samen", "vrienden", "kring"],
    icon: "group",
    visibility: "ingelogd",
    target: { type: "link", href: "/groepen" },
    pageKey: "groups",
  },
  {
    id: "pagina-hulpbronnen",
    group: "pagina",
    title: "Hulpbronnen",
    subtitle: "Gratis bijbelstudieboeken",
    keywords: ["bibliotheek", "boeken", "bronnen", "publiek domein", "materiaal", "e-books"],
    icon: "library",
    visibility: "iedereen",
    target: { type: "link", href: "/hulpbronnen" },
    pageKey: "resources",
  },
  {
    id: "pagina-profiel",
    group: "pagina",
    title: "Profiel",
    subtitle: "Je naam, bio en badges",
    keywords: ["account", "mijn profiel", "gebruiker", "ik", "badges", "niveau"],
    icon: "user",
    visibility: "ingelogd",
    target: { type: "link", href: "/profiel" },
    pageKey: "profile",
  },
  {
    id: "pagina-boom",
    group: "pagina",
    title: "Je boom",
    subtitle: "Voortgang en niveau",
    keywords: ["voortgang", "boom", "avatar", "xp", "niveau", "groei", "levensboom"],
    icon: "tree",
    visibility: "ingelogd",
    target: { type: "link", href: "/profiel/boom" },
    pageKey: "profileTree",
  },
  {
    id: "pagina-instellingen",
    group: "pagina",
    title: "Instellingen",
    subtitle: "Leesweergave, meldingen, account",
    keywords: ["voorkeuren", "opties", "configuratie", "settings", "aanpassen"],
    icon: "settings",
    visibility: "ingelogd",
    target: { type: "link", href: "/instellingen" },
    pageKey: "settings",
  },
  {
    id: "pagina-abonnement",
    group: "pagina",
    title: "Abonnement",
    subtitle: "Prijzen en Pro",
    keywords: ["prijzen", "pro", "kosten", "betalen", "premium", "tarieven", "prijs", "wat kost"],
    icon: "subscription",
    visibility: "iedereen",
    target: { type: "link", href: "/abonnement" },
    pageKey: "subscribe",
  },
  {
    id: "pagina-feedback",
    group: "pagina",
    title: "Feedback",
    subtitle: "Laat weten wat beter kan",
    keywords: ["suggestie", "idee", "bug", "probleem melden", "reactie", "mening"],
    icon: "feedback",
    visibility: "ingelogd",
    target: { type: "link", href: "/feedback" },
    pageKey: "feedback",
  },
  {
    id: "pagina-help",
    group: "pagina",
    title: "Help",
    subtitle: "Veelgestelde vragen",
    keywords: ["hulp", "faq", "vragen", "ondersteuning", "support", "uitleg"],
    icon: "help",
    visibility: "iedereen",
    target: { type: "link", href: "/help" },
    pageKey: "help",
  },
  {
    id: "pagina-contact",
    group: "pagina",
    title: "Contact",
    subtitle: "Neem contact met ons op",
    keywords: ["mail", "e-mail", "bericht", "vraag stellen", "klantenservice", "support", "helpdesk", "contactformulier"],
    icon: "mail",
    visibility: "iedereen",
    target: { type: "link", href: "/contact" },
    pageKey: "contact",
  },
  {
    id: "pagina-gids",
    group: "pagina",
    title: "Bijbelstudie: de complete gids",
    subtitle: "Gids",
    keywords: ["gids", "handleiding", "hoe studeer je", "uitleg bijbelstudie", "artikel"],
    icon: "guide",
    visibility: "iedereen",
    target: { type: "link", href: "/bijbelstudie" },
    pageKey: "guideHub",
  },
  {
    id: "pagina-gids-methoden",
    group: "pagina",
    title: "Bijbelstudie methoden",
    subtitle: "Gids · 6 beproefde manieren",
    keywords: ["methoden", "methode", "inductief", "thematisch", "woordstudie", "gids"],
    icon: "guide",
    visibility: "iedereen",
    target: { type: "link", href: "/bijbelstudie/methoden" },
    pageKey: "guideMethods",
  },
  {
    id: "pagina-gids-beginnen",
    group: "pagina",
    title: "Bijbelstudie voor beginners",
    subtitle: "Gids · zo begin je",
    keywords: ["beginners", "beginnen", "starten", "nieuw", "eerste keer", "gids"],
    icon: "guide",
    visibility: "iedereen",
    target: { type: "link", href: "/bijbelstudie/beginnen" },
    pageKey: "guideStart",
  },
  {
    id: "pagina-gids-online",
    group: "pagina",
    title: "Online bijbelstudie",
    subtitle: "Gids · wat digitaal beter kan",
    keywords: ["online", "digitaal", "internet", "website", "gids"],
    icon: "guide",
    visibility: "iedereen",
    target: { type: "link", href: "/bijbelstudie/online" },
    pageKey: "guideOnline",
  },
  {
    id: "pagina-gids-gratis",
    group: "pagina",
    title: "Gratis bijbelstudie",
    subtitle: "Gids · alles wat gratis kan",
    keywords: ["gratis", "kosteloos", "zonder betalen", "free", "gids"],
    icon: "guide",
    visibility: "iedereen",
    target: { type: "link", href: "/bijbelstudie/gratis" },
    pageKey: "guideFree",
  },
  {
    id: "pagina-bijbelboeken",
    group: "pagina",
    title: "Bijbelboeken",
    subtitle: "De 66 boeken op een rij",
    keywords: ["boeken", "66 boeken", "oude testament", "nieuwe testament", "overzicht", "canon"],
    icon: "book",
    visibility: "iedereen",
    target: { type: "link", href: "/bijbelboeken" },
    pageKey: "bibleBooks",
  },
  {
    id: "pagina-app",
    group: "pagina",
    title: "Download de app",
    subtitle: "BijbelStudie voor iPhone",
    keywords: ["app", "iphone", "ios", "mobiel", "telefoon", "downloaden", "app store"],
    icon: "phone",
    visibility: "iedereen",
    target: { type: "link", href: "/app" },
    pageKey: "appDownload",
  },
  {
    id: "pagina-privacybeleid",
    group: "pagina",
    title: "Privacybeleid",
    subtitle: "Hoe we met je gegevens omgaan",
    keywords: ["privacy", "privé", "avg", "gdpr", "gegevens", "cookies", "persoonsgegevens"],
    icon: "document",
    visibility: "iedereen",
    target: { type: "link", href: "/privacybeleid" },
    pageKey: "privacyPolicy",
  },
  {
    id: "pagina-voorwaarden",
    group: "pagina",
    title: "Algemene voorwaarden",
    subtitle: "De gebruiksvoorwaarden",
    keywords: ["voorwaarden", "gebruiksvoorwaarden", "terms", "juridisch", "regels"],
    icon: "document",
    visibility: "iedereen",
    target: { type: "link", href: "/algemene-voorwaarden" },
    pageKey: "termsOfService",
  },
  {
    id: "pagina-beheer",
    group: "pagina",
    title: "Beheer",
    subtitle: "Beheeroverzicht",
    keywords: ["admin", "beheerder", "dashboard beheer", "statistieken", "omzet"],
    icon: "admin",
    visibility: "admin",
    target: { type: "link", href: "/beheer" },
    pageKey: "admin",
  },
  {
    id: "pagina-beheer-gebruikers",
    group: "pagina",
    title: "Gebruikersbeheer",
    subtitle: "Beheer",
    keywords: ["gebruikers", "accounts", "admin", "leden", "klanten"],
    icon: "admin",
    visibility: "admin",
    target: { type: "link", href: "/beheer/gebruikers" },
  },
  {
    id: "pagina-beheer-feedback",
    group: "pagina",
    title: "Feedback beheren",
    subtitle: "Beheer",
    keywords: ["feedback", "admin", "reacties", "meldingen gebruikers", "inzendingen"],
    icon: "admin",
    visibility: "admin",
    target: { type: "link", href: "/beheer/feedback" },
  },
  {
    id: "pagina-beheer-inzichten",
    group: "pagina",
    title: "Inzichten",
    subtitle: "Beheer · bereik en paginaweergaven",
    keywords: ["analytics", "statistieken", "bezoekers", "paginaweergaven", "admin", "bereik"],
    icon: "admin",
    visibility: "admin",
    target: { type: "link", href: "/beheer/inzichten" },
  },
  {
    id: "pagina-inloggen",
    group: "pagina",
    title: "Inloggen",
    subtitle: "Log in op je account",
    keywords: ["login", "aanmelden", "sign in", "account", "google"],
    icon: "login",
    visibility: "gast",
    target: { type: "link", href: "/inloggen" },
    pageKey: "signin",
    showWhenEmpty: true,
  },
  {
    id: "pagina-registreren",
    group: "pagina",
    title: "Registreren",
    subtitle: "Maak gratis een account",
    keywords: ["account aanmaken", "aanmelden", "sign up", "gratis beginnen", "nieuw account"],
    icon: "user",
    visibility: "gast",
    target: { type: "link", href: "/registreren" },
    pageKey: "register",
    showWhenEmpty: true,
  },
  {
    id: "pagina-account-verwijderen",
    group: "pagina",
    title: "Account laten verwijderen",
    subtitle: "Zo verwijder je je account en je gegevens",
    keywords: ["account verwijderen", "gegevens verwijderen", "account opheffen", "uitschrijven", "privacy", "data wissen"],
    icon: "trash",
    // Signed in, "Account verwijderen" under Acties goes straight to the control.
    visibility: "gast",
    target: { type: "link", href: "/account-verwijderen" },
    pageKey: "accountDeletion",
  },
];

export const SETTING_COMMANDS: CommandItem[] = [
  {
    id: "instelling-thema",
    group: "instelling",
    title: "Thema",
    subtitle: "Instellingen · Leesweergave",
    keywords: ["weergave", "donker", "licht", "dark mode", "kleur", "systeem", "nachtmodus", "donkere modus", "lichte modus", "kleurenschema"],
    icon: "theme",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "thema") },
  },
  {
    id: "instelling-vertaling",
    group: "instelling",
    title: "Standaard bijbelvertaling",
    subtitle: "Instellingen · Leesweergave",
    keywords: ["vertaling", "bijbelvertaling", "statenvertaling", "kjv", "versie", "taal", "canisius", "engels", "king james"],
    icon: "book",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "vertaling") },
  },
  {
    id: "instelling-commentaar",
    group: "instelling",
    title: "Standaard commentaar",
    subtitle: "Instellingen · Leesweergave",
    keywords: ["commentaar", "uitleg", "kingcomments", "matthew henry", "calvijn", "verklaring"],
    icon: "book",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "commentaar") },
  },
  {
    id: "instelling-tekstgrootte",
    group: "instelling",
    title: "Tekstgrootte",
    subtitle: "Instellingen · Leesweergave",
    keywords: ["lettergrootte", "grootte", "groter", "kleiner", "zoom", "leesbaarheid", "letters groter", "tekst groter", "slechtziend"],
    icon: "text",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "tekstgrootte") },
  },
  {
    id: "instelling-regelafstand",
    group: "instelling",
    title: "Regelafstand",
    subtitle: "Instellingen · Leesweergave",
    keywords: ["regels", "afstand", "ruimte", "compact", "ruim", "interlinie"],
    icon: "text",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "regelafstand") },
  },
  {
    id: "instelling-lettertype",
    group: "instelling",
    title: "Lettertype",
    subtitle: "Instellingen · Leesweergave",
    keywords: ["font", "schreef", "schreefloos", "letter", "typografie"],
    icon: "text",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "lettertype") },
  },
  {
    id: "instelling-letterafstand",
    group: "instelling",
    title: "Letterafstand",
    subtitle: "Instellingen · Leesweergave",
    keywords: ["spatiering", "letters", "afstand", "breed", "strak"],
    icon: "text",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "letterafstand") },
  },
  {
    id: "instelling-versnummers",
    group: "instelling",
    title: "Versnummers tonen",
    subtitle: "Instellingen · Leesweergave",
    keywords: ["versnummers", "nummers", "verzen", "verbergen", "tonen"],
    icon: "text",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "versnummers") },
  },
  {
    id: "instelling-stem",
    group: "instelling",
    title: "Standaard stem",
    subtitle: "Instellingen · Voorlezen",
    keywords: ["voorlezen", "stem", "audio", "luisteren", "tts", "voorleesstem"],
    icon: "voice",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "stem") },
  },
  {
    id: "instelling-standaard-herstellen",
    group: "instelling",
    title: "Leesweergave terugzetten",
    subtitle: "Instellingen · Standaard herstellen",
    keywords: ["reset", "standaard", "herstellen", "terugzetten", "standaardinstellingen"],
    icon: "settings",
    visibility: "ingelogd",
    target: { type: "link", href: setting("lezen", "standaard-herstellen") },
  },
  {
    id: "instelling-herinneringen",
    group: "instelling",
    title: "Herinneringen",
    subtitle: "Instellingen · Meldingen",
    keywords: ["meldingen", "notificaties", "herinnering", "push", "melding aan", "melding uit", "notificatie", "reminder"],
    icon: "bell",
    visibility: "ingelogd",
    target: { type: "link", href: setting("meldingen", "herinneringen") },
  },
  {
    id: "instelling-herinneringstijd",
    group: "instelling",
    title: "Studieherinnering tijdstip",
    subtitle: "Instellingen · Meldingen",
    keywords: ["tijd", "tijdstip", "uur", "wanneer", "dagelijkse herinnering", "wekker"],
    icon: "bell",
    visibility: "ingelogd",
    target: { type: "link", href: setting("meldingen", "herinneringstijd") },
  },
  {
    id: "instelling-boom-tonen",
    group: "instelling",
    title: "Boom tonen",
    subtitle: "Instellingen · Account · Voortgang",
    keywords: ["boom", "verbergen", "voortgang", "avatar", "levensboom", "uitzetten"],
    icon: "tree",
    visibility: "ingelogd",
    target: { type: "link", href: setting("account", "boom-tonen") },
  },
  {
    id: "instelling-minder-beweging",
    group: "instelling",
    title: "Minder beweging",
    subtitle: "Instellingen · Account · Voortgang",
    keywords: ["animatie", "beweging", "rustig", "toegankelijkheid", "reduced motion"],
    icon: "eye",
    visibility: "ingelogd",
    target: { type: "link", href: setting("account", "minder-beweging") },
  },
  {
    id: "instelling-openbaar-profiel",
    group: "instelling",
    title: "Openbaar profiel",
    subtitle: "Instellingen · Account · Voortgang",
    keywords: ["openbaar", "publiek", "delen", "privacy", "zichtbaar", "profiellink", "prive", "verbergen"],
    icon: "eye",
    visibility: "ingelogd",
    target: { type: "link", href: setting("account", "openbaar-profiel") },
  },
  {
    id: "instelling-abonnement",
    group: "instelling",
    title: "Abonnement en facturen",
    subtitle: "Instellingen · Abonnement",
    keywords: ["facturen", "betaalgegevens", "opzeggen", "pauzeren", "betaling", "creditcard"],
    icon: "subscription",
    visibility: "pro",
    target: { type: "link", href: setting("abonnement", "abonnement") },
    pro: true,
  },
  {
    id: "instelling-over",
    group: "instelling",
    title: "Over BijbelStudie",
    subtitle: "Instellingen · Over",
    keywords: ["over", "info", "versie", "documenten", "iphone-app"],
    icon: "settings",
    visibility: "ingelogd",
    target: { type: "link", href: setting("over", "over") },
  },
];

export const ACTION_COMMANDS: CommandItem[] = [
  {
    id: "actie-thema-donker",
    group: "actie",
    title: "Donkere modus",
    subtitle: "Thema wijzigen",
    keywords: ["donker", "dark mode", "nachtmodus", "zwart", "thema donker", "avond"],
    icon: "moon",
    visibility: "iedereen",
    target: { type: "run", run: "theme:dark" },
  },
  {
    id: "actie-thema-licht",
    group: "actie",
    title: "Lichte modus",
    subtitle: "Thema wijzigen",
    keywords: ["licht", "light mode", "dagmodus", "wit", "thema licht"],
    icon: "sun",
    visibility: "iedereen",
    target: { type: "run", run: "theme:light" },
  },
  {
    id: "actie-thema-systeem",
    group: "actie",
    title: "Thema volgt systeem",
    subtitle: "Thema wijzigen",
    keywords: ["systeem", "automatisch", "system", "thema systeem", "apparaat"],
    icon: "monitor",
    visibility: "iedereen",
    target: { type: "run", run: "theme:system" },
  },
  {
    id: "actie-thema-wisselen",
    group: "actie",
    title: "Thema wisselen",
    subtitle: "Tussen licht en donker",
    keywords: ["wisselen", "toggle", "omschakelen", "donker", "licht", "dark mode"],
    icon: "theme",
    visibility: "iedereen",
    target: { type: "run", run: "theme:toggle" },
    showWhenEmpty: true,
  },
  {
    id: "actie-verder-lezen",
    group: "actie",
    title: "Verder lezen",
    subtitle: "Ga door in de Bijbel",
    keywords: ["doorgaan", "hervatten", "lezen", "bijbel", "hoofdstuk", "verder"],
    icon: "play",
    visibility: "iedereen",
    target: { type: "link", href: "/lezen" },
    showWhenEmpty: true,
  },
  {
    id: "actie-verder-studie",
    group: "actie",
    title: "Verder met je studie",
    subtitle: "Ga door waar je was",
    keywords: ["doorgaan", "hervatten", "studie", "les", "verder", "studeren"],
    icon: "play",
    visibility: "ingelogd",
    target: { type: "link", href: "/studie" },
    showWhenEmpty: true,
  },
  {
    id: "actie-studie-starten",
    group: "actie",
    title: "Studie starten",
    subtitle: "Kies een begeleide studie",
    keywords: ["nieuwe studie", "beginnen", "studeren", "cursus", "begeleide studie"],
    icon: "study",
    visibility: "iedereen",
    target: { type: "link", href: "/studies" },
  },
  {
    id: "actie-notitie-maken",
    group: "actie",
    title: "Notitie maken",
    subtitle: "Kies een vers in de tekst",
    keywords: ["nieuwe notitie", "aantekening", "schrijven", "opschrijven", "markeren"],
    icon: "note",
    visibility: "ingelogd",
    target: { type: "link", href: "/lezen" },
  },
  {
    id: "actie-groep-aanmaken",
    group: "actie",
    title: "Groep aanmaken",
    subtitle: "Start een nieuwe groep",
    keywords: ["nieuwe groep", "groep maken", "groep starten", "bijbelkring", "oprichten"],
    icon: "plus",
    visibility: "ingelogd",
    target: { type: "link", href: "/groepen?actie=aanmaken" },
    pro: true,
  },
  {
    id: "actie-groep-code",
    group: "actie",
    title: "Deelnemen met code",
    subtitle: "Word lid met een uitnodigingscode",
    keywords: ["uitnodigingscode", "code", "lid worden", "groep", "uitnodiging", "aansluiten"],
    icon: "group",
    visibility: "ingelogd",
    target: { type: "link", href: "/groepen?actie=code" },
  },
  {
    id: "actie-naam-wijzigen",
    group: "actie",
    title: "Naam wijzigen",
    subtitle: "Profiel",
    keywords: ["naam", "gebruikersnaam", "hernoemen", "naam aanpassen", "profiel"],
    icon: "edit",
    visibility: "ingelogd",
    target: { type: "link", href: "/profiel?actie=naam" },
  },
  {
    id: "actie-bio-wijzigen",
    group: "actie",
    title: "Bio wijzigen",
    subtitle: "Profiel",
    keywords: ["bio", "beschrijving", "over mij", "over jou", "profieltekst"],
    icon: "edit",
    visibility: "ingelogd",
    target: { type: "link", href: "/profiel?actie=bio" },
  },
  {
    id: "actie-badges-bekijken",
    group: "actie",
    title: "Badges bekijken",
    subtitle: "Profiel",
    keywords: ["badges", "prestaties", "onderscheidingen", "achievements", "medailles"],
    icon: "badge",
    visibility: "ingelogd",
    target: { type: "link", href: "/profiel?actie=badges" },
  },
  {
    id: "actie-boom-aanpassen",
    group: "actie",
    title: "Boom aanpassen",
    subtitle: "Soort, seizoen en omgeving",
    keywords: ["boom", "avatar", "studio", "aanpassen", "uiterlijk", "levensboom"],
    icon: "tree",
    visibility: "ingelogd",
    target: { type: "link", href: "/profiel/boom" },
  },
  {
    id: "actie-upgraden",
    group: "actie",
    title: "Upgraden naar Pro",
    subtitle: "Alle commentaren en meer AI-vragen",
    keywords: ["pro", "upgrade", "premium", "abonneren", "kopen", "betalen", "abonnement", "pro worden", "lid worden", "commentaren"],
    icon: "subscription",
    visibility: "gratis",
    target: { type: "link", href: "/abonnement" },
    pro: true,
  },
  {
    id: "actie-abonnement-beheren",
    group: "actie",
    title: "Abonnement beheren",
    subtitle: "Facturen, pauzeren of opzeggen",
    keywords: ["opzeggen", "stoppen", "annuleren", "facturen", "pauzeren", "abonnement"],
    icon: "subscription",
    visibility: "pro",
    target: { type: "link", href: setting("abonnement", "abonnement") },
    pro: true,
  },
  {
    id: "actie-feedback",
    group: "actie",
    title: "Feedback geven",
    subtitle: "Idee of probleem melden",
    keywords: ["feedback", "suggestie", "bug melden", "probleem", "idee", "verbeteren"],
    icon: "feedback",
    visibility: "ingelogd",
    target: { type: "link", href: "/feedback" },
  },
  {
    id: "actie-wachtwoord-wijzigen",
    group: "actie",
    title: "Wachtwoord wijzigen",
    subtitle: "Instellingen · Account",
    keywords: ["wachtwoord", "password", "veranderen", "nieuw wachtwoord", "beveiliging", "wachtwoord instellen", "wachtwoord aanpassen", "inloggegevens"],
    icon: "key",
    visibility: "ingelogd",
    target: { type: "link", href: setting("account", "wachtwoord") },
  },
  {
    id: "actie-wachtwoord-vergeten",
    group: "actie",
    title: "Wachtwoord vergeten",
    subtitle: "Stel een nieuw wachtwoord in",
    keywords: ["wachtwoord", "password", "reset", "kwijt", "herstellen", "inloggen lukt niet"],
    icon: "key",
    visibility: "gast",
    target: { type: "link", href: "/wachtwoord-vergeten" },
    pageKey: "forgotPassword",
  },
  {
    id: "actie-account-verwijderen",
    group: "actie",
    title: "Account verwijderen",
    subtitle: "Instellingen · Account",
    keywords: ["verwijderen", "account opheffen", "uitschrijven", "gegevens wissen", "stoppen", "account wissen", "gegevens verwijderen", "avg"],
    icon: "trash",
    visibility: "ingelogd",
    target: { type: "link", href: setting("account", "account-verwijderen") },
  },
  {
    id: "actie-uitloggen",
    group: "actie",
    title: "Uitloggen",
    subtitle: "Afmelden van dit apparaat",
    keywords: ["afmelden", "logout", "log uit", "sign out", "log out", "uitlog"],
    icon: "logout",
    visibility: "ingelogd",
    target: { type: "run", run: "signout" },
  },
];

/** One command per help topic and one per question, generated from lib/content/helpFaq.ts. */
export function helpCommands(): CommandItem[] {
  const items: CommandItem[] = [];
  for (const topic of HELP_TOPICS) {
    items.push({
      id: `hulp-${topic.id}`,
      group: "hulp",
      title: topic.title,
      subtitle: "Help · onderwerp",
      keywords: ["help", "faq", ...topic.faqs.map((f) => f.q)],
      icon: "help",
      visibility: "iedereen",
      target: { type: "link", href: `/help#${topic.id}` },
    });
    for (const faq of topic.faqs) {
      const anchor = faqAnchor(topic.id, faq.q);
      items.push({
        id: `hulp-${anchor}`,
        group: "hulp",
        title: faq.q,
        subtitle: `Help · ${topic.title}`,
        keywords: ["help", "vraag", topic.title],
        icon: "question",
        visibility: "iedereen",
        target: { type: "link", href: `/help#${anchor}` },
      });
    }
  }
  return items;
}

export const ALL_COMMANDS: CommandItem[] = [
  ...ACTION_COMMANDS,
  ...PAGE_COMMANDS,
  ...SETTING_COMMANDS,
  ...helpCommands(),
];

const BY_ID = new Map(ALL_COMMANDS.map((c) => [c.id, c]));

export function getCommand(id: string): CommandItem | undefined {
  return BY_ID.get(id);
}
